### ISSUE TITLE
Topichead with @copy-to on it throws NPE

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1408]
If I have in the DITA Map something like:

<topichead navtitle="THEAD" copy-to="topics/copyright.dita"/>

The DITA OT throws an error when processing it:

                D:\projects\eXml\frameworks\dita\DITA-OT\plugins\org.dita.base\build_preprocess.xml:35: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'flowers.ditamap'. The XML parser reported the following error: :null
                	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:269)
                	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
                	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
                	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                	at java.lang.reflect.Method.invoke(Unknown Source)
                	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                	at org.apache.tools.ant.Task.perform(Task.java:348)
                	at org.apache.tools.ant.Target.execute(Target.java:390)
                	at org.apache.tools.ant.Target.performTasks(Target.java:411)
                	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
                	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
                	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
                	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
                	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
                	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
                	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
                	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                	at java.lang.reflect.Method.invoke(Unknown Source)
                	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                	at org.apache.tools.ant.Task.perform(Task.java:348)
                	at org.apache.tools.ant.Target.execute(Target.java:390)
                	at org.apache.tools.ant.Target.performTasks(Target.java:411)
                	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
                	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
                	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
                	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
                	at org.apache.tools.ant.Main.runBuild(Main.java:809)
                	at org.apache.tools.ant.Main.startAnt(Main.java:217)
                	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
                	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
                Caused by: org.dita.dost.exception.DITAOTException: [DOTJ012F][FATAL] Failed to parse the input file 'flowers.ditamap'. The XML parser reported the following error: :null
                	at org.dita.dost.module.GenMapAndTopicListModule.processFile(GenMapAndTopicListModule.java:495)
                	at org.dita.dost.module.GenMapAndTopicListModule.processWaitList(GenMapAndTopicListModule.java:418)
                	at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:288)
                	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:63)
                	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:266)
                	... 29 more
                Caused by: java.lang.NullPointerException
                	at org.dita.dost.util.FileUtils.stripFragment(FileUtils.java:698)
                	at org.dita.dost.util.FileUtils.normalizeDirectory(FileUtils.java:411)
                	at org.dita.dost.reader.GenListModuleReader.parseAttribute(GenListModuleReader.java:1513)
                	at org.dita.dost.reader.GenListModuleReader.startElement(GenListModuleReader.java:991)
                	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
                	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
                	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(RelaxNGDefaultsComponent.java:639)
                	at org.apache.xerces.impl.dtd.XMLDTDValidatorXerces.emptyElement(XMLDTDValidatorXerces.java:852)
                	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:260)
                	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1655)
                	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
                	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
                	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:108)
                	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
                	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
                	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
                	at org.dita.dost.reader.GenListModuleReader.parse(GenListModuleReader.java:617)
                	at org.dita.dost.module.GenMapAndTopicListModule.processFile(GenMapAndTopicListModule.java:449)

I started a question here about why the DITA 1.2 specs allows @copy-to on topichead:

https://lists.oasis-open.org/archives/dita-comment/201211/msg00002.html

**Comment by jelovirt** [comment]
Closing as obsolete.
