### ISSUE TITLE
New Java command line tool working example needed

### ISSUE THREAD

**Issue by lagivan** [dita-ot/dita-ot#1839]
I'm struggling to make a new Java command line tool working. I've prepared the following working scenario (Windows batch script):
```
set DITA_HOME=c:\Programs\DITA-OT
set WORK_DIR=c:\Temp\dita

java -classpath "%DITA_HOME%\lib\ant-launcher.jar" "-Dant.home=%DITA_HOME%" org.apache.tools.ant.launch.Launcher -cp "%DITA_HOME%\lib\dost.jar;%DITA_HOME%\lib\xercesImpl.jar;%DITA_HOME%\lib\xml-apis.jar;%DITA_HOME%\lib\xml-resolver.jar;%DITA_HOME%\lib\commons-codec.jar;%DITA_HOME%\lib\saxon.jar;%DITA_HOME%\lib\saxon-dom.jar" -i %DITA_HOME%\samples\taskbook\installing.dita -f pdf -o %WORK_DIR%\out -Dargs.debug=yes -Dargs.logdir=%WORK_DIR%\log -Ddita.dir=%DITA_HOME% -Dclean.temp=yes -Dbasedir=%WORK_DIR%\base -temp=%WORK_DIR%\temp -buildfile "%DITA_HOME%\build.xml" -main "org.dita.dost.invoker.Main"
```
So the above command works fine, the only issue is that log file is not created - seems to be a bug (all directories exist). But my intention is to make a direct call to ```org.dita.dost.invoker.Main``` from another Java library, not via the Ant launcher (as it could be done with ```CommandLineInvoker``` earlier). So I've tried the following:
```
cd %DITA_HOME%
java -classpath "%DITA_HOME%\lib\dost.jar;%DITA_HOME%\lib\xercesImpl.jar;%DITA_HOME%\lib\xml-apis.jar;%DITA_HOME%\lib\xml-resolver.jar;%DITA_HOME%\lib\commons-codec.jar;%DITA_HOME%\lib\saxon.jar;%DITA_HOME%\lib\saxon-dom.jar;%DITA_HOME%\lib\ant.jar;%DITA_HOME%\lib\ant-launcher.jar" org.dita.dost.invoker.Main -i %DITA_HOME%\samples\taskbook\installing.dita -f pdf -o %WORK_DIR%\out -Dargs.debug=yes -Ddita.dir=%DITA_HOME% -Dclean.temp=yes -Dbasedir=%WORK_DIR%\base -temp=%WORK_DIR%\temp -buildfile "%DITA_HOME%\build.xml"
```
However, it fails with the following output:
```
Warning: XML resolver not found; external catalogs will be ignored
Warning: XML resolver not found; external catalogs will be ignored
Error: The following error occurred while executing this line:
c:\Programs\DITA-OT\plugins\org.dita.pdf2\build.xml:335: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 12 errors detected.
```
Please suggest how to make this working and what is the recommended way. Also it would be nice to solve an issue with the missing log file.

**Comment by jelovirt** [comment]
What's wrong with the `dita.bat` that comes with the client distribution so that you cannot use it?

If you want to call DITA-OT from another Java class, you should not do it by calling the `Main` class, but rather via Ant's `Process` class. The `Main` class only handles command line tool related argument parsing, it should not be used for embedding DITA-OT.

**Comment by lagivan** [comment]
Indeed I'd like to call DITA-OT from Java class so ```dita.bat``` is not applicable. You've probably meant Ant's ```Project``` class. I've tried it as well following [this example](http://stackoverflow.com/questions/6733684/run-ant-from-java) with the following code:
```
File buildFile = new File(System.getProperty("ant.home") + "/build.xml");
Project p = new Project();
p.setUserProperty("ant.file", buildFile.getAbsolutePath());
p.init();
ProjectHelper helper = ProjectHelper.getProjectHelper();
p.addReference("ant.projectHelper", helper);
helper.parse(p, buildFile);
p.setProperty("transtype", "pdf");
p.setProperty("args.input", "c:\\Programs\\DITA-OT\\samples\\taskbook\\installing.dita");
p.executeTarget(p.getDefaultTarget());
```
Unfortunately, it does not work throwing almost identical error as above (only it detects 13 errors instead of 12 above):
```
Caused by: c:\Programs\DITA-OT\plugins\org.dita.pdf2\build.xml:136: The following error occurred while executing this line:
c:\Programs\DITA-OT\plugins\org.dita.pdf2\build.xml:335: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 13 errors detected.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:568)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:443)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	... 39 more
Caused by: c:\Programs\DITA-OT\plugins\org.dita.pdf2\build.xml:335: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 13 errors detected.
	at org.apache.tools.ant.taskdefs.XSLTProcess.handleTransformationError(XSLTProcess.java:1443)
	at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:886)
	at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:414)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	... 52 more
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 13 errors detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:220)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:132)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:300)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
	at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:876)
	... 65 more
```
Any suggestions?

**Comment by lagivan** [comment]
Indeed I'd like to call DITA-OT from Java class so ```dita.bat``` is not applicable. You've probably meant Ant's ```Project``` class. I've tried it as well following [this example](http://stackoverflow.com/questions/6733684/run-ant-from-java) with the code:
```
File buildFile = new File(System.getProperty("ant.home") + "/build.xml");
Project p = new Project();
p.setUserProperty("ant.file", buildFile.getAbsolutePath());
p.init();
ProjectHelper helper = ProjectHelper.getProjectHelper();
p.addReference("ant.projectHelper", helper);
helper.parse(p, buildFile);
p.setProperty("transtype", "pdf");
p.setProperty("args.input", "c:\\Programs\\DITA-OT\\samples\\taskbook\\installing.dita");
p.executeTarget(p.getDefaultTarget());
```
It now complains about DITA DTDs that it cannot find:
```
Caused by: org.dita.dost.exception.DITAOTException: Failed to transform c:\Programs\DITA-OT\temp\temp20150120184645423\installing.dita: java.io.FileNotFoundException: c:\Programs\base\dtd\highlightDomain.ent (The system cannot find the path specified)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:190)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:147)
	at org.dita.dost.module.TopicFragmentModule.execute(TopicFragmentModule.java:49)
	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
	... 51 more
Caused by: javax.xml.transform.TransformerException: java.io.FileNotFoundException: c:\Programs\base\dtd\highlightDomain.ent (The system cannot find the path specified)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:505)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:186)
	... 55 more
Caused by: java.io.FileNotFoundException: c:\Programs\base\dtd\highlightDomain.ent (The system cannot find the path specified)
```
Perhaps I'm missing some configuration to help it find the DTDs. Could you please suggest anything on this?

**Comment by lagivan** [comment]
P.S. The initial issue was caused by the incorrect Saxon version. I've set up a maven project and have used a Saxon lib from maven repository. After I've switched to the original set of libraries from ```DITA-OT/lib```, the initial error has changed to:
```
Error: Failed to run pipeline: Failed to transform c:\Temp\dita\temp\installing.dita: java.io.FileNotFoundException: c:\Temp\dtd\topic.dtd (The system cannot find the path specified)
```
So it's identical to the one that I got using Ant's ```Project``` API.

**Comment by jelovirt** [comment]
You have to pass the absolute system path to DITA-OT installation directory as `dita.dir` property.

Also, note that depending on DITA-OT version, Xalan-J may not be supported and the XSLTC version of Xalan hasn't worked for a long time.

**Comment by jelovirt** [comment]
@infotexture This is basically a documentation issue, we currently don't have a topic describing how DITA-OT could/should be embedded into code running inside/outside JVM.

**Comment by lagivan** [comment]
I've already tried setting ```dita.dir```. It only changes the error message to the following:
```
Caused by: org.dita.dost.exception.DITAOTException: Failed to transform c:\Programs\DITA-OT\temp\temp20150120190124865\installing.dita: java.io.FileNotFoundException: c:\Programs\DITA-OT\dtd\topic.dtd (The system cannot find the file specified)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:190)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:147)
	at org.dita.dost.module.TopicFragmentModule.execute(TopicFragmentModule.java:49)
	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
	... 51 more
Caused by: javax.xml.transform.TransformerException: java.io.FileNotFoundException: c:\Programs\DITA-OT\dtd\topic.dtd (The system cannot find the file specified)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:505)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:186)
	... 55 more
Caused by: java.io.FileNotFoundException: c:\Programs\DITA-OT\dtd\topic.dtd (The system cannot find the file specified)
```
BTW the location of the DTDs has changed from DITA-OT 1.8 to 2.0. It may be related somehow. 
For 1.8 it is: ```%DITA_DIR%\dtd\technicalContent\dtd\topic.dtd```
For 2.0 it is: ```%DITA_DIR%\plugins\org.oasis-open.dita.v1_2\dtd\technicalContent\dtd\topic.dtd```
Still even for DITA-OT 1.8 ```topic.dtd``` location differs from what Java expects.

**Comment by jelovirt** [comment]
Do you have all the dependencies in classpath, especially xml-resolver.jar?

**Comment by lagivan** [comment]
Yes, I've added all libraries from ```%DITA_DIR%\lib``` to the classpath.

**Comment by drmacro** [comment]
In the past when I tried to run the OT from Java I was never able to get Ant to work properly through the loader class. I ended up just using System.exec(), which allowed me to completely control the execution environment from my Java code. I doubt that anything on the Ant side has changed sufficiently to change my original experience.

**Comment by lagivan** [comment]
@drmacro thanks for the input. I can say that I successfully used ```CommandLineInvoker``` to run DITA-OT 1.8 from Java but it's been removed recently and besides it does not allow setting a custom XSL:FO formatter (as it requires Ant parameter ```pdf.formatter```).

**Comment by jelovirt** [comment]
`CommandLineInvoker` created a new JVM to run Ant in, using ant command line tools. Thus, you can still use the same approach by just calling `System.exe()` on `ant.bat`.

**Comment by eerohele** [comment]
@lagivan: I don't know why this needs to be done exactly, but try adding `$DITA_HOME/lib/ant-apache-resolver.jar` into your CLASSPATH.

I gave it a go with the code snippet you provided and had the same error, so I first [enabled Ant logging](http://www.ibm.com/developerworks/websphere/library/techarticles/0502_gawor/0502_gawor.html#sec2b) by adding this:

```java
import org.apache.tools.ant.DefaultLogger;

...

DefaultLogger consoleLogger = new DefaultLogger();
consoleLogger.setErrorPrintStream(System.err);
consoleLogger.setOutputPrintStream(System.out);
consoleLogger.setMessageOutputLevel(Project.MSG_INFO);
p.addBuildListener(consoleLogger);
```

In the Ant logs, it said `Warning: XML resolver not found; external catalogs will be ignored`, but adding `$DITA_HOME/lib/ant-apache-resolver.jar` into the CLASSPATH, it works for me, at least.

**Comment by lagivan** [comment]
Problem solved! The root cause was really stupid and it could be easily seen in the stacktrace shown above - there was Xalan library on the classpath and its transformer was used instead of Saxon. So there are two ways to fix my issue:
1. Removing Xalan library from the classpath.
2. Adding JVM argument:
```
-Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl
```

**Comment by lagivan** [comment]
Finally there are several ways to implement Java call to DITA-OT:
* Using Ant ```Project``` (almost the same as above):
```
File buildFile = new File("build.xml");
Project p = new Project();
p.setUserProperty("ant.file", buildFile.getAbsolutePath());
p.init();
ProjectHelper helper = ProjectHelper.getProjectHelper();
p.addReference("ant.projectHelper", helper);
helper.parse(p, buildFile);
p.setProperty("transtype", "pdf");
p.setProperty("args.input", "c:\\Programs\\DITA-OT\\samples\\taskbook\\installing.dita");
p.executeTarget(p.getDefaultTarget());
```
* Using Ant ```Launcher```:
```
Launcher.main(new String[] { "-Dargs.input=c:\\Programs\\DITA-OT\\samples\\taskbook\\installing.dita", "-Dtranstype=pdf" });
```
* Using Ant ```Launcher``` in combination with ```org.dita.dost.invoker.Main```:
```
Launcher.main(new String[] { "-i", "c:\\Programs\\DITA-OT\\samples\\taskbook\\installing.dita", "-f", "pdf", "-main", "org.dita.dost.invoker.Main" });
```

Additional requirements:
1. ```%DITA_DIR%\lib``` libraries should be in the classpath.
2. The working directory of Java must be %DITA_DIR%! So far I could not find a workaround when a different working directory is used. Specifying ```dita.dir``` argument does not help with it. When working directory cannot be changed, the only solution seems to be ```Runtime.exec()```.

**Comment by lagivan** [comment]
@jelovirt You suggested setting ```dita.dir``` above. However, it did not help in any of three scenarios above. May it be a bug? I believe we should not be tied to a working directory so proper handling of ```dita.dir``` argument by DITA-OT would be great.

**Comment by jelovirt** [comment]
:+1:
