### ISSUE TITLE
"fop.xconf" no longer exists in DITA OT 2.0.1 distribution.

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1855]
I downloaded "DITA-OT2.1.0-M1_standard_bin.zip"

The folder:

   DITA-OT2.1.0-M1\plugins\org.dita.pdf2\fop

only contains license, notice and readme files.

			C:\Users\radu_coravu\Desktop\DOT2.0.1\DITA-OT2.1.0-M1\plugins\org.dita.pdf2\fop\conf\fop.xconf (The system cannot find the path specified)
				at java.io.FileInputStream.open(Native Method)
				at java.io.FileInputStream.<init>(Unknown Source)
				at java.io.FileInputStream.<init>(Unknown Source)
				at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
				at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
				at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:1036)
				at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
				at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
				at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:150)
				at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
				at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
				at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
				at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
				at org.apache.avalon.framework.configuration.DefaultConfigurationBuilder.buildFromFile(DefaultConfigurationBuilder.java:186)
				at org.apache.fop.apps.FopFactoryConfigurator.setUserConfig(FopFactoryConfigurator.java:337)
				at org.apache.fop.apps.FopFactory.setUserConfig(FopFactory.java:703)

**Comment by robander** [comment]
I built 2.1-M1 and 2.0.1 off of the same clone (different branches) - but 2.0.1 has a lot of JAR files in that directory along with license / notice / readme. @jelovirt do you think the build process has changed for the 2.1 copy? Don't think I changed any environment settings between builds.

**Comment by jelovirt** [comment]
Just investigating. We could actually not stick the FOP dependency JARs into our Git, but rather get they with Ivy.

**Comment by jelovirt** [comment]
Yup, it's excluded https://github.com/dita-ot/dita-ot/blob/develop/build.xml#L213 but only partially. Per http://www.dita-ot.org/2.0/readme/distribution_packages.html the standard package should not contain FOP. The build would need to be fixed to skip `fop` directory completely.

**Comment by robander** [comment]
Oh of course, I didn't even realize this was for the standard dist. Everything is there in the client package (which is what I checked for 2.0.1).

**Comment by raducoravu** [comment]
In my opinion if the fop.xconf is different than the one coming by default with Apache FOP (if it has DITA OT-specific related changes) it should also get included in the standard dist.

**Comment by jelovirt** [comment]
The standard package should not have FOP bundled at all. It's a build bug that the license files get included and the whole `plugins/org.dita.pdf2/fop` directory should be omitted.

**Comment by robander** [comment]
Marking this closed as obsolete - we no longer ship a standard package, so any files that were missing from that (but present in the full package) are no longer an issue.
