### ISSUE TITLE
1.8.5 - XHTML build causes FileNotFoundException trying to find nonexistent export.xml

### ISSUE THREAD

**Issue by datlan** [dita-ot/dita-ot#1881]
We have glossary entries that are referenced by conkeyrefs.  For each one we have, we get an error when generating xhtml:

[filter] java.io.FileNotFoundException: d:\temp\export.xml (The system cannot find the file specified)

I'm not very familiar with the DITA-OT code but I did see that the error is occurring in org.dita.dost.util.DelayConrefUtils.checkExport() when it is trying to open export.xml, which doesn't exist.  It appears that export.xml doesn't exist because we aren't using the eclipsehelp transtype.  If we were, I think that export.xml would have been created on line 985 of org.dita.dost.module.GenMapAndTopicListModule().  Should DelayConrefUtils.checkExport not be called if eclipsehelp is not being generated?

Glossary entry:

<glossentry conkeyref="GlossEntTransactionRequestBroker" id="GlossGrpT_TransactionRequestBroker">
  <glossterm />
</glossentry>

Another file has the key definition:

<topicgroup>
  <topicref href="Glossary/GlossaryT/g_GlossEntTransactionRequestBroker.xml#GlossEntTransactionRequestBroker" keys="GlossEntTransactionRequestBroker" />
</topicgroup>

And finally, there is a file with the content:

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glossentry PUBLIC "-//OASIS//DTD DITA Glossary//EN" "glossary.dtd">
<glossentry id="GlossEntTransactionRequestBroker">
  <glossterm>TransactionRequestBroker</glossterm>
  <glossdef>(TRB) <shortdesc>Session Manager.</shortdesc> TRB....</glossdef>
   ...
</glossentry>

Full error:
 [filter] Processing D:\DITASVN\Glossary\GlossaryT\g_GlossGrpT.xml
   [filter] java.io.FileNotFoundException: d:\temp\export.xml (The system cannot find the file specified)
   [filter] 	at java.io.FileInputStream.open(Native Method)
   [filter] 	at java.io.FileInputStream.<init>(Unknown Source)
   [filter] 	at org.dita.dost.util.DelayConrefUtils.checkExport(DelayConrefUtils.java:149)
   [filter] 	at org.dita.dost.writer.DitaWriter.processAttributes(DitaWriter.java:552)
   [filter] 	at org.dita.dost.writer.DitaWriter.startElement(DitaWriter.java:941)
   [filter] 	at org.dita.dost.writer.ValidationFilter.startElement(ValidationFilter.java:80)
   [filter] 	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:105)
   [filter] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
   [filter] 	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
   [filter] 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
   [filter] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
   [filter] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
   [filter] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
   [filter] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
   [filter] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
   [filter] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
   [filter] 	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
   [filter] 	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
   [filter] 	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
   [filter] 	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
   [filter] 	at net.sf.saxon.event.Sender.send(Sender.java:193)
   [filter] 	at net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:30)
   [filter] 	at org.dita.dost.writer.DitaWriter.write(DitaWriter.java:1036)
   [filter] 	at org.dita.dost.module.DebugAndFilterModule.execute(DebugAndFilterModule.java:303)
   [filter] 	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:64)
   [filter] 	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:140)
   [filter] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
   [filter] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [filter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   [filter] 	at java.lang.reflect.Method.invoke(Unknown Source)
   [filter] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
   [filter] 	at org.apache.tools.ant.Task.perform(Task.java:348)
   [filter] 	at org.apache.tools.ant.Target.execute(Target.java:392)
   [filter] 	at org.apache.tools.ant.Target.performTasks(Target.java:413)
   [filter] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
   [filter] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
   [filter] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
   [filter] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
   [filter] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
   [filter] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
   [filter] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [filter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   [filter] 	at java.lang.reflect.Method.invoke(Unknown Source)
   [filter] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
   [filter] 	at org.apache.tools.ant.Task.perform(Task.java:348)
   [filter] 	at org.apache.tools.ant.Target.execute(Target.java:392)
   [filter] 	at org.apache.tools.ant.Target.performTasks(Target.java:413)
   [filter] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
   [filter] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
   [filter] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
   [filter] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
   [filter] 	at org.apache.tools.ant.Main.runBuild(Main.java:811)
   [filter] 	at org.apache.tools.ant.Main.startAnt(Main.java:217)
   [filter] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
   [filter] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by datlan** [comment]
Pull request for this created: https://github.com/dita-ot/dita-ot/pull/1882
