### ISSUE TITLE
Cryptic error when XHTML outout generate copy outer param set to not allowed value

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1935]
If I process DITA OT XHTML using DITA OT 2.x and the copy outer parameter set to: 

```
 -Dgenerate.copy.outer=2
```

I obtain a very cryptic error at some point like:

```
            BUILD FAILED
            C:\wade\DITA-OT\build.xml:41: The following error occurred while executing this line:
            C:\wade\DITA-OT\plugins\org.dita.base\build_preprocess.xml:78: Failed to run pipeline: null
                at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:199)
                at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
                at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                at org.apache.tools.ant.Task.perform(Task.java:348)
                at org.apache.tools.ant.Target.execute(Target.java:435)
                at org.apache.tools.ant.Target.performTasks(Target.java:456)
                at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
                at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
                at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
                at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
                at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
                at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
                at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                at org.apache.tools.ant.Task.perform(Task.java:348)
                at org.apache.tools.ant.Target.execute(Target.java:435)
                at org.apache.tools.ant.Target.performTasks(Target.java:456)
                at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
                at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
                at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
                at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
                at org.apache.tools.ant.Main.runBuild(Main.java:851)
                at org.apache.tools.ant.Main.startAnt(Main.java:235)
                at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
                at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
            Caused by: org.dita.dost.exception.DITAOTException
                at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:248)
                at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
                at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
                ... 29 more
            Caused by: java.lang.IllegalArgumentException
                at org.dita.dost.util.Job$Generate.get(Job.java:802)
                at org.dita.dost.util.Job.setGeneratecopyouter(Job.java:848)
                at org.dita.dost.module.GenMapAndTopicListModule.parseInputParameters(GenMapAndTopicListModule.java:333)
                at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:232)
                ... 31 more
```
with DITA OT 3.x I obtain a similar failure:

      \dita-ot-3x-plugin-master\dita-   ot-3.x\build.xml:45: The following error occurred while executing this line:
       dita-ot-3x-plugin-master\dita-ot-3.x\plugins\org.dita.base\build_preprocess2.xml:71: java.lang.IllegalArgumentException
     at org.dita.dost.util.Job$Generate.get(Job.java:856)
     at org.dita.dost.util.Job.setGeneratecopyouter(Job.java:902)
     at     org.dita.dost.module.reader.AbstractReaderModule.parseInputParameters(AbstractReaderModule.java:230)
     at org.dita.dost.module.reader.MapReaderModule.execute(MapReaderModule.java:46)
     at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)
     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)

**Comment by jelovirt** [comment]
Value `2` is no longer supported. Need to add validation with a better error message.
