### ISSUE TITLE
Cannot publish remote HTTP DITA Map to XHTML [DOT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2003]
I'm publishing a DITA Map from a webdav HTTP server without authentication.
I have images referenced in my topics, at some point the publishing breaks with this error:
```shell
BUILD FAILED
D:\projects\eXml\frameworks\dita\DITA-OT2.x\build.xml:41: The following error occurred while executing this line:
D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.xhtml\build_general.xml:112: java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(Unknown Source)
	at org.dita.dost.writer.ImageMetadataFilter.getImageFile(ImageMetadataFilter.java:172)
	at org.dita.dost.writer.ImageMetadataFilter.startElement(ImageMetadataFilter.java:84)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(RelaxNGDefaultsComponent.java:635)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:260)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1655)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:150)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
	at net.sf.saxon.event.Sender.send(Sender.java:146)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:244)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:204)
	at org.dita.dost.writer.AbstractXMLFilter.write(AbstractXMLFilter.java:32)
	at org.dita.dost.writer.ImageMetadataFilter.write(ImageMetadataFilter.java:73)
	at org.dita.dost.module.ImageMetadataModule.execute(ImageMetadataModule.java:46)
	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
```

**Comment by raducoravu** [comment]
Great, I confirm that this is fixed now.
I'm considering testing a larger example, publishing our entire user's manual directly from GitHub:
https://raw.githubusercontent.com/oxygenxml/userguide/master/DITA/UserManual.ditamap
If I find other issues I will report them.
