### ISSUE TITLE
Relative "dita.temp.dir" makes PDF processing fail

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2038]
It happens with both DOT 1.8 and 2.x.
So if the temporary directory is specified in the command line like:

```
  -Ddita.temp.dir=temp/pdf
```

at some point the indexer fails:

```
   D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2\build.xml:292: java.io.FileNotFoundException: temp\pdf\stage1.xml (The system cannot find the path specified)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at com.idiominc.ws.opentopic.fo.index2.IndexPreprocessorTask.execute(IndexPreprocessorTask.java:137)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:435)
at org.apache.tools.ant.Target.performTasks(Target.java:456)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
```

I think that in such cases it should be explicitly considered relative to the basedir.

**Comment by raducoravu** [comment]
It all started with a discussion here:

http://www.oxygenxml.com/forum/post35711.html#p35711

**Comment by jelovirt** [comment]
Not sure if I want this to be implemented. The problem is that `dita.temp.dir` is an "internal" property and it must be absolute (otherwise we'd have to resolved it in context that doesn't have information what is a suitable base path). But, on the other hand there is not way to define the temporary directory in other way.

My vote here is :-1: and just add support for relative temporary path in `dita` command. Ant should be considered an advanced API and we shouldn't add convenience method/properties there.

**Comment by raducoravu** [comment]
We should probably have had two properties, one which could be set externally and could have supported relative paths and an absolute internal one used everywhere in the build files.
Anyway, does not seem to be a common problem.

**Comment by raducoravu** [comment]
Or at least add a check for the dita.temp.dir in the build files and if it is given as relative, break everything with a meaningfull error.
