### ISSUE TITLE
Topicmerge process runs out of memory (DITA OT v 2.2)

### ISSUE THREAD

**Issue by snijderr** [dita-ot/dita-ot#2175]
I'm developing PDF2 stylesheets for a customer of ours and hit the following issue.

A publication of around 5000 objects which includes cross-references towards objects in a separate data set of around 18000 objects I hit an out of memory error message in the topicmerge process.

If I exclude the data set of around 18000 objects (so the xref statements do not resolve) the process runs fine.

I have already extended the memory on the server to 64GB of RAM, however when monitoring the process in the task manager I do see that it crashes when it has around 27,7GB or memory in use.

Upon suggestion of Eero, I have switched the generate-debug-attributes option in the lib/configuration.properties file from "true" to "false". This reduce the memory to 13,5 GB however the process still crashes.

Below the error stack which is raised each time:

-- start of snippet --

BUILD FAILED
W:\InfoShare\App\Utilities\DITA-OT\LR\build.xml:41: The following error occurred while executing this line:
W:\InfoShare\App\Utilities\DITA-OT\LR\plugins\org.dita.pdf2\build.xml:134: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:2271)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.write(BufferedWriter.java:230)
	at java.io.Writer.write(Writer.java:157)
	at net.sf.saxon.event.XMLEmitter.writeCharSequence(XMLEmitter.java:621)
	at net.sf.saxon.event.XMLEmitter.writeEscape(XMLEmitter.java:714)
	at net.sf.saxon.event.XMLEmitter.writeAttribute(XMLEmitter.java:473)
	at net.sf.saxon.event.XMLEmitter.attribute(XMLEmitter.java:394)
	at net.sf.saxon.event.ProxyReceiver.attribute(ProxyReceiver.java:154)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:366)
	at org.dita.dost.reader.MergeTopicParser.startElement(MergeTopicParser.java:231)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.dita.dost.reader.MergeTopicParser.parse(MergeTopicParser.java:190)
	at org.dita.dost.reader.MergeMapParser.endDocument(MergeMapParser.java:253)
	at org.apache.xerces.parsers.AbstractSAXParser.endDocument(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl.endEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.endEntity(Unknown Source)

-- end of snippet --

Any idea on how to overcome this issue? Is there any memory switch which I can use apart from the -Xmx which I'm already using.
Can I get the topicmerge task setup so it can use more memory or can I somehow reduce the required memory in an easy way?

Any inside you can provide is highly appreciated.

Unfortunately, I'm not able to share the datasets as the customer doesn't allow this.

Kind Regards,

Raf

Raf Snijders

**Comment by jelovirt** [comment]
Which DITA-OT version?

**Comment by eerohele** [comment]
The error message is different, but I wonder whether https://saxonica.plan.io/issues/2271 is related...?

From that issue:

>As reported, I did look at the possibility of supported larger documents beyond the 2G limit. With strings and arrays in Java limited to 32-bit int addressing, it's not at all easy. The limits for a LinkedTree would probably be rather higher than for the TinyTree, which tries to reduce the number of Java objects and therefore ends up with objects whose size appriximates to the document size. It might be worth seeing how far you get with the Linked Tree: the actual amount of memory used will be higher, but I don't think you'll hit the same limits.

**Comment by eerohele** [comment]
@snijderr: Which Java version are you using? I found this bug report:

https://bugs.openjdk.java.net/browse/JDK-8136527

The [last comment](https://bugs.openjdk.java.net/browse/JDK-8136527) in that bug report would suggest that this is a bug that has been fixed in newer JDK versions.

I tried the test case attached to that ticket and using JDK 8u65 indeed seemed to make a difference.

**Comment by snijderr** [comment]
in response to the DITA-OT version number question,
The DITA-OT version I used is 2.2.0
But I also experience the same behaviour with DITA-OT 1.7.5.

I'll retry later tonight the process using the JDK8u65 as currently we are using JDK7u21.

Keep you posted.

Many thanks for the comments and investigations.
Kind Regards,

Raf

**Comment by snijderr** [comment]
Hi Eero,
Hi Jarno,

The proposed fix of Eero did work. Upgrading the java development environment towards JDK8u60 made the publishing process to continue and work as expected.

I'll close the issue for now as it seems to be caused by JDK and not the DITA-OT.

Thanks,

Raf

**Comment by jelovirt** [comment]
While upgrading Java proved to be a working workaround, topicmerge still consumes a lot of memory. This is because the output of merge is:

* map
* topics

in that order. To update the generated IDs into the map, the process cannot be streaming without buffers. I had a feature branch that changed the output so that the merged output was

* topics
* map

And only DOM document of the map is kept in memory, all topic content is directly flushed to final output stream. I think I'll land this change for 3.0, since it breaks backwards compatibility. The change is small and I'm actually pretty sure no one relies on that order, but still.
