### ISSUE TITLE
copy-html task fails for 2.2.1

### ISSUE THREAD

**Issue by tyrin** [dita-ot/dita-ot#2178]
Upgrading from 1.8.4 to 2.2.1. I get the following stack trace:

```
copy-html:
BUILD FAILED
/Users/tavery/clone/documentation/DITA/build/dw_infocenter.xml:156: The following error occurred while executing this line:
/Users/tavery/clone/documentation/DITA/build/dw_infocenter.xml:120: The following error occurred while executing this line:
/Users/tavery/clone/documentation/DITA/build.xml:41: The following error occurred while executing this line:
/Users/tavery/clone/documentation/DITA/plugins/org.dita.base/build_preprocess.xml:441: java.lang.IllegalArgumentException: URI has a query component
    at java.io.File.<init>(File.java:427)
    at org.dita.dost.util.JobSourceSet.getResults(JobSourceSet.java:53)
    at org.dita.dost.util.JobSourceSet.isFilesystemOnly(JobSourceSet.java:89)
    at org.apache.tools.ant.taskdefs.Copy.execute(Copy.java:513)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

The build doesn't fail is if it's run against a ditamap with a single file in it (probably because the copy task isn't called?)

  <b>&lt;!-- The 2.2.1 dita-ot target --&gt;</b>
  &lt;target name=&quot;copy-html&quot; depends=&quot;&quot; unless=&quot;preprocess.copy-html.skip&quot; description=&quot;Copy html files&quot;&gt;
    &lt;copy todir=&quot;${output.dir}&quot; failonerror=&quot;false&quot;&gt;
      &lt;dita-fileset format=&quot;html&quot;/&gt;
    &lt;/copy&gt;
  &lt;/target&gt;
  <b>&lt;!-- The 1.8.4 dita-ot target &gt;</b>
  &lt;target name=&quot;copy-html&quot; depends=&quot;copy-html-check&quot; unless=&quot;preprocess.copy-html.skip&quot; description=&quot;Copy html files&quot;&gt;
    &lt;copy todir=&quot;${output.dir}&quot;&gt;
      &lt;fileset dir=&quot;${user.input.dir}&quot; includesfile=&quot;${dita.temp.dir}/${htmlfile}&quot;/&gt;
    &lt;/copy&gt;
  &lt;/target&gt;

  &lt;target name=&quot;copy-html-check&quot;&gt;
    &lt;condition property=&quot;preprocess.copy-html.skip&quot;&gt;
      &lt;or&gt;
        &lt;isset property=&quot;preprocess.copy-files.skip&quot;/&gt;
        &lt;length file=&quot;${dita.temp.dir}/${htmlfile}&quot; length=&quot;0&quot;/&gt;
      &lt;/or&gt;
    &lt;/condition&gt;
  &lt;/target&gt;

If you want to know what it's copying to, here's the log output for copy-image, which works just fine: 

```
copy-image:
File file:/Users/tavery/clone/documentation/DITA/ditaval/img/images/New2.gif not found
     [copy] Copying 111 files to /Users/tavery/clone/documentation/DITA/target/info/com.demandware.docSG.en
```

The folder it's copying to has periods in the name, which is the only thing I thought might be tripping up the copy task, though ant has no problem with that. It has to have periods in the name because it's being used as part of a webapp.
## What happens with the old target

I tried replacing the new target with the old one and it works fine for small amounts of content, but for my full help system it gives me a java heap space error, which I don't get with the 1.8.4 version. 
The stack trace for that is:

```
BUILD FAILED
/Users/tavery/clone/documentation/DITA/build/dw_infocenter.xml:55: The following error occurred while executing this line:
/Users/tavery/clone/documentation/DITA/build/dw_infocenter.xml:120: The following error occurred while executing this line:
/Users/tavery/clone/documentation/DITA/build.xml:41: The following error occurred while executing this line:
/Users/tavery/clone/documentation/DITA/plugins/org.dita.base/build_preprocess.xml:358: java.lang.OutOfMemoryError: Java heap space
    at org.apache.xerces.xni.XMLString.toString(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanAttribute(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
    at net.sf.saxon.event.Sender.send(Sender.java:193)
    at net.sf.saxon.event.Sender.send(Sender.java:50)
    at net.sf.saxon.Controller.transform(Controller.java:1611)
    at org.dita.dost.module.XsltModule.execute(XsltModule.java:121)
    at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:78)
    at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:178)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
## What to do

I can try increasing the java heap space, but I'm wondering why the new target doesn't work at all - possibly an issue with the encoding of the string used for copying? For the old target, maybe a memory leak somewhere?
I can't upgrade without figuring out what's wrong or replacing the existing copy task with one of my own. I'm hoping there's a simple fix and that I don't have to try and customize the toolkit to upgrade. It just seems very weird to me that it's blowing up on a copy task. I know there's a JIRA in to update the copy-html with a target a lot like copy-image, which I know is working, so I'm going to try that too. 
..Tried it and it behaved like the old target - ran 15 min instead of the usual 4 min and then gave me a java heap space error.

**Comment by jelovirt** [comment]
Unable to reproduce. Please link to a Gist with example files that can't be used to reproduce the issue.

**Comment by tyrin** [comment]
Gist doesn't seem like a good fit, since this is only an issue with a large number of files.

**Comment by jelovirt** [comment]
Could you then create an artificial test case that reproduces this issue, with only few files? I created a test case that I though might reproduce the issue based on the stack trace, but I was unable to break anything.

Does 2.2.1 fail when you run your content using one of the built-in transtypes, without any custom plugins?

**Comment by tyrin** [comment]
I will try to provide files to reproduce the problem later today/tomorrow. We don't use any custom plugins. We do run an ant build with other tasks, but they run after the main build, which just creates eclipse help. It's dying at the preprocess stage, in the base plugin, as far as I can tell. I'm using Java 1.8.

**Comment by tyrin** [comment]
I needed specific directory structures, so I couldn't use gist. Instead, I created a public repo with just the toolkit and a small number of files needed for the test. It's available at: https://github.com/tyrin/DITAOT_Test
You should be able to unzip/clone it locally and run it from the root directory using the following command:
```bash test.sh infotest test```
(This info is also in the repo ReadMe.

**Comment by jelovirt** [comment]
While you code doesn't use custom plugins, the test repo you have uses a lot of custom Ant code, which is basically the same as having custom plugins.

**Comment by tyrin** [comment]
OK. I'll try and simplify it for you. Give me a bit.

**Comment by jelovirt** [comment]
The file `ditaval/en.ditaval` is missing from the repo.

**Comment by tyrin** [comment]
OK. As an update - so in simplifying it I found it's some kind of content bug. In the test.ditamap I had our 'welcome' page and when that is removed, it works fine. when not, you get that ugly copy-html error. 
On the page itself, there's something it doesn't like in all of the links in the following table: 
(maybe that they are relative and point upward?)
```
<table>
        <tgroup cols="2">
          <tbody>
            <row>
              <entry><p><b>Merchants</b></p><p><xref
              href="../ActiveMerchandising/ActiveMerchandising.dita">Active
              merchandising</xref></p><p><xref
              href="../Ordering/Ordering.dita">Ordering</xref></p><p><xref
              href="../Batch/Batchprocessing.dita">Batch
              processing</xref></p><p><xref
              href="../Catalogs/CatalogsCategoriesAndProducts.dita">Catalogs,
              categories, and products</xref></p></entry>

              <entry><p><b>Administrators</b></p><p><xref
              href="../Permissions/Permissions.dita">Permissions, users, and
              roles</xref></p><p><xref
              href="../ImportExport/ImportandExport.dita">Import and
              export</xref></p><p><xref
              href="../ImportExport/ImportExportObjectCheatsheet.dita">Import
              export object cheatsheet</xref></p><p><xref
              href="../DataReplication/DataReplication.dita">Data
              Replication</xref></p></entry>
            </row>

            <row otherprops="transno" translate="no">
              <entry><p><b>Developers</b></p><p otherprops="transno"><xref
              href="../SiteDevelopment/GettingStartedforDevelopers.dita">Getting
              started for developers</xref></p><p otherprops="transno"><xref
              href="../ISML/ISML.dita">ISML</xref></p><p
              otherprops="transno"><xref
              href="../SiteDevelopment/WorkingwithScripts.dita">Script
              programming</xref></p><p otherprops="transno"><xref
              href="../CodingStyles/SiteGenesisConventionsandCodingStandards.dita">Storefront
              coding standards and conventions</xref></p></entry>

              <entry><p><b>Designers</b></p><p><xref
              href="../ImageManagement/ImageManagement.dita">Image
              management</xref></p><p otherprops="transno"><xref
              href="../StorefrontToolkit/StorefrontToolkit.dita">Storefront
              Toolkit</xref></p></entry>
            </row>
          </tbody>
        </tgroup>
      </table> ```
Only removing all of the links gets the error to disappear, so it's doubtful that it's a file issue, but I'm going to check that. 
As a side note, don't bother with the repo til I can update it with files that show the content bug.

**Comment by tyrin** [comment]
Update: this is layered. I got rid of the URI error by removing all empty xrefs and topicrefs.
But I'm still getting the java.lang.OutOfMemoryError: GC overhead limit exceeded error. I don't get this when I build the small test system, but when I build our English system, it dies. This is strange to me, because with the current toolkit we build several languages, where the non-English help contains English as a fallback, without problems or errors. 
So I think the toolkit just has some kind of memory leak. I tried increasing the heap space from 512 to 1024, but it didn't help. Not sure what else to do. But clearly I can't upgrade.

**Comment by tyrin** [comment]
I do have a number of "recoverable errors", which seem to be when there's an xref with a relative link that doesn't need a relative link. I.e., you're in the Search directory and there's an xref path of ../Search/myfile.dita. 
I'll try fixing those and see if somehow the 'recoverable' part is what's blowing out the heap space.

**Comment by sebschmied** [comment]
Hi tyrin, a have a similar issue. Did fixing the recoverable errors help in any way?
