### ISSUE TITLE
chunk="to-content" combined with copy-to="xxx" gives rise to java NullPointerException

### ISSUE THREAD

**Issue by strgaltentf** [dita-ot/dita-ot#2188]
Using the following example map file, a null pointer exception is generated by OpenToolkit v2.2 during metadata processing. The exception didn't occur in v2.1.
<map>
    <title>MyDoc</title>
    <topicmeta><publisher>Acme Inc.</publisher></topicmeta>
    <topichead navtitle="Manual">
        <topicref navtitle="Toolbars" href="toolbars.dita#t_toolbars" copy-to="ToolbarsChunk.dita" chunk="to-content">
            <topicref href="toolbars.dita#t_save"/>
       </topicref>
    </topichead>
</map>
Notes: (i) if either the chunk="to-content" or copy-to attribute is missing, the map is processed ok.
(ii) Also the map must have metadata present for the null pointer exception to appear (though output appears incorrect).
Little bit of investigation makes me suspect the fault is actually earlier than the metadata stage - the file named by the copy-to attribute is missing in any of the lists generated earlier.

[dita_opentoolkit_issue.zip](https://github.com/dita-ot/dita-ot/files/82675/dita_opentoolkit_issue.zip)

**Comment by raducoravu** [comment]
Stack trace for NPE obtained with DITA OT 2.2.1:

            BUILD FAILED
            C:\Users\radu_coravu\Desktop\DOT 2.2\dita-ot-2.2.1\build.xml:41: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DOT 2.2\dita-ot-2.2.1\plugins\org.dita.base\build_preprocess.xml:190: java.lang.NullPointerException
            	at org.dita.dost.module.MoveMetaModule.pushMetadata(MoveMetaModule.java:159)
            	at org.dita.dost.module.MoveMetaModule.execute(MoveMetaModule.java:68)
            	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
            	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
            	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)

**Comment by jelovirt** [comment]
The gen-list module doesn't correctly add `format` information for `ToolbarsChunk.dita`.

**Comment by jelovirt** [comment]
If a copy-to source has chunk="to-content", it will not listed in normal copy-to map, because the processing assumes it will be dealt with in chunk processing. The code is _old_.

**Comment by jelovirt** [comment]
If we add the format information to chunk target in gen-list, it will be processed as a normal topic. It could be added in chunk processing, but that is implemented in XSLT.

**Comment by jelovirt** [comment]
Fixed in #2207 for `develop` branch. The same fix cannot be used here because it changes preprocess step order.
