### ISSUE TITLE
NPE in [keyref] processing (DITA-OT 2.2.2)

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#2246]
Following is the result log file.

```
     [echo] com.antennahouse.i18n_index.2.3 is integrated.

init:
     [echo] com.antennahouse.i18n_index.2.3 is integrated.

check-arg:
    [mkdir] Created dir: D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227

log-arg:
     [echo] *****************************************************************
     [echo] * basedir = D:\DITA-OT\dita-ot-2.2.2
     [echo] * dita.dir = D:\DITA-OT\dita-ot-2.2.2
     [echo] * transtype = pdf5.ml
     [echo] * tempdir = D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227
     [echo] * outputdir = D:\DITA-OT\dita-ot-2.2.2\out
     [echo] * clean.temp = true
     [echo] * DITA-OT version = 2.2.2
     [echo] * XML parser = Xerces
     [echo] * XSLT processor = Saxon
     [echo] * collator = ICU
     [echo] *****************************************************************
     [echo] #Ant properties
     [echo] #Wed Mar 02 16:53:01 GMT+09:00 2016
     [echo] args.grammar.cache=yes
     [echo] args.input=samples/sample_en/sample_en.ditamap
     [echo] args.logdir=D\:\\DITA-OT\\dita-ot-2.2.2\\out
     [echo] args.xml.systemid.set=yes
     [echo] dita.dir=D\:\\DITA-OT\\dita-ot-2.2.2
     [echo] dita.plugin.com.antennahouse.dita.dita13.doctypes.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\com.antennahouse.dita.dita13.doctypes
     [echo] dita.plugin.com.antennahouse.i18n_index.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\com.antennahouse.i18n_index.2.3
     [echo] dita.plugin.com.antennahouse.pdf5.ml.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\com.antennahouse.pdf5.ml
     [echo] dita.plugin.com.antennahouse.samples.form.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\com.antennahouse.samples.form
     [echo] dita.plugin.com.sophos.tocjs.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\com.sophos.tocjs
     [echo] dita.plugin.org.dita.base.dir=D\:\\DITA-OT\\dita-ot-2.2.2
     [echo] dita.plugin.org.dita.docbook.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.docbook
     [echo] dita.plugin.org.dita.eclipsecontent.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.eclipsecontent
     [echo] dita.plugin.org.dita.eclipsehelp.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.eclipsehelp
     [echo] dita.plugin.org.dita.html5.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.html5
     [echo] dita.plugin.org.dita.htmlhelp.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.htmlhelp
     [echo] dita.plugin.org.dita.javahelp.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.javahelp
     [echo] dita.plugin.org.dita.odt.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.odt
     [echo] dita.plugin.org.dita.pdf2.axf.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.pdf2.axf
     [echo] dita.plugin.org.dita.pdf2.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.pdf2
     [echo] dita.plugin.org.dita.pdf2.fop.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.pdf2.fop
     [echo] dita.plugin.org.dita.pdf2.xep.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.pdf2.xep
     [echo] dita.plugin.org.dita.specialization.dita11.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.specialization.dita11
     [echo] dita.plugin.org.dita.specialization.eclipsemap.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.specialization.eclipsemap
     [echo] dita.plugin.org.dita.troff.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.troff
     [echo] dita.plugin.org.dita.wordrtf.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.wordrtf
     [echo] dita.plugin.org.dita.xhtml.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.dita.xhtml
     [echo] dita.plugin.org.oasis-open.dita.v1_2.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.oasis-open.dita.v1_2
     [echo] dita.plugin.org.oasis-open.dita.v1_3.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\plugins\\org.oasis-open.dita.v1_3
     [echo] dita.temp.dir=D\:\\DITA-OT\\dita-ot-2.2.2\\temp\\temp20160302165301227
     [echo] preprocess.copy-html.skip=true
     [echo] preprocess.copy-image.skip=true
     [echo] *****************************************************************

build-init:

preprocess.init:
     [echo] *****************************************************************
     [echo] * input = samples/sample_en/sample_en.ditamap
     [echo] *****************************************************************

gen-list:
 [gen-list] Using Xerces grammar pool for DTD and schema caching.
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/sample_en.ditamap
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/dita_sample.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/c_preface.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_weirdtitle1.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_weirdtitle2.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/c_test_introduction.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_abstract.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_xref.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_note.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_bodyelements.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_miscellaneouselements.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_specializationelements.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_typographic.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_programmingelements.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_softwareelements.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_utilityelements.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_fig.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_table.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/r_properties.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/t_logging_in_to_client.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_dita12.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_longdescref.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_longquoteref.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/m_keydef.ditamap
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_sectiondiv.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_reference_to_no_print.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_complecated_index_example.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/r_xslt.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_dir_attribute.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_backmatter.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/glossary_en.ditamap
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_no_print.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/r_tys125f.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XSLT.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XSLFO.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XMLandHTML.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XMLSchema.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_DTD.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_DOM.xml
 [gen-list] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_SAX.xml
 [gen-list] Serializing job specification

debug-filter:
   [filter] Using Xerces grammar pool for DTD and schema caching.
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_programmingelements.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_longdescref.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/glossary_en.ditamap
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/c_preface.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_typographic.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_table.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/dita_sample.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_reference_to_no_print.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/r_tys125f.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_miscellaneouselements.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/sample_en.ditamap
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_weirdtitle1.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_fig.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_specializationelements.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XSLFO.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_xref.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_note.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/r_properties.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XMLandHTML.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_utilityelements.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_DTD.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_DOM.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_complecated_index_example.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XMLSchema.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_dir_attribute.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/m_keydef.ditamap
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_SAX.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/r_xslt.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_abstract.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_dita12.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_no_print.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_bodyelements.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_sectiondiv.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_weirdtitle2.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/gloss_XSLT.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_longquoteref.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/c_test_introduction.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/t_logging_in_to_client.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_backmatter.xml
   [filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/samples/sample_en/topics-en/p_softwareelements.xml
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\outditafiles.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\fullditamapandtopic.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\fullditatopic.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\fullditamap.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\hrefditatopic.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\conref.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\image.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\flagimage.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\html.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\canditopics.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\subjectscheme.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\conreftargets.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\copytosource.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\subtargets.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\resourceonly.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\user.input.file.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\hreftargets.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\conref.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\hrefditatopic.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\fullditatopic.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\fullditamapandtopic.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\conreftargets.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\canditopics.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl
[job-helper] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\.job.xml to D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\resourceonly.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\job-helper.xsl

mapref-check:

mapref:
   [mapref] Transforming into D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227
   [mapref] Loading stylesheet D:\DITA-OT\dita-ot-2.2.2\xsl\preprocess\mapref.xsl
   [mapref] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\topics-en\m_keydef.ditamap
   [mapref] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\topics-en\glossary_en.ditamap
   [mapref] Processing D:\DITA-OT\dita-ot-2.2.2\temp\temp20160302165301227\sample_en.ditamap

branch-filter:
[branch-filter] Processing file:/D:/DITA-OT/dita-ot-2.2.2/temp/temp20160302165301227/sample_en.ditamap

copy-image:

copy-html:

copy-flag-check:

copy-flag:

copy-files:

keyref:
   [keyref] Reading file:/D:/DITA-OT/dita-ot-2.2.2/temp/temp20160302165301227/sample_en.ditamap
   [keyref] Processing file:/D:/DITA-OT/dita-ot-2.2.2/temp/temp20160302165301227/topics-en/p_longquoteref.xml

BUILD FAILED
D:\DITA-OT\dita-ot-2.2.2\build.xml:41: The following error occurred while executing this line:
D:\DITA-OT\dita-ot-2.2.2\plugins\org.dita.base\build_preprocess.xml:270: java.lang.NullPointerException
	at org.dita.dost.writer.KeyrefPaser.processElement(KeyrefPaser.java:374)
	at org.dita.dost.writer.KeyrefPaser.startElement(KeyrefPaser.java:364)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(Unknown Source)
	at org.dita.dost.writer.TopicFragmentFilter.startElement(TopicFragmentFilter.java:62)
	at org.dita.dost.writer.ConkeyrefFilter.startElement(ConkeyrefFilter.java:89)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
	at net.sf.saxon.event.Sender.send(Sender.java:193)
	at net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:30)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:259)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:219)
	at org.dita.dost.module.KeyrefModule.processFile(KeyrefModule.java:234)
	at org.dita.dost.module.KeyrefModule.execute(KeyrefModule.java:93)
	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 4 seconds
```
It seems that p_longquoteref.xml has no validation errors.

I attached used DITA instance.

[sample_en.zip](https://github.com/dita-ot/dita-ot/files/154305/sample_en.zip)

**Comment by eerohele** [comment]
Reproduced.

```diff
diff --git a/src/main/java/org/dita/dost/writer/KeyrefPaser.java b/src/main/java/org/dita/dost/writer/KeyrefPaser.java
index 65186da..1847d04 100644
--- a/src/main/java/org/dita/dost/writer/KeyrefPaser.java
+++ b/src/main/java/org/dita/dost/writer/KeyrefPaser.java
@@ -95,6 +95,7 @@ public final class KeyrefPaser extends AbstractXMLFilter {
         ki.add(new KeyrefInfo(TOPIC_INDEXTERM, ATTRIBUTE_NAME_HREF, false, false));
         ki.add(new KeyrefInfo(TOPIC_INDEX_BASE, ATTRIBUTE_NAME_HREF, false, false));
         ki.add(new KeyrefInfo(TOPIC_INDEXTERMREF, ATTRIBUTE_NAME_HREF, false, false));
+        ki.add(new KeyrefInfo(TOPIC_LONGQUOTEREF, ATTRIBUTE_NAME_HREF, false, false));
         final Map<String, String> objectAttrs = new HashMap<>();
         objectAttrs.put(ATTRIBUTE_NAME_ARCHIVEKEYREFS, ATTRIBUTE_NAME_ARCHIVE);
         objectAttrs.put(ATTRIBUTE_NAME_CLASSIDKEYREF, ATTRIBUTE_NAME_CLASSID);
```

I think.

**Comment by ToshihikoMakita** [comment]
Hi eerohele,

Thank you for your quick fix!
