### ISSUE TITLE
StackOverflow in KeyrefReader [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2337]
Using DITA OT 2.2.4 to publish a DITA project the publishing fails with:

            D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.base\build_preprocess.xml:270: java.lang.StackOverflowError
            	at org.apache.xerces.dom.NamedNodeMapImpl.findNamePoint(Unknown Source)
            	at org.apache.xerces.dom.NamedNodeMapImpl.getNamedItem(Unknown Source)
            	at org.apache.xerces.dom.ElementImpl.getAttribute(Unknown Source)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:255)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:261)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:261)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:261)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:261)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:261)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:261)
            	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:261)

**Comment by raducoravu** [comment]
The sample DITA Map which was created by one of our QA has something like this in it:

       <topicref href="topics/flowers/snowdrop.dita" keys="snowdrop galanthus"
     keyscope="snowdrop galanthus" keyref="snowdrop.snowdrop"/>

**Comment by robander** [comment]
"silly" :+1: :-)

**Comment by robander** [comment]
Tagging as P3 because of the described "silly" nature. Do you have a zip with the full map that can reproduce?

**Comment by raducoravu** [comment]
Uploaded a sample here:
https://www.oxygenxml.com/forum/files/sillyKeyRefKeyScope.zip
