### ISSUE TITLE
Reltable links not properly reflected in output when using key scopes.

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2393]
I'm attaching a sample project here:
https://www.oxygenxml.com/forum/files/reltableKeyScopes.zip

The relathioship table maps a topic to 2 topicrefs, each topicref pointing to the same topic but in a different key scope:

				<reltable>
					<relrow>
						<relcell>
							<topicref keyref="key_ref-common" />
						</relcell>
						<relcell>
							<topicref keyref="keyscope_prod-A.key_topic-reused_prod-A" />
							<topicref keyref="keyscope_prod-B.key_topic-reused_prod-B" />
						</relcell>
					</relrow>
				</reltable>

but in the published output the common.html only contains a link to the "Product A" topic and the link to the "Product B" topic is missing.

**Comment by raducoravu** [comment]
We've recently had an end user wanting to add reltable-based links between topics in different key scopes. So it would be quite nice if this worked.

**Comment by raducoravu** [comment]
This is probably related to #2538

**Comment by raducoravu** [comment]
Somebody else on the DITA Users list has problems with key scopes and reltables.
Samples are attached here:
https://dita-users.groups.io/g/main/message/45704
and his opinion on the problem here:
https://dita-users.groups.io/g/main/message/45708

**Comment by edLearns** [comment]
Thank you @raducoravu for picking this up!  
This issue is known since at least May 2016. That’s more than four years ago. @jelovirt, @robander and whoever else might be in a position to help with this, I know the time and resources you’re able to put into this are severly limited and I know you’re very likely more than fully booked with your day job. But if one of you could please look into the issue, estimate the time it would take to solve this problem (and maybe even put a price tag on it), maybe we could find a way to make this work. I will contact our consultant regarding this issue and see what they can do, maybe they have a solution and are able/willing to help with this.    

Thank you all for the hard work you so far have put in!  

Regards,  
Ed

**Comment by raducoravu** [comment]
Attaching a simplified version of Ed's map, which just a mapref with keyscope, and inside the referenced map a reltable.
[keysAndDitavalsSimplified.zip](https://github.com/dita-ot/dita-ot/files/5090617/keysAndDitavalsSimplified.zip)

The main problem I see is that the stylesheet "plugins/org.dita.base/xsl/preprocess/maprefImpl.xsl" which expands the reltable of the submap inside the main DITA Map does not copy the keyscope context on the generated reltable elements.

I'm also attaching a modified version of the stylesheet which attempts to wrap the "reltable" inside a "tgroup" in case there are keyscope attributes which need to be set as context for the "reltable". The related links seem to appear afterwards but I'm not sure if it's a solid fix:
[maprefImpl.xsl.zip](https://github.com/dita-ot/dita-ot/files/5090643/maprefImpl.xsl.zip)

**Comment by edLearns** [comment]
Good morning @raducoravu and all other DOT-heroes: using DITA-OT 3.5.2 (dita-command), your modified stylesheet and the simplified version of the sample project, I managed to produce functioning links.  
As soon as I added a single ditavalref though, I got an error and no output at all. I’m attaching  
+ the output generated with the modified stylesheet, DOT 3.5.2 and the simplified sample project  
+ the logfile produced after trying to generate output using the modified stylesheet with DOT 3.5.2 and the original sample project (which includes ditavals)  

[20200820_github2393.zip](https://github.com/dita-ot/dita-ot/files/5101522/20200820_github2393.zip)

**Comment by raducoravu** [comment]
The NullPointerException stack trace:

       /Users/..../plugins/org.dita.base/build_preprocess.xml:148: java.lang.NullPointerException
	at org.dita.dost.module.BranchFilterModule.processAttributes(BranchFilterModule.java:603)
	at org.dita.dost.module.BranchFilterModule.splitBranches(BranchFilterModule.java:523)
	at org.dita.dost.module.BranchFilterModule.splitBranches(BranchFilterModule.java:519)
	at org.dita.dost.module.BranchFilterModule.splitBranches(BranchFilterModule.java:525)
	at org.dita.dost.module.BranchFilterModule.splitBranches(BranchFilterModule.java:525)
	at org.dita.dost.module.BranchFilterModule.processMap(BranchFilterModule.java:133)
	at org.dita.dost.module.BranchFilterModule.execute(BranchFilterModule.java:102)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:190)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
            } else {
                buf.insert(0, s);
            }
        });
        return toURI(buf.toString());
    }

}

**Comment by raducoravu** [comment]
Again in mapRefImpl.xsl there is a place where a "keydef" is separately kept to preserve the name of the key assigned to the DITA Map:

            
            <xsl:if test="@keys">
              <keydef class="+ map/topicref mapgroup-d/keydef ditaot-d/keydef " processing-role="resource-only">
                <xsl:apply-templates select="@* except (@class | @processing-role)"/>
                <xsl:apply-templates select="*[contains(@class, ' map/topicmeta ')]"/>
              </keydef>
            </xsl:if>

The @href attribute value I think needs to be made relative to the relative path.

              <keydef class="+ map/topicref mapgroup-d/keydef ditaot-d/keydef " processing-role="resource-only">
                <xsl:apply-templates select="@* except (@class | @processing-role | @href)"/>
                <xsl:if test="@href">
                  <xsl:choose>
                    <xsl:when test="$relative-path != '#none#'">
                      <xsl:value-of select="concat($relative-path, @href)"/>
                    </xsl:when>
                    <xsl:otherwise>
                      <xsl:value-of select="@href"/>
                    </xsl:otherwise>
                  </xsl:choose>
                </xsl:if>
                <xsl:apply-templates select="*[contains(@class, ' map/topicmeta ')]"/>
              </keydef>

**Comment by raducoravu** [comment]
Attaching both fixes (for the reltable and for the invalid reference generating the NPE) in a zip containing the maprefImpl.xsl: [maprefImpl.xsl.zip](https://github.com/dita-ot/dita-ot/files/5102683/maprefImpl.xsl.zip)

@edLearns maybe you can try again when you have the time

**Comment by edLearns** [comment]
Hi @raducoravu,
this is getting better by the hour: I have no errors and get links.  
Another problem shows up though: keyrefs in the reltable which explicitely point to another instance of a topic in a different keyscope (as in `<topicref keyref="keyscope.key"/>`) are rendered as leading to the first instance of that topic. Let’s say I have Topic A in three maps, all of which have some profiling applied. If I now use the navigational key to point to Topic A in map 3, Topic A from map 1 will be linked in the output, instead of Topic A from map 3.

One more thing: I get no output when trying all of this with DITA-OT 3.4.1 (which ist what we’d like to use with our transformation from Oxygen).

Many thanks,  
Ed

**Comment by jelovirt** [comment]
@raducoravu Could we move the discussion to https://github.com/dita-ot/dita-ot/pull/3563?

**Comment by edLearns** [comment]
Hi @raducoravu, I created a new issue:  
https://github.com/dita-ot/dita-ot/issues/3565

**Comment by jelovirt** [comment]
Fixes #2147
