### ISSUE TITLE
java.lang.UnsupportedClassVersionError: org/dita/dost/invoker/Main : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2506]
I switched a build script to `dita-ot-develop`. Now the build fails with an `UnsupportedClassVersionError`, see [https://travis-ci.org/doctales/org.doctales.terminology/builds/168562882](https://travis-ci.org/doctales/org.doctales.terminology/builds/168562882):

```
java.lang.UnsupportedClassVersionError: org/dita/dost/invoker/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
```

**Comment by jelovirt** [comment]
Do you have Java 8 in use?

**Comment by xephon2** [comment]
@jelovirt, could you please add a `<fail>` to the `build.xml`. I know, there is a statement in the `README.md`, but an `UnsupportedClassVersionError` is not very self explaining, I think.

```xml
<fail message="Unsupported Java version: ${ant.java.version}. 
  Make sure that the Java version is 1.5 or greater.">
  <condition>
    <not>
      <or>
        <equals arg1="${ant.java.version}" arg2="1.5"/>
        <equals arg1="${ant.java.version}" arg2="1.6"/>
      </or>
    </not>
  </condition>
</fail>
```

**Comment by jelovirt** [comment]
If we added an error message like that, it would need to be so early in the init process that no DITA-OT class would not have loaded yet.

However, I don't want to litter the code with checks like that, since they would only be used *once* per installation, and only when unsupported Java version is used. Preferably I would just document that error message.

**Comment by xephon2** [comment]
I'll open a docs ticket.
