### ISSUE TITLE
SVG images missing in 2.4.1

### ISSUE THREAD

**Issue by ru-fu** [dita-ot/dita-ot#2548]
When building a PDF with the default PDF transformation in DITA-OT 2.4.1, SVG files are not rendered. The log contains the following error:

      [fop] Dec 15, 2016 1:17:30 PM org.apache.fop.image.loader.batik.PreloaderSVG$Loader getImage
      [fop] WARNING: Batik not in class path
      [fop] java.lang.NoClassDefFoundError: org/w3c/dom/svg/SVGDocument
      [fop]     at java.lang.ClassLoader.defineClass1(Native Method)
      [fop]     at java.lang.ClassLoader.defineClass(Unknown Source)
       ...
      [fop] SEVERE: Image not available. URI: file:/C:/tedtools/dita-ot-2.4.1/docsrc/samples/image/DNV_liability.svg. Reason: org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for file:/C:/tedtools/dita-ot-2.4.1/docsrc/samples/image/DNV_liability.svg (See position 59:-1)
      [fop] org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for file:/C:/tedtools/dita-ot-2.4.1/docsrc/samples/image/DNV_liability.svg

I tested with the supplied sample and just replaced the jpg image with an svg image.

It might be a setup issue of course, but I didn't manage to figure it out. Explicitly setting the class path didn't help. Java version is Java(TM) SE Runtime Environment (build 1.8.0_25-b18). dita.plugin.org.dita.pdf2.fop.dir is set as expected, and all the batik-*.jar files are in the lib subfolder. Google says the error indicates that xml-apis-ext.jar is missing - that file is not there, but this might be outdated information (and adding it doesn't help either).

Seems to be the same issue as mentioned [here](https://beta.groups.yahoo.com/neo/groups/dita-users/conversations/messages/41441).

**Comment by xephon2** [comment]
I'm not familiar with the issue, but please make sure, that the `@format` is set correctly, when using keys here.

```xml
<keydef keys="key" href="image.svg" format="svg"/>
```

**Comment by raducoravu** [comment]
I don't think the Batik libraries are shipped with the DITA OT. So you would probably have to download them separately from:

https://xmlgraphics.apache.org/batik/

and copy them to the DITA OT "lib" folder.

**Comment by ru-fu** [comment]
I'm not using keys. For testing, I simply included the image:
`<image href="../image/carwash.jpg" alt="washing the car" height="171" width="249"/>`
`<image href="../image/DNV_liability.svg" alt="washing the car" height="171" width="249" id="dfgfdgdgf"
    />`
The jpg works, the svg doesn't.

And most of the Batik libraries are included in dita-ot-2.4.1\plugins\org.dita.pdf2.fop\lib
Adding the missing ones doesn't solve the problem.

**Comment by lionelmoi** [comment]
I had the same problem, before FOP 2.1 was added to the DITA-OT 2.4.

I solved by adding this libraries 

    <feature extension="dita.conductor.lib.import" file="libs/avalon-framework-api-4.3.1.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/avalon-framework-impl-4.3.1.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-anim-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-awt-util-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-bridge-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-css-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-dom-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-ext-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-extension-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-gvt-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-parser-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-script-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-svg-dom-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-svggen-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-transcoder-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-util-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/batik-xml-1.8.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/commons-logging-1.0.4.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/fop-2.1.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/xmlgraphics-commons-2.1.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/xercesImpl-2.11.0.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/xml-apis.jar"/>
    <feature extension="dita.conductor.lib.import" file="libs/xml-apis-ext.jar"/>

I don't know if it's the right approach but it solved the issue.

**Comment by ru-fu** [comment]
Thanks! That helped me fix the problem:
- Download the Batik libraries from https://xmlgraphics.apache.org/batik/
- Copy xml-apis-ext-1.3.04.jar from the download to dita-ot-2.4.1\plugins\org.dita.pdf2.fop\lib
- Add the line ` <feature extension="dita.conductor.lib.import" file="lib/xml-apis-ext-1.3.04.jar"/>` to dita-ot-2.4.1\plugins\org.dita.pdf2.fop\plugin.xml
- Run dita --install

However, processing time increases considerably (in my project from about 25 seconds to a bit over 2 minutes).

**Comment by raducoravu** [comment]
I think the problem with the delay might be connected to the fact that your SVG's have DOCTYPE declarations like:

     <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

so when the Apache FOP reads the SVG, it needs to locate the SVG and it downloads it from the web server for each SVG.
You probably need to add additional entries in the DITA OT catalog file to map the "-//W3C//DTD SVG 1.1//EN" to a local SVG DTD.

**Comment by ru-fu** [comment]
Thanks! I *think* I did as you suggested:
`<public publicId="-//W3C//DTD SVG 1.1//EN" uri="dtd/svg11.dtd"/>`

It only saves a few seconds though, unfortunately. :(

**Comment by raducoravu** [comment]
If you can run the processing even with the network disabled, then indeed the DTDs are resolved locally. I would assume that indeed it would take longer to produce the PDF with the SVG images included than it did before when the SVG images were skipped.

**Comment by drmacro** [comment]
If you can, better to remove the DOCTYYPE declarations entirely from your SVGs--the DTD adds no value during the production process and as you've noted only adds to the processing time.

**Comment by raducoravu** [comment]
👍 Same problem recently posted on the DITA Users List:
https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/41625

**Comment by raducoravu** [comment]
Maybe we could bundle the Batik libraries as default libraries for PDF output.

**Comment by AlastairDent** [comment]
I have tried adding just this file <feature extension="dita.conductor.lib.import" file="lib/xml-apis-ext-1.3.04.jar"/> to my plugin.
The SVG images appear, but positioning of some text is incorrect (wildly different, munged up and superimposed over another part of the image).

**Comment by raducoravu** [comment]
That's maybe a problem with the latest Apache FOP 2.1, problem which I reported here:
https://issues.apache.org/jira/browse/FOP-2617

**Comment by raducoravu** [comment]
@jelovirt By the way DITA OT 2.1 already seems to come with the Batik libraries present in the folder "plugins\org.dita.pdf2.fop\lib". But the "org/w3c/dom/svg/SVGDocument" is from a JAR library called "xml-apis-ext.jar" which should also be added to that folder + referenced as an extra JAR in the plugin.xml

**Comment by raducoravu** [comment]
👍
