### ISSUE TITLE
Error: java.lang.IllegalStateException: Duplicate key topic-id-1.dita

### ISSUE THREAD

**Issue by howlger** [dita-ot/dita-ot#2549]
If in a *.ditamap file a *.dita file that contains `<keyword keyref="..."/>` is referenced more than twice then [dita-ot-2.4.1](https://github.com/dita-ot/dita-ot/releases/download/2.4.1/dita-ot-2.4.1.zip) fails with following error: **`Error: java.lang.IllegalStateException: Duplicate key`** _topic-id_**`-1.dita`**

## Steps to reproduce:
1. Create following files:

_map.ditamap_:
```
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "dtd/map.dtd">
<map title="Error: java.lang.IllegalStateException: Duplicate key topic-id-1.dita">
   <topicref href="topic.dita"/>
   <topicref href="topic.dita"/>
   <topicref href="topic.dita"/>
   <keydef keys="VAR">
      <topicmeta><keywords><keyword>value</keyword></keywords></topicmeta>
   </keydef>
</map>
```
_topic.dita_:
```
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "dtd/concept.dtd">
<concept id="topic-id">
   <title>Topic</title>
   <shortdesc>Lorem ipsum</shortdesc>
   <conbody><p><keyword keyref="VAR"/></p></conbody>
</concept>
```
2. Run dita-ot: `dita -f html5 -i map.ditamap`

### Results:
- **Actual**: no output is generated; processing fails with following error: `Error: java.lang.IllegalStateException: Duplicate key topic-1.dita`
- **Expected**: in out/ at least the files _index.html_ and _topic.html_ should be created (see #2363 if the files _topic-1.html_ and  _topic-2.html_ should also be created)

**Comment by lionelmoi** [comment]
I encountered the same issue with 2.4.1

**Comment by DaveDITA** [comment]
I'm getting the same error in 2.4.5 with conkeyref or keyref in files referenced more than once in a map structure. The keyref stage of the transformation starts and quickly exits with the above error on the first -1.xml file containing either of those types of keyrefs.

**Comment by raducoravu** [comment]
I also hit this problem in one of our end user's projects. The problem could not be reproduced with DITA OT 2.3.3

            D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.base\build_preprocess.xml:270: java.lang.IllegalStateException: Duplicate key AAM/common/source/heading_Product-2.dita
            	at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source)
            	at java.util.HashMap.merge(Unknown Source)
            	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
            	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
            	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
            	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
            	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
            	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
            	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
            	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
            	at java.util.stream.ReferencePipeline.collect(Unknown Source)
            	at org.dita.dost.module.KeyrefModule.adjustResourceRenames(KeyrefModule.java:162)
            	at org.dita.dost.module.KeyrefModule.collectProcessingTopics(KeyrefModule.java:150)
            	at org.dita.dost.module.KeyrefModule.execute(KeyrefModule.java:99)
            	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:70)
            	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:222)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by raducoravu** [comment]
Also these lambda expression rewrites like the ones in "org.dita.dost.module.KeyrefModule.adjustResourceRenames(List<ResolveTask>)" make the code very hard to decifer.

**Comment by raducoravu** [comment]
The code in the adjustResourceRenames could be re-written to accept duplicates in the created map like:

            final Map<URI, URI> rewrites = 
            		tasks.stream().filter(t -> t.out != null).collect(toMap(
                            t -> t.in.uri,
                            t -> t.out.uri,
                            (v1, v2) -> {
                                return v1;
                            }
                    ));

**Comment by jelovirt** [comment]
The fix proposed by @raducoravu would work around the null pointer, but would not fix the underlying issue. The duplicates need to be detected earlier on.

**Comment by raducoravu** [comment]
I confirm that the fix works also on my client's samples.
