### ISSUE TITLE
"uri and file may not be null" when having a reference to a Markdown file in DITA Map + preprocessing plugin installed

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2564]
Having the "com.elovirta.dita.markdown_1.1.0" plugin installed in DITA OT 2.4, with a small DITA Map like this:

            <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
            <map>
              <topicref format="markdown" href="markdowntest.md"/>
            </map>

and a markdown file "markdowntest.md" like this:

            # Title
            
            Para

converting to XHTML fails with this exception:

            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-2.4.1\build.xml:45: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-2.4.1\plugins\org.dita.base\build_preprocess.xml:47: Failed to run pipeline: uri and file may not be null
            	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:228)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
            	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.Main.runBuild(Main.java:854)
            	at org.apache.tools.ant.Main.startAnt(Main.java:236)
            	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
            	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
            Caused by: org.dita.dost.exception.DITAOTException: uri and file may not be null
            	at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:232)
            	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:70)
            	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:222)
            	... 29 more
            Caused by: java.lang.IllegalStateException: uri and file may not be null
            	at org.dita.dost.util.Job$FileInfo$Builder.build(Job.java:780)
            	at org.dita.dost.module.GenMapAndTopicListModule.categorizeCurrentFile(GenMapAndTopicListModule.java:606)
            	at org.dita.dost.module.GenMapAndTopicListModule.processFile(GenMapAndTopicListModule.java:448)
            	at org.dita.dost.module.GenMapAndTopicListModule.processWaitList(GenMapAndTopicListModule.java:378)
            	at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:224)
            	... 31 more

So it would seem that referencing markdown converted topics no longer work with the latest DITA OT 2.4.
At some point there were some changes made by @jelovirt in the FileInfo class, possibly this change caused the problem:

https://github.com/dita-ot/dita-ot/commit/378c0981d14fa141987df9b2e0c2336a14efd429

**Comment by jelovirt** [comment]
Fixed by 7dd77f91999e9c0bd3dd41670d31bfb88549bda3

**Comment by raducoravu** [comment]
👍

**Comment by ShabeerK** [comment]
I have also faced the same issue using the DITA-OT 2.4.3 version. Is there any older version in which markdown to DITA/PDF/HTML works fine?

Thanks!

Shabeer

**Comment by raducoravu** [comment]
2.3.3 is OK.

**Comment by ShabeerK** [comment]
Hi Radu,

Tried with DITA-OT 2.3.3 and it shows the conversion is successful to PDF and for HTML as well. But the PDF file is not getting generated. HTML output just shows the link to markdown file  and there is no styling applied.

> <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<meta name="copyright" content="(C) Copyright 2017" />
<meta name="DC.rights.owner" content="(C) Copyright 2017" />
<meta name="DC.Type" content="map" />
<meta name="DC.Format" content="XHTML" />
<link rel="stylesheet" type="text/css" href="commonltr.css" />
<title></title></head>
<body><div><ul class="map"><li class="topicref"><a href="test.md" target="_blank">test.md</a></li></ul></div></body></html>

> 

Also is there a way markdown directly convert to DITA output rather than HTML/PDF?
Shabeer

**Comment by raducoravu** [comment]
@ShabeerK I do not have enough details to know what's wrong, maybe if you would attach the entire ANT console output that you receive...
About this:

> Also is there a way markdown directly convert to DITA output rather than HTML/PDF?

@jelovirt has another DITA OT plugin:

https://github.com/dita-ot/org.dita.normalize

It can be installed side by side with the markdown plugin. It's transtype is "dita" and should produce in the output folder the DITA topics converted from the markdown ones.
