### ISSUE TITLE
dita-ot-2.4.3 install failure

### ISSUE THREAD

**Issue by StanDoherty** [dita-ot/dita-ot#2590]
Hi --

I cannot get dita-ot-2.4.3 to install.

I am running Java . . . 
C:\dita-ot-2.4.3\bin>java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

When I execute dita -install, I get UnsupportedClassVersionError . . . 
C:\dita-ot-2.4.3\bin>dita -install
java.lang.UnsupportedClassVersionError: org/dita/dost/invoker/Main : Unsupported
 major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
ant.home: C:\dita-ot-2.4.3\bin\..
. . .

**Comment by StanDoherty** [comment]
I encountered the same error on dita-ot-2.4 and dita-ot-2.4.2. 

Previous 2.3 and 2.2 toolkits installed correctly. 

Stan
