### ISSUE TITLE
Topicref to bookmap breaks PDF generation

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2596]
In a regular DITA Map you have a bookmap referenced like this:

    <map>
        <title>bla</title>
       <topicref href="first.dita">
           <topicref href="bookmap.ditamap" format="ditamap"/>
       </topicref>
   </map>

The PDF processing breaks with:

            Caused by: org.apache.fop.fo.ValidationException: "fo:page-sequence" is not a valid child of "fo:block"! (See position 3:91)
            	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
            	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
            	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)
            	at com.sun.proxy.$Proxy5.invalidChild(Unknown Source)
            	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:561)
            	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:537)
            	at org.apache.fop.fo.flow.Block.validateChildNode(Block.java:293)
            	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:276)
            	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
            	at net.sf.saxon.event.ContentHandlerProxy.startContent(ContentHandlerProxy.java:398)
            	... 66 more

[topicrefBookmap.zip](https://github.com/dita-ot/dita-ot/files/762979/topicrefBookmap.zip)

**Comment by raducoravu** [comment]
Probably most of the XSLT templates from "org.dita.pdf2\xsl\fo\commons.xsl" which process bookmap references like "processTopicChapter" should not start a "page-sequence" if they are not on the first level in the resolved map.

**Comment by robander** [comment]
Reproduced in 3.0, and thinking that the suggestion above is probably a good one.

**Comment by robander** [comment]
This proved more troublesome than I thought but I have a fix up that can be tested.

It keeps current processing the same for bookmap (no moving around of page sequences, no renaming of templates -- only breaking existing ones down a bit -- so any overrides will still work).

The fix allows you to use map references like the one submitted above, where:

1. Referencing map is not a bookmap
1. The reference is made within the context of another topic (so bookmap ends up nested in a topic)
1. The bookmap uses a chapter, part, preface / front matter topic, appendix, or appendices (each of these would previously set up a new page sequence inside the existing `fo:block`)
