### ISSUE TITLE
DITA OT 2.4.5 throw NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly in copy-to:

### ISSUE THREAD

**Issue by renemjrt** [dita-ot/dita-ot#2649]
There seems to be a problem with  commons.io.2.5 jar file  version shiped with latest dita ot. 
Target copy-to: throw error below.  I run the transformation  with oxygen editor. 
After I changed to commons.io.2.4 problem is   gone.

```
C:\Users\*\workspace_eclipse\ifx-dita-ot\dita-ot-2.4.5\plugins\org.dita.base\build_preprocess.xml:284: java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly(Ljava/io/File;)Z
            at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:348)
            at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:335)
            at org.dita.dost.module.CopyToModule.processMap(CopyToModule.java:91)
            at org.dita.dost.module.CopyToModule.execute(CopyToModule.java:65)
            at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:70)
            at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:222)
            at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            at org.apache.tools.ant.Task.perform(Task.java:348)
            at org.apache.tools.ant.Target.execute(Target.java:435)
            at org.apache.tools.ant.Target.performTasks(Target.java:456)
            at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            at org.apache.tools.ant.Task.perform(Task.java:348)
            at org.apache.tools.ant.Target.execute(Target.java:435)
            at org.apache.tools.ant.Target.performTasks(Target.java:456)
            at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            at org.apache.tools.ant.Task.perform(Task.java:348)
            at org.apache.tools.ant.Target.execute(Target.java:435)
            at org.apache.tools.ant.Target.performTasks(Target.java:456)
            at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
            at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
            at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            at org.apache.tools.ant.Main.runBuild(Main.java:854)
            at org.apache.tools.ant.Main.startAnt(Main.java:236)
            at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
            at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by raducoravu** [comment]
This is not a bug in the DITA OT. It is a problem in the list of libraries Oxygen uses to start the DITA OT. The Oxygen main libraries contain a patch for an older commons.io package so the list of libraries used by Oxygen to start the DITA OT needs to refer to the commons IO bundled with DITA OT before referring to the Oxygen main libraries. I'm attaching an image with the default list of JAR libraries in Oxygen 18.1.
What Oxygen version do you have?
![classpathorder](https://cloud.githubusercontent.com/assets/1005979/24739216/93830bf0-1aa3-11e7-94fa-9f1df3e49f5b.png)

**Comment by renemjrt** [comment]
Hi Radu,

I am so sorry for late answer.  I am still using Oxygen 17.1 and I am planning to move to you new one - version -19.00

I have been check the libraries in 17.1 and it is pointing to commons-io.2.4.jar. So we can close this ticket.

Once again thanks for hint.

**Comment by renemjrt** [comment]
with Oxygen 19.0 no problem
