### ISSUE TITLE
NullPointerException when processing invalid email link

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2654]
The topic contains something like:

            <xref href="mailto:test@test.com">test@test.com</xref>

and with DITA OT 2.4.4 produces the NPE:

                D:\projects\eXml\frameworks\dita\DITA-OT2.x\build.xml:45: The following error occurred while executing this line:
                D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.base\build_preprocess.xml:47: Failed to run pipeline: null
                	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:228)
                	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
                	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
                	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                	at java.lang.reflect.Method.invoke(Unknown Source)
                	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                	at org.apache.tools.ant.Task.perform(Task.java:348)
                	at org.apache.tools.ant.Target.execute(Target.java:435)
                	at org.apache.tools.ant.Target.performTasks(Target.java:456)
                	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
                	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
                	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
                	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
                	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
                	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
                	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
                	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                	at java.lang.reflect.Method.invoke(Unknown Source)
                	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                	at org.apache.tools.ant.Task.perform(Task.java:348)
                	at org.apache.tools.ant.Target.execute(Target.java:435)
                	at org.apache.tools.ant.Target.performTasks(Target.java:456)
                	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
                	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
                	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
                	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
                	at org.apache.tools.ant.Main.runBuild(Main.java:854)
                	at org.apache.tools.ant.Main.startAnt(Main.java:236)
                	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
                	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
                Caused by: org.dita.dost.exception.DITAOTException
                	at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:235)
                	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:70)
                	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:222)
                	... 29 more
                Caused by: java.lang.NullPointerException
                	at org.dita.dost.reader.GenListModuleReader.isOutFile(GenListModuleReader.java:705)
                	at org.dita.dost.reader.GenListModuleReader.toOutFile(GenListModuleReader.java:725)
                	at org.dita.dost.reader.GenListModuleReader.parseAttribute(GenListModuleReader.java:585)
                	at org.dita.dost.reader.GenListModuleReader.startElement(GenListModuleReader.java:437)
                	at org.dita.dost.reader.KeydefFilter.startElement(KeydefFilter.java:89)
                	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:104)
                	at org.xml.sax.helpers.XMLFilterImpl.startElement(Unknown Source)

**Comment by raducoravu** [comment]
👍 We had another user report the same NPE, not sure if it's caused by the same type of link, she did not provide the samples.

**Comment by raducoravu** [comment]
By the way for anybody reading this thread and wandering about it the proper way to add a link to an email address is this one:

           <xref href="mailto:radu_coravu@oxygenxml.com" format="html" scope="external"/>

**Comment by jelovirt** [comment]
IMO using `format="html"` for email is just wrong, but I can understand why people use `html` to mean "it's not DITA, it's something else".

**Comment by raducoravu** [comment]
Right :)

**Comment by robander** [comment]
Same here, I've suggested either `format="mailto"` or `format="email"` to people in the past, but there is definitely no "standard" and a lot of people I know use `html` as a default for most non-DITA links (including email).

**Comment by jelovirt** [comment]
An improvement we could have in the clean-up steps is to change the format to `email` when the URI scheme is `mailto`. Either just add `email` when `@format` has not been defined, or always fix it.
