### ISSUE TITLE
NPE in ForceUniqueFilter

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2657]
Our QA team found this:

        E:\KiTuri\qa\oxygen\frameworks\dita\DITA-OT2.x\plugins\org.dita.base\build_preprocess.xml:290:
        java.lang.NullPointerException
            at
        org.dita.dost.writer.ForceUniqueFilter.generateCopyToTarget(ForceUniqueFilter.java:101)
            at
        org.dita.dost.writer.ForceUniqueFilter.startElement(ForceUniqueFilter.java:67)
            at
        org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
            at
        org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown
        Source)
            at
        org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(Unknown
        Source)
            at
        org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown
        Source)
            at
        org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown
        Source)
            at
        org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown
        Source)
            at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            at
        org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(Unknown
        Source)
            at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
            at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
            at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:451)
            at net.sf.saxon.event.Sender.send(Sender.java:153)
            at
        net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:375)
            at org.dita.dost.util.XMLUtils.transformFile(XMLUtils.java:391)
            at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:346)
            at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:335)
            at org.dita.dost.module.CopyToModule.processMap(CopyToModule.java:91)
            at org.dita.dost.module.CopyToModule.execute(CopyToModule.java:65)
            at
        org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:70)
            at
        org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:222)
            at
        org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at
        org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            at org.apache.tools.ant.Task.perform(Task.java:348)
            at org.apache.tools.ant.Target.execute(Target.java:435)
            at org.apache.tools.ant.Target.performTasks(Target.java:456)
            at
        org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405) 

If I find some samples to reproduce the problem I'll be back.

**Comment by raducoravu** [comment]
It can be reproduced if I have a topic with an invalid ID set on an element:

    <?xml version='1.0' encoding='UTF-8'?>
    <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
    <topic id="lilac">
     <title>Lilac</title>
     <body>
      <p id="li lac"><b>Lilac</b> </p>
     </body>
    </topic>

and I refer to it twice in the DITA Map.
