### ISSUE TITLE
Possible NPE when interpreting Antenna House log

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2662]
We had this error reported to us:

            C:\Program Files\Oxygen XML Editor 18\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2.axf\build_axf.xml:225: The following error occurred while executing this line:
            C:\Program Files\Oxygen XML Editor 18\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2.axf\build_axf.xml:243: java.lang.NullPointerException
                        at org.dita.dost.pdf2.AhfLogProcessorTask.execute(AhfLogProcessorTask.java:43)
                        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
                        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                        at java.lang.reflect.Method.invoke(Unknown Source)
                        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
                        at org.apache.tools.ant.Task.perform(Task.java:348)
                        at org.apache.tools.ant.Target.execute(Target.java:435)

In the "build_axf.xml" there is a "log-processor" task which interprets the log emitted by Antenna House. It seems to not be very robust, it expects for example that the log file is longer than two lines.

**Comment by raducoravu** [comment]
👍 I reproduced this issue publishing probably using a broken Antenna House installation:

            transform.fo2pdf.ah.nooption:
                  [ahf] Processing D:\projects\eXml\samples\dita\flowers/temp/pdf/oxygen_dita_temp/topic.fo to D:\projects\eXml\samples\dita\flowers\out\pdf/flowers.pdf
                 [exec] Result: -1073741515
            
            BUILD FAILED
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\build.xml:45: The following error occurred while executing this line:
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2\build.xml:140: The following error occurred while executing this line:
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2.axf\build_axf.xml:195: The following error occurred while executing this line:
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2.axf\build_axf.xml:213: java.lang.NullPointerException
            	at org.dita.dost.pdf2.AhfLogProcessorTask.execute(AhfLogProcessorTask.java:46)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:10

**Comment by infotexture** [comment]
Fixed for 3.1.1 w/ PR #3012.
