### ISSUE TITLE
Win7 SP1 installations fail for dita-ot-2.5.x

### ISSUE THREAD

**Issue by StanDoherty** [dita-ot/dita-ot#2741]
I am running Win7 SP1 with JDK 1.8.0_131 (the latest) and receive the following error message when I run either "dita --install" or "ant -f integrator.xml":

C:\dita-ot-2.5.1\bin>dita --install
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/to
ols/ant/launch/Launcher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:472)

Is there some package dependency that needs to be satisfied to run dita-ot-2.5.x on Windows 7?

The same dita-ot binaries install and run fine on my new Windows systems and on MacOS.

**Comment by jelovirt** [comment]
You're running an older version of Java. Debug by running

`%JAVA_HOME%\bin\java.exe -version`

or just

`java.exe -version`

**Comment by StanDoherty** [comment]
Hi --

When I run java.exe -version, I get:

C:\dita-ot-2.5.1\bin>java.exe -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

That is the most current version of the Java JDK available from Oracle. 

Sorry . . . what am I missing?

Thanx
Stan

**Comment by jelovirt** [comment]
And for `%JAVA_HOME%\bin\java.exe`?

**Comment by StanDoherty** [comment]
Ouch . . . 

I get:

C:\dita-ot-2.5.1\bin>echo %JAVA_HOME%
c:\Program Files\Java\jdk1.7.0

Sorry . . . I need to track down that environment variable definition. 

Duh . . . forgive me.
