### ISSUE TITLE
NullPointerException in DITA OT 3.x

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2828]
One of our clients seems to have found a NPE in DITA OT 3.x:

    BUILD FAILED
     /Users/......../tools/dita-ot-3.0/build.xml:45: The following error occurred while executing this line:
     /Users/.........../dita-ot-3.0/plugins/org.dita.base/build_preprocess2.xml:176: java.lang.NullPointerException
	at org.dita.dost.module.reader.TopicReaderModule.getStartDocuments(TopicReaderModule.java:169)
	at org.dita.dost.module.reader.TopicReaderModule.readStartFile(TopicReaderModule.java:133)
	at org.dita.dost.module.reader.TopicReaderModule.execute(TopicReaderModule.java:70)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:163)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

**Comment by raducoravu** [comment]
If I get any samples I will post them on the issue.

**Comment by robertnthomas** [comment]
I get the same error. It appears to be caused by /bookmap/bookmeta/data/image/@href. I use this markup in bookmap to point to front cover and back cover artwork.

**Comment by coderliz** [comment]
I encountered the same problem when I compiled htmlhelp

**Comment by jelovirt** [comment]
The root cause is that if we have

```xml
<data href="image.jpg"/>
```
Both preprocess and preprocess2 will assume that is a reference to a DITA topic. The normal explicit `@format` value is used also in `<data>` element.

There is no obvious answer how to handle this case. The NPE is something that can be fixed, but the underlying issue might need a fix too.

**Comment by jelovirt** [comment]
@raducoravu I still can't reproduce this.

**Comment by raducoravu** [comment]
@robertnthomas could you maybe attach a sample small project to reproduce the issue?
Having something like this in the DITA Map:

                 <data href="images/Chrysanthemums.jpg" />

produces an error with DITA OT 3.x, it also produced an error with DITA OT 2.x and I cannot reproduce that NullPointerException with DITA OT 3.x, even without @jelovirt 's fixes.

**Comment by hscherzer** [comment]
I had the same problem and patched TopicReaderModule.java to get some more info. Finally I found that in Line 169
`if (fi == null) {
   fi = job.getFileInfo(tmp.resolve(href));
 }
 assert fi != null;
`
getFileInfo(....) **does not find the chapters's children** (the topicrefs) in the temp-directory (and they aren't there).
Further research showed that my definition of the **tempdir = ${cfd}\..\build\temp** is THE PROBLEM because the parent notation \..\ (or /../) is not interpreted by that process that stores the topicrefs into the tempdir.

Since DITA-OT3 this process has changed because it does name mangling (changing a name of a file like "mychapter.dita" into something like "bb308a949b3f699f027435c09ca750e19ae16dce.dita" (which is perfectly OK). But the process doing that (and storing those mangled files) doesn't seem to correctly understand such ${cfd}\..\build\temp parent notation as target dir and therefore does not store the topicrefs into the tempdir.

Consequently ... getFileInfo(....) does not find the chapters's children. And the assertion kills the process.

**SOLUTION:** Do no use relative notation in the tempdir definition ... until the problem is solved. I do not consider this a severe bug, but a bit hard to find ... so I hope this contributes to some change when time is available.

Feel free to contact me under helmut.scherzer@gi-de.com I might not scan this issue often enough.
