### ISSUE TITLE
Error in HTML publishing if any topic has apostrophe in its name

### ISSUE THREAD

**Issue by rahul1995** [dita-ot/dita-ot#2844]
Create a topic with apostrophe in its name e.g. i'm_topic.dita. Put it in ditamap and publish.
PDF works fine but xhtml and html5 give NullPointerException.

**Comment by raducoravu** [comment]
Indeed a NPE can be obtained with DITA OT 3.0, also with 2.5.2:

            BUILD FAILED
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0\build.xml:197: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0\plugins\org.dita.xhtml\build_general.xml:170: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0\plugins\org.dita.xhtml\build_general.xml:128: java.lang.NullPointerException
            	at org.dita.dost.ant.types.JobMapper.mapFileName(JobMapper.java:83)
            	at org.dita.dost.module.XsltModule.execute(XsltModule.java:110)
            	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:163)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:402)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
            	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.Main.runBuild(Main.java:857)
            	at org.apache.tools.ant.Main.startAnt(Main.java:236)
            	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
            	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

**Comment by jelovirt** [comment]
Unable to reproduce with `hotfix/3.0.2`on OS X.

**Comment by raducoravu** [comment]
I can still reproduce the NPE on Windows. I patched the code and added some logging.
So for a topic called "i'm_topic.dita" (without the quotes) the .job.xml adds an entry like:

        <file src="file:/D:/projects/eXml/samples/dita/flowers/topics/i'm_topic.dita"
            uri="topics/i'm_topic.dita" path="topics\i'm_topic.dita"
            result="file:/D:/projects/eXml/samples/dita/flowers/topics/i'm_topic.dita" format="dita"
            target="true"/>

The method "org.dita.dost.ant.types.JobMapper.mapFileName(String)" receives a "sourceFileName" param with value "topics\i'm_topic.dita", creates from it an URI like "topics/i%27m_topic.dita" and then tries to find it in the ".job.xml", turning up with no mapping for it.

**Comment by raducoravu** [comment]
+1 Another end user encountered the same problem

**Comment by raducoravu** [comment]
👍 And yet another one of our end users encountered the same problem.

**Comment by raducoravu** [comment]
Still get the same NPE in DITA OT 3.1.2, @robander can you reproduce this problem on your Windows installation?

**Comment by robander** [comment]
@raducoravu yes, just tried this and I can reproduce the NPE with `html5` build from `develop`. PDF output is OK.

**Comment by raducoravu** [comment]
👍 Another one of our clients experienced this problem.

**Comment by raducoravu** [comment]
👍 One of our QA team encountered this problem again because they had an apostrophe in a DITA file name.

**Comment by thendarion** [comment]
I just encountered this. it took a while to track down the error. I'd like to have a check and an informative error message for this, please, if it's not too much trouble

**Comment by raducoravu** [comment]
+1 we had another end user with a file name with apostrophe in its name.

**Comment by raducoravu** [comment]
+1 another one of our clients was using " what's_new_installation.dita" as the name of a file and this produced the NPE.

**Comment by raducoravu** [comment]
I can no longer reproduce this problem with DITA OT 3.6. Can somebody else test this with DITA OT 3.6 just to double check?

**Comment by raducoravu** [comment]
Actually I can still reproduce the problem with 3.6.1 publishing to HTML5:


    /Users/r../dita-ot-3.6.1/plugins/org.dita.base/build.xml:29: The following error occurred while executing this line:
    /Users/../dita-ot-3.6.1/plugins/org.dita.html5/build_dita2html5.xml:125: The following error occurred while executing this line:
    /Users/..dita-ot-3.6.1/plugins/org.dita.html5/build_dita2html5.xml:157: java.lang.NullPointerException
	at org.dita.dost.ant.types.JobMapper.mapFileName(JobMapper.java:79)
Re-attaching test samples:
[testApos.zip](https://github.com/dita-ot/dita-ot/files/6783724/testApos.zip)

**Comment by raducoravu** [comment]
👍 One of our end users encountered this problem, they have an "User's Guide" folder with topics inside it.

**Comment by jelovirt** [comment]
@jlacour31 are you able to test that #3880 fixed this?

**Comment by jlacour31** [comment]
> @jlacour31 are you able to test that #3880 fixed this?

I created a unit test that runs html5 transformation on ditamap and topics having apos in their names. The test did succeed.
