### ISSUE TITLE
DOMException when using two "ditavalref"'s on first level in map

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2865]
Reported here:

https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/43072

I'm attaching a sample project:
 
[two-ditavalref-map.zip](https://github.com/dita-ot/dita-ot/files/1566943/two-ditavalref-map.zip)

There are two ditaval files referenced on the first DITA Map level like:

    <map>
       <ditavalref href="ditavals/AWS.ditaval"/>
       <ditavalref href="ditavals/LINUX.ditaval"/>
    

I can reproduce problem with both DITA OT 2.x and 3.x:

    BUILD FAILED
    C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\build.xml:45: The following error occurred     while executing this line:
    C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\plugins\org.dita.base\build_preprocess2.xml:110: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted.
	at org.apache.xerces.dom.CoreDocumentImpl.insertBefore(Unknown Source)
	at org.apache.xerces.dom.NodeImpl.appendChild(Unknown Source)
	at org.dita.dost.module.filter.MapBranchFilterModule.splitBranches(MapBranchFilterModule.java:326)
	at org.dita.dost.module.filter.MapBranchFilterModule.processMap(MapBranchFilterModule.java:111)
	at org.dita.dost.module.filter.MapBranchFilterModule.execute(MapBranchFilterModule.java:78)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:163)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

**Comment by lief-erickson** [comment]
@raducoravu posted a workaround on the dita-users list, which may be helpful for some until a fix is created.

> A workaround for it seems to be the use of a topicgroup to wrap everything up.
>
```
<map>
    <topicgroup>
        <ditavalref href="ditavals/AWS.ditaval"/>
        <ditavalref href="ditavals/LINUX.ditaval"/>
        <topicref href="choicetable.dita" platform="AWS" />
        <topicref href="filepath.dita" platform="AWS" />
        <topicref href="table_number.dita" platform="LINUX" />
        <topicref href="task_labels.dita" platform="LINUX" />
    </topicgroup>
</map>
```

**Comment by raducoravu** [comment]
Another one of our users reproduced a very similar problem, this time coming from the BranchFilterModule class:

                HIERARCHY_REQUEST_ERR: Une tentative a été faite pour insérer un n?ud là où il n'est pas autorisé.
                	at org.apache.xerces.dom.CoreDocumentImpl.insertBefore(Unknown Source)
                	at org.apache.xerces.dom.NodeImpl.appendChild(Unknown Source)
                	at org.dita.dost.module.BranchFilterModule.splitBranches(BranchFilterModule.java:473)
                	at org.dita.dost.module.BranchFilterModule.processMap(BranchFilterModule.java:130)
                	at org.dita.dost.module.BranchFilterModule.execute(BranchFilterModule.java:100)
                	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:80)

**Comment by robander** [comment]
I've started work on a fix for this but am not quite certain how to handle some cases.

The issue begins here in the method `splitBranches`:
https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/module/BranchFilterModule.java#L461

Basically it splits by:

1. Collect each `ditavalref` from the current node
2. Remove those from the current element
3. Create a new branch that's a copy of the current one, with one `ditavalref` per branch
4. Replace the branch with those copies

When the "branch" is actually the root node, and there are 2 or more `ditavalref` elements, this replaces the root node with more than one node, which causes the DOM exception.

My attempt to replace it was basically to detect when it's the root node with 2 or more `ditavalref`, and in that case, create a `topicgroup` style wrapper to hold all of the content. That seems simple enough, but also results in `reltable` elements within the topicgroup, which will likely break later steps that reasonably assume `reltable` can only be at the root level.

I think what's needed for this condition is:

- Create the `topicgroup`
- Move everything inside of `topicgroup` (everything = all except the title + topicmeta)
- Proceed with the branch filtering to rename and filter topics
- Add a new step at the end of the module that moves the `reltable` elements (with properly renamed topics) back to the root level

That would fix the DOM exception and handle common cases, but it could also mess with key resolution if there are key scopes in play. For example, if each branch creates a new key scope, the relationship table would be properly in that scope at first but then then moved out.

**Comment by raducoravu** [comment]
@robander makes sense, the relationship between the reltable and branch filtering is a little murky, at some point I added an issue to clarify it: https://github.com/dita-ot/dita-ot/issues/2147

**Comment by robander** [comment]
Right, it is murky, and I'm not sure it can be fully handled (correctly) without larger changes to the processing pipeline.

Of course, using more than one `ditavalref` at the start of a map has other issues too. For example if you do it with `bookmap` (using the proposed DITA 2.0 model), you can end up with two separate sequences of [front matter, chapters, back matter]. 

I think the best fix here might be:
- Implement the solution I suggested above
- If relationship tables + key scopes do not work for some cases (they might, I'm not sure), then try and work out a design with #2147)
- Advise that if you're trying to use `ditavalref` on the root map, you should take care; it may not be the most logical way to publish information anyway, due to the issues that can come up

**Comment by raducoravu** [comment]
Problem can still be reproduced with latest DITA OT code.

**Comment by raducoravu** [comment]
+1 another one of our end users run into the same problem with two ditaval refs referenced on the top level of the DITA Map.

**Comment by ericsirois** [comment]
+1 We have a client that has run into this issue as well.  In their case, they are using bookmap where they have modified the DTDs to make ditavalref available at the root level.  On another note, would this need to be updated for DITA 2.0 where ditavalref is within a mapresource

**Comment by ericsirois** [comment]
We temporarily have resolved this issue by adding a depend.preprocess.pre that merges all the ditavalrefs referenced as a direct child of the root map/bookmap element into one ditavalref file and replaces the reference accordingly in the map.  That seems to be a satisfactory solution for this client for now.
