### ISSUE TITLE
NullPointerException in HtmlParser

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2867]
Publishing the attached project to XHTML using the DITA OT 3.0.1 results in:

            BUILD FAILED
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\build.xml:45: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\plugins\org.dita.base\build_preprocess.xml:85: java.lang.NullPointerException
            	at net.sf.saxon.event.ReceivingContentHandler.processingInstruction(ReceivingContentHandler.java:537)
            	at org.dita.dost.module.DebugAndFilterModule$DTDForwardHandler.startDTD(DebugAndFilterModule.java:573)
            	at nu.validator.saxtree.TreeParser.startDTD(TreeParser.java:246)
            	at nu.validator.saxtree.DTD.visit(DTD.java:71)
            	at nu.validator.saxtree.TreeParser.parse(TreeParser.java:89)
            	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:428)
            	at com.elovirta.dita.html.HtmlReader.parse(HtmlReader.java:148)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
            	at org.dita.dost.module.DebugAndFilterModule.processFile(DebugAndFilterModule.java:180)
            	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
            	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
            	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)

[testNPEHtmlParser.zip](https://github.com/dita-ot/dita-ot/files/1571780/testNPEHtmlParser.zip)

There is no HTML file referenced in that project, only a MathML one.

**Comment by jelovirt** [comment]
I'm unable to reproduce the NPE with 3.0.2. I do get an error message HtmlParser, but not a NPE.

**Comment by jelovirt** [comment]
The cause seems to be that format `mml` is not recognized in gen-list module and is saved to job configuration as format `html`. Format `html` has traditionally means "something that's not DITA", but now that we can actually process HTML as HDITA, this no longer applies.

**Comment by raducoravu** [comment]
I confirm error is no longer reported
