### ISSUE TITLE
InvalidPathException when publishing remote DITA Map to PDF

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2868]
This used to work with DITA OT 2.x but it no longer does with DITA OT 3.x.
The published DITA Map is here:

https://raw.githubusercontent.com/gnostyx/dita-demo-content-collection/master/Thunderbird/User_Guide.ditamap

and the publishing breaks with:

            map-reader:
            [map-reader] Using Xerces grammar pool for DTD and schema caching.
            [map-reader] Processing https://raw.githubusercontent.com/gnostyx/dita-demo-content-collection/master/Thunderbird/User_Guide.ditamap to file:/D:/projects/eXml/test/dita/temp/xhtml_rem/b27694fec64da5944eb9cb7688e400b3a7d204e2.ditamap
            
            BUILD FAILED
            D:\projects\oxygen-dita-ot-3.x\build.xml:45: The following error occurred while executing this line:
            D:\projects\oxygen-dita-ot-3.x\plugins\org.dita.base\build_preprocess2.xml:67: java.nio.file.InvalidPathException: Illegal char <:> at index 5: https:\raw.githubusercontent.com\gnostyx\dita-demo-content-collection\master\Thunderbird\User_Guide.ditamap
            	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
            	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
            	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
            	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
            	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
            	at java.io.File.toPath(File.java:2234)
            	at org.dita.dost.util.FileUtils.getRelativePath(FileUtils.java:169)
            	at org.dita.dost.writer.DitaWriterFilter.startDocument(DitaWriterFilter.java:94)
            	at org.dita.dost.reader.GenListModuleReader.startDocument(GenListModuleReader.java:387)
            	at org.xml.sax.helpers.XMLFilterImpl.startDocument(XMLFilterImpl.java:482)
            	at org.xml.sax.helpers.XMLFilterImpl.startDocument(XMLFilterImpl.java:482)
            	at org.xml.sax.helpers.XMLFilterImpl.startDocument(XMLFilterImpl.java:482)
            	at org.dita.dost.writer.ProfilingFilter.startDocument(ProfilingFilter.java:214)
            	at org.dita.dost.writer.DebugFilter.startDocument(DebugFilter.java:49)
            	at org.apache.xerces.parsers.AbstractSAXParser.startDocument(Unknown Source)
            	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startDocument(RelaxNGDefaultsComponent.java:187)
            	at org.apache.xerces.impl.xs.XMLSchemaValidatorXerces.startDocument(XMLSchemaValidatorXerces.java:305)
            	at org.apache.xerces.impl.xs.XMLSchemaValidator.startDocument(XMLSchemaValidator.java:102)
            	at org.apache.xerces.impl.dtd.XMLDTDValidatorXerces.startDocument(XMLDTDValidatorXerces.java:719)
            	at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(XMLDTDValidator.java:104)

**Comment by raducoravu** [comment]
Actually the exception above is on Windows, for Linux the reported exception is a NullPointerException"

            java.lang.NullPointerException
            	at org.dita.dost.util.FileUtils.getRelativePath(FileUtils.java:169)
            	at org.dita.dost.writer.DitaWriterFilter.startDocument(DitaWriterFilter.java:94)
            	at org.dita.dost.reader.GenListModuleReader.startDocument(GenListModuleReader.java:388)
            	at org.xml.sax.helpers.XMLFilterImpl.startDocument(XMLFilterImpl.java:482)
            	at org.xml.sax.helpers.XMLFilterImpl.startDocument(XMLFilterImpl.java:482)
            	at org.xml.sax.helpers.XMLFilterImpl.startDocument(XMLFilterImpl.java:482)
            	at org.dita.dost.writer.ProfilingFilter.startDocument(ProfilingFilter.java:214)
            	at org.dita.dost.writer.DebugFilter.startDocument(DebugFilter.java:49)
            	at org.apache.xerces.parsers.AbstractSAXParser.startDocument(Unknown Source)
            	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startDocument(RelaxNGDefaultsComponent.java:187)
            	at org.apache.xerces.impl.xs.XMLSchemaValidatorXerces.startDocument(XMLSchemaValidatorXerces.java:305)
            	at org.apache.xerces.impl.xs.XMLSchemaValidator.startDocument(XMLSchemaValidator.java:102)
            	at org.apache.xerces.impl.dtd.XMLDTDValidatorXerces.startDocument(XMLDTDValidatorXerces.java:719)
