### ISSUE TITLE
Cannot produce EclipseHelp with DITA OT 3.0.1

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2870]
Eclipsehelp "plugin.xml" does not refer to "eclipsehelp.jar". So with DITA OT 3.0.1, publishing to Eclipse Help using the command line:

    dita -i D:\projects\eXml\test\dita\transform\hierarchy.ditamap -f eclipsehelp

generates these problems:

            dita.out.map.eclipse.index:
                 [echo]  args.eclipsehelp.indexsee = false 
             [pipeline] [Fatal Error] :-1:-1: Premature end of file.
             [pipeline] [DOTJ013E][ERROR] Failed to parse the referenced file 'file:/D:/projects/eXml/test/dita/transform/temp/eclipsehelp/oxygen_dita_temp/tasks/flowers.pdf'.Premature end of file.
             [pipeline] java.lang.ClassNotFoundException: org.dita.dost.writer.EclipseIndexWriter
             [pipeline] 	at java.net.URLClassLoader.findClass(Unknown Source)
             [pipeline] 	at java.lang.ClassLoader.loadClass(Unknown Source)
             [pipeline] 	at java.lang.ClassLoader.loadClass(Unknown Source)
             [pipeline] 	at java.lang.Class.forName0(Native Method)
             [pipeline] 	at java.lang.Class.forName(Unknown Source)
             [pipeline] 	at org.dita.dost.index.IndexTermCollection.outputTerms(IndexTermCollection.java:165)
             [pipeline] 	at org.dita.dost.module.IndexTermExtractModule.execute(IndexTermExtractModule.java:77)
             [pipeline] 	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:163)
             [pipeline] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
             [pipeline] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
             [pipeline] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
             [pipeline] 	at java.lang.reflect.Method.invoke(Unknown Source)
             [pipeline] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
             [pipeline] 	at org.apache.tools.ant.Task.perform(Task.java:348)
             [pipeline] 	at org.apache.tools.ant.Target.execute(Target.java:435)
             [pipeline] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
             [pipeline] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
             [pipeline] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
             [pipeline] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
             [pipeline] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
             [pipeline] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
             [pipeline] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
             [pipeline] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
             [pipeline] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
             [pipeline] 	at java.lang.reflect.Method.invoke(Unknown Source)
             [pipeline] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
             [pipeline] 	at org.apache.tools.ant.Task.perform(Task.java:348)
             [pipeline] 	at org.apache.tools.ant.Target.execute(Target.java:435)
             [pipeline] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
             [pipeline] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
             [pipeline] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
             [pipeline] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
             [pipeline] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
             [pipeline] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
             [pipeline] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
             [pipeline] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
             [pipeline] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
             [pipeline] 	at java.lang.reflect.Method.invoke(Unknown Source)
             [pipeline] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
             [pipeline] 	at org.apache.tools.ant.Task.perform(Task.java:348)
             [pipeline] 	at org.apache.tools.ant.Target.execute(Target.java:435)
             [pipeline] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
             [pipeline] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
             [pipeline] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
             [pipeline] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
             [pipeline] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
             [pipeline] 	at org.apache.tools.ant.Main.runBuild(Main.java:857)
             [pipeline] 	at org.apache.tools.ant.Main.startAnt(Main.java:236)
             [pipeline] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
             [pipeline] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
            
            BUILD FAILED
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\build.xml:45: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\plugins\org.dita.eclipsehelp\build_dita2eclipsehelp.xml:35: The following error occurred while executing this line:
            C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\plugins\org.dita.eclipsehelp\build_dita2eclipsehelp.xml:128: java.lang.NullPointerException
            	at org.dita.dost.index.IndexTermCollection.outputTerms(IndexTermCollection.java:196)
            	at org.dita.dost.module.IndexTermExtractModule.execute(IndexTermExtractModule.java:77)
            	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:163)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
            	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
            	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)
            	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
            	at org.apache.tools.ant.Task.perform(Task.java:348)
            	at org.apache.tools.ant.Target.execute(Target.java:435)
            	at org.apache.tools.ant.Target.performTasks(Target.java:456)
            	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
            	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
            	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
            	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
            	at org.apache.tools.ant.Main.runBuild(Main.java:857)
            	at org.apache.tools.ant.Main.startAnt(Main.java:236)
            	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
            	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
            
            Total time: 13 seconds
            
            The process finished with exit code: 1

**Comment by raducoravu** [comment]
If the reference to the JAR is added in the plugin.xml, this results later on in the transformation in this problem:

            dita.inner.topics.html.common:
             [pipeline] Transforming into D:\projects\eXml\test\dita\transform\out\eclipsehelp
             [pipeline] Static error at char 11 near {...m:random-sequence(1, $seed)...} in expression in xsl:variable/@select on line 960 column 28 of learning2domain2html.xsl:
             [pipeline]   XPST0017: Cannot find a 2-argument function named {http://exslt.org/random}random-sequence()
             [pipeline] Warning at char 3 in xsl:sequence/@select on line 255 column 37 of dita-support-lib.xsl:

probably because the bundled Saxon no longer allows Java extension functions and there are still some of them in the XSLTs.

**Comment by thendarion** [comment]
it's 3.1 now and still no eclipsehelp output :(

**Comment by eerohele** [comment]
Isn't fixing this just a matter of adding an entry for `eclipsehelp.jar` into `org.dita.eclipsehelp/plugin.xml`?

```diff
--- a/src/main/plugins/org.dita.eclipsehelp/plugin.xml
+++ b/src/main/plugins/org.dita.eclipsehelp/plugin.xml
@@ -28,6 +28,7 @@ See the accompanying LICENSE file for applicable license.
     </param>
   </transtype>
   <require plugin="org.dita.xhtml"/>
+  <feature extension="dita.conductor.lib.import" file="lib/eclipsehelp.jar"/>
   <feature extension="ant.import" file="build_dita2eclipsehelp.xml"/>
   <template file="build_dita2eclipsehelp_template.xml"/>
   <template file="xsl/map2eclipse_template.xsl"/>
```

**Comment by jelovirt** [comment]
@eerohele Yes. How on earth did I miss that when I separated the Java code build into plugins. Easy first PR is someone's interested.

**Comment by dukepeet** [comment]
is there perhaps an ETA for 3.1.1?

**Comment by jelovirt** [comment]
Most likely after July.
