### ISSUE TITLE
Better failure message when using "generate.copy.outer=2"

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3013]
If using "generate.copy.outer=2" as a parameter with a DITA OT 3.1 PDF transformation the publishing fails with something like:

      \dita-ot-3x-plugin-master\dita-   ot-3.x\build.xml:45: The following error occurred while executing this line:
      dita-ot-3x-plugin-master\dita-ot-3.x\plugins\org.dita.base\build_preprocess2.xml:71: java.lang.IllegalArgumentException
	at org.dita.dost.util.Job$Generate.get(Job.java:856)
	at org.dita.dost.util.Job.setGeneratecopyouter(Job.java:902)
	at org.dita.dost.module.reader.AbstractReaderModule.parseInputParameters(AbstractReaderModule.java:230)
	at org.dita.dost.module.reader.MapReaderModule.execute(MapReaderModule.java:46)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)

which is very hard to figure out. How about if we add a fail in the build.xml for this instead of breaking only in the Java code?

**Comment by eerohele** [comment]
Duplicate of #1935?

**Comment by raducoravu** [comment]
@eerohele, right, closing as duplicate of https://github.com/dita-ot/dita-ot/issues/1935
