### ISSUE TITLE
Rendering HTMLHelp throws MalformedURLException when ditamap filename contains umlaut

### ISSUE THREAD

**Issue by c-kunz** [dita-ot/dita-ot#3149]
## Expected Behavior
CHM file is created without exceptions.

## Actual Behavior
Throws MalformedURLException.

## Workaround
Rename ditamap so that it contains *no umlauts* (`map.ditamap`).

## Steps to Reproduce

1. Download test files from Gist:
  https://gist.github.com/c-kunz/166a44f5dad8278804197e74f99121d4
2. `dita -f htmlhelp -i mäp.ditamap -o .`

## Copy of the error message, log file or stack trace
```cmd
C:\...>dita -f htmlhelp -i mäp.ditamap -o .
[check-lang] java.net.MalformedURLException: unknown protocol: c
[check-lang]    at java.net.URL.<init>(URL.java:600)
[check-lang]    at java.net.URL.<init>(URL.java:490)
[check-lang]    at java.net.URL.<init>(URL.java:439)
[check-lang]    at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
[check-lang]    at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
[check-lang]    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[check-lang]    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[check-lang]    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[check-lang]    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
[check-lang]    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
[check-lang]    at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
[check-lang]    at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
[check-lang]    at org.dita.dost.ant.CheckLang.execute(CheckLang.java:78)
[check-lang]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[check-lang]    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[check-lang]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[check-lang]    at java.lang.reflect.Method.invoke(Method.java:498)
[check-lang]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[check-lang]    at org.apache.tools.ant.Task.perform(Task.java:350)
[check-lang]    at org.apache.tools.ant.Target.execute(Target.java:448)
[check-lang]    at org.apache.tools.ant.Target.performTasks(Target.java:469)
[check-lang]    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[check-lang]    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
[check-lang]    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[check-lang]    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
[check-lang]    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[check-lang]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[check-lang]    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[check-lang]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[check-lang]    at java.lang.reflect.Method.invoke(Method.java:498)
[check-lang]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[check-lang]    at org.apache.tools.ant.Task.perform(Task.java:350)
[check-lang]    at org.apache.tools.ant.Target.execute(Target.java:448)
[check-lang]    at org.apache.tools.ant.Target.performTasks(Target.java:469)
[check-lang]    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[check-lang]    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
[check-lang]    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[check-lang]    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
[check-lang]    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[check-lang]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[check-lang]    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[check-lang]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[check-lang]    at java.lang.reflect.Method.invoke(Method.java:498)
[check-lang]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[check-lang]    at org.apache.tools.ant.Task.perform(Task.java:350)
[check-lang]    at org.apache.tools.ant.Target.execute(Target.java:448)
[check-lang]    at org.apache.tools.ant.Target.performTasks(Target.java:469)
[check-lang]    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[check-lang]    at org.apache.tools.ant.Project.executeTarget(Project.java:1370)

[check-lang]    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[check-lang]    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[check-lang]    at org.dita.dost.invoker.Main.runBuild(Main.java:1162)
[check-lang]    at org.dita.dost.invoker.Main.startAnt(Main.java:488)
[check-lang]    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
[check-lang]    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Error: The following error occurred while executing this line:
C:\Program Files\dita-ot-3.1.3\plugins\org.dita.htmlhelp\build_dita2htmlhelp.xml:110: java.lang.IllegalArgumentException: Unsupported language code '${htmlhelp.locale}', unable to map to a Locale ID.
```

## Environment

* DITA-OT version 3.1.3
* Operating system and version:
  _Windows 7 x64 Professional Service Pack 1_
* How did you run DITA-OT?
  _`dita` command_
* Transformation type:
  _htmlhelp_
* HTML Help Workshop:
  _4.74.8702.0_

**Comment by robander** [comment]
I reproduced this with `htmlhelp` output by adding ä to a map name. PDF and HTML5 both build correctly.
