### ISSUE TITLE
keyref in mapref can not access key when both are defined in a keyscope

### ISSUE THREAD

**Issue by caotrem** [dita-ot/dita-ot#3192]
## Expected Behavior
The root.ditamap defines keys with hrefs to the `featureXX.dita` files. Then maprefs reference a `template_xxxxx_feature.ditamap` in which the keys shall be used to set the href of the included topicrefs. Since the `template_xxxxx_feature.ditamap` files can be referenced multiple times, with different values for the same keynames topicgroups around the keydef and mapref define a keyscope. See "Steps to reproduce" for example files.

Expected output behavior without keyscopes (first occurance of key "feature" counts so Feature 2.1 shows twice)
![image](https://user-images.githubusercontent.com/47040897/51771558-ae954e00-20e9-11e9-9c49-740031f9bc30.png)

Expected output behaviour with keyscopes set to prevent double keydef in same scope
![image](https://user-images.githubusercontent.com/47040897/51771543-99b8ba80-20e9-11e9-86fa-03e81ca37ef4.png)

## Actual Behavior
None of the topics get referenced in the output when keyscopes are defined
![image](https://user-images.githubusercontent.com/47040897/51771581-be149700-20e9-11e9-989a-bd968d26df6e.png)

## Possible Solution

The Open Toolkit should support the behaviour correctly as defined in the specification:

_"...Map authors define the boundaries for key scopes by specifying the `@keyscope` attribute on `<map>` elements, `<topicref>` elements, or elements that are specializations of `<map>` or `<topicref>`. Such elements, their contents, and any locally-scoped content referenced from within the element, are considered to be part of the scope...."_
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/attributes/the-key-scope-attribute.html#keyscope-attribute

The example in the linked spec shows how keyscopes are defined in topicgroups. The mapref is a specialisation of topicref and a child in the keyscope defined by the group. Thus the referenced map should be able to us the keys defined in the keyscope.

## Steps to Reproduce
[example.zip](https://github.com/dita-ot/dita-ot/files/2797759/example.zip)

## Environment

* DITA-OT version: Tested with dita-ot-3.2.1 and dita-ot-2.5.4
* Operating system and version:
Windows 10 
![image](https://user-images.githubusercontent.com/47040897/51772305-f5844300-20eb-11e9-9fa3-042883e0f60a.png)

* How did you run DITA-OT?
dita-ot-3.2.1\bin\dita --input=root.ditamap --format=html5
dita-ot-3.2.1\bin\dita --input=root.ditamap --format=pdf2
dita-ot-2.5.4\bin\dita --input=root.ditamap --format=html5
dita-ot-2.5.4\bin\dita --input=root.ditamap --format=pdf2
* Transformation type:
HTML5
PDF

During PDF generation the following stack trace occurs when the keyscopes are set. Can*t tell if it's relevant or another problem:
```
[fop] [ERROR] Anttask - Error rendering fo file: C:\Users\Caotrem\AppData\Local\Temp\temp20190125215600161\topic.fo <org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)>org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:652)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:671)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:532)
      [fop]     at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:369)
      [fop]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop]     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [fop]     at java.lang.reflect.Method.invoke(Method.java:498)
      [fop]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop]     at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop]     at org.apache.tools.ant.Target.execute(Target.java:448)
      [fop]     at org.apache.tools.ant.Target.performTasks(Target.java:469)
      [fop]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
      [fop]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
      [fop]     at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      [fop]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
      [fop]     at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop]     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [fop]     at java.lang.reflect.Method.invoke(Method.java:498)
      [fop]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop]     at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop]     at org.apache.tools.ant.Target.execute(Target.java:448)
      [fop]     at org.apache.tools.ant.Target.performTasks(Target.java:469)
      [fop]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
      [fop]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
      [fop]     at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      [fop]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
      [fop]     at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop]     at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [fop]     at java.lang.reflect.Method.invoke(Method.java:498)
      [fop]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop]     at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop]     at org.apache.tools.ant.Target.execute(Target.java:448)
      [fop]     at org.apache.tools.ant.Target.performTasks(Target.java:469)
      [fop]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
      [fop]     at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
      [fop]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [fop]     at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      [fop]     at org.dita.dost.invoker.Main.runBuild(Main.java:1102)
      [fop]     at org.dita.dost.invoker.Main.startAnt(Main.java:417)
      [fop]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
      [fop]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
      [fop] Caused by: org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)
      [fop]     at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:296)
      [fop]     at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:648)
      [fop]     ... 45 more
      [fop] Caused by: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)
      [fop]     at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(ContentHandlerProxy.java:555)
      [fop]     at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:416)
      [fop]     at net.sf.saxon.event.NamespaceReducer.endElement(NamespaceReducer.java:228)
      [fop]     at net.sf.saxon.event.ComplexContentOutputter.endElement(ComplexContentOutputter.java:578)
      [fop]     at net.sf.saxon.event.ReceivingContentHandler.endElement(ReceivingContentHandler.java:459)
      [fop]     at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
      [fop]     at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
      [fop]     at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(RelaxNGDefaultsComponent.java:647)
      [fop]     at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
      [fop]     at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
      [fop]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
      [fop]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
      [fop]     at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop]     at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:111)
      [fop]     at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop]     at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
      [fop]     at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
      [fop]     at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
      [fop]     at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
      [fop]     at net.sf.saxon.event.Sender.send(Sender.java:138)
      [fop]     at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:383)
      [fop]     at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:293)
      [fop]     ... 47 more
      [fop] Caused by: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (Siehe Position 1:10717)
      [fop]     at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
      [fop]     at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
      [fop]     at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
      [fop]     at com.sun.proxy.$Proxy3.missingChildElement(Unknown Source)
      [fop]     at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:588)
      [fop]     at org.apache.fop.fo.pagination.Flow.endOfNode(Flow.java:93)
      [fop]     at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:360)
      [fop]     at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
      [fop]     at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:414)
      [fop]     ... 67 more
      [fop]
Error: The following error occurred while executing this line:
C:\dita-ot-3.2.1\plugins\org.dita.pdf2.fop\build_fop.xml:155: [PDFX013F][FATAL] The PDF file 'C:\Demo_006\.\out/root.pdf' could not be generated.
```

**Comment by raducoravu** [comment]
@jelovirt From what I tested this issue seems to have been fixed by: https://github.com/dita-ot/dita-ot/pull/3141, right?

**Comment by caotrem** [comment]
Hey jelovirt, thanks for investigating. Didn't make a connection to this during research. Sounds like it is the same problem like what I am facing.

I tested with the latest snapschot: dita-ot-3.3.0-SNAPSHOT+07cf66a but the result is still empty. I have no build environment setup for dita. So I can't test it with the latest commits.

**Comment by jelovirt** [comment]
Works in 3.5.4. Closing.
