### ISSUE TITLE
NullPointerException in LinkFilter

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3205]
We have an user's guide with about 2000 topics, when publishing it to CHM using DITA OT 3.2.1 we get this error which breaks the publishing:

    D:\projects\eXml\frameworks\dita\DITA-OT3.x\build.xml:46: The following error occurred while executing this line:
    D:\projects\eXml\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:417: java.lang.NullPointerException
	at org.dita.dost.util.URLUtils.getRelativePath(URLUtils.java:602)
	at org.dita.dost.writer.LinkFilter.getHref(LinkFilter.java:83)
	at org.dita.dost.writer.LinkFilter.startElement(LinkFilter.java:48)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startElement(RelaxNGDefaultsComponent.java:200)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:271)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1655)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:149)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
	at net.sf.saxon.event.Sender.send(Sender.java:138)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:383)
	at org.dita.dost.util.XMLUtils.transformURI(XMLUtils.java:515)
	at org.dita.dost.util.XMLUtils.transform(XMLUtils.java:487)
	at org.dita.dost.module.CleanPreprocessModule.execute(CleanPreprocessModule.java:82)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:448)
	at org.apache.tools.ant.Target.performTasks(Target.java:469)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)

The core of the problem seems to be that in ".job.xml" there is this entry:

    <file uri="fc11bb033139e3430cf270183e7baa3287740a52.dita"
      path="fc11bb033139e3430cf270183e7baa3287740a52.dita" format="dita"/>

which lacks the "result" attribute on it. This makes various stages which interpret the ".job.xml" like LinkFilter and even CleanPreprocessModule fail further one:

    D:\projects\eXml\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:417: java.lang.NullPointerException
	at java.net.URI.relativize(Unknown Source)
	at java.net.URI.relativize(Unknown Source)
	at org.dita.dost.module.CleanPreprocessModule.execute(CleanPreprocessModule.java:71)

**Comment by raducoravu** [comment]
Somewhere in the DITA Map it seems that on a topicref I used a keyref with a copy-to. I will try to produce a small sample project.

**Comment by raducoravu** [comment]
I'm having trouble reproducing this on a smaller project. If anybody wants to debug this on the larger project I can provide a download link in private.
Also, even without the sample project the .job.xml should probably never contain a "file" entry without a "result" attribute. Instead some kind of warning should be issued when the .job.xml is written and the entry should not be written at all.

**Comment by raducoravu** [comment]
Using for CHM output "preprocess" instead of "preprocess2" seems to fix the NPE but it still reports more broken links for the same project than DITA OT 2.x.
