### ISSUE TITLE
NullPointerException in AbstractDitaMetaWriter

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3226]
A DITA Map referenced with "processing-role='resource-only'" which in turn references a DITA concept with "chunk='to-content'".
Publish the uploaded project to HTML5 with DITA OT 3.2.1:

[npeDitaMetaWriter.zip](https://github.com/dita-ot/dita-ot/files/2880270/npeDitaMetaWriter.zip)

you get a NullPointerException:

     [move-meta] Processing file:/C:/Users/radu_coravu/Desktop/lorem_ipsum/__uk_interest_rate_specific_position_risk/temp/html5/oxygen_dita_temp/gdm/co_cde_df_ext_rating.dita
     BUILD FAILED
     D:\projects\eXml\frameworks\dita\DITA-OT3.x\build.xml:46: The following error occurred while executing this line:
     D:\projects\eXml\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:203: java.lang.NullPointerException
	at org.dita.dost.writer.AbstractDitaMetaWriter.getFirstChildElement(AbstractDitaMetaWriter.java:157)
	at org.dita.dost.writer.AbstractDitaMetaWriter.findMetadataContainer(AbstractDitaMetaWriter.java:134)
	at org.dita.dost.writer.DitaMetaWriter.process(DitaMetaWriter.java:73)
	at org.dita.dost.writer.AbstractDomFilter.read(AbstractDomFilter.java:55)
	at org.dita.dost.module.MoveMetaModule.pushMetadata(MoveMetaModule.java:190)
	at org.dita.dost.module.MoveMetaModule.execute(MoveMetaModule.java:64)

**Comment by robander** [comment]
Reproduced in 3.3.4 building `test1.ditamap` to HTML5.

**Comment by raducoravu** [comment]
I can confirm the NPE can no longer be reproduced with the latest DITA OT code, possibly it was fixed as a side effect.
