### ISSUE TITLE
NullPointerException in JobMapper

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3270]
Using DITA OT 3.2.1 with HTML5-based publishing:

    C:\Program Files\Oxygen XML Editor 21\frameworks\dita\DITA-OT3.x\build.xml:46: The following error occurred while executing this line:
    C:\Program Files\Oxygen XML Editor 21\frameworks\dita\DITA-OT3.x\plugins\com.oxygenxml.webhelp.responsive\build_dita.xml:919: java.lang.NullPointerException
	at org.dita.dost.ant.types.JobMapper.mapFileName(JobMapper.java:83)
	at org.dita.dost.module.XsltModule.execute(XsltModule.java:123)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.util.Vector.forEach(Unknown Source)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)

I don't have a sample project to reproduce things right now but if I get one I'll post it here.

**Comment by raducoravu** [comment]
I'm marking this as a duplicate of #2844 because it probably is. Plus there are no samples to reproduce the problem.
