### ISSUE TITLE
More details about failure in CleanPreprocessModule

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3274]
One of our clients is experiencing this DITA OT failure:

     C:\PATH\TO\DITA-OT\plugins\org.dita.base\build_preprocess.xml:417: java.lang.IllegalArgumentException: Argument schemes do not match
	at org.dita.dost.module.CleanPreprocessModule.getCommonBase(CleanPreprocessModule.java:146)
	at org.dita.dost.module.CleanPreprocessModule.getBaseDir(CleanPreprocessModule.java:135)
	at org.dita.dost.module.CleanPreprocessModule.execute(CleanPreprocessModule.java:59)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)

Maybe that particular exception would be more helpful if it mentioned the two URIs for which the schemes do not match. Also maybe this NPE could be fixed as well #2869

**Comment by raducoravu** [comment]
Somehow our client has a simple quote in the file name "What's New.dita" and there is already an issue added for this: #2844. I can still reproduce the stack trace in #2844 but I cannot reproduce on my machine the "IllegalArgumentException" in the "CleanPreprocessModule". But anyway the message of the exception should be more helpful.

**Comment by raducoravu** [comment]
Somehow our client has a simple quote in the file name "What's New.dita" and there is already an issue added for this: #2844. I can still reproduce the stack trace in #2844 but I cannot reproduce on my machine the "IllegalArgumentException" in the "CleanPreprocessModule". But anyway the message of the exception should be more helpful.

**Comment by android606** [comment]
I'd like to mention that I got this same error message because I had an xref to an external URL with a scope attribute set to "local".  This type of error would be much easier to track down if the error message included the URL.
