### ISSUE TITLE
Cannot run publishing using a licensed Saxon 9.9 distribution

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3383]
The following unhandled exception thrown by Saxon is received in the command line:

       DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:260: java.lang.IllegalStateException: XsltController#setMessageEmitter() is not supported for a configuration that allows multi-threading. Use setMessageFactory() instead
	at net.sf.saxon.trans.XsltController.setMessageEmitter(XsltController.java:431)
	at org.dita.dost.util.XMLUtils.withLogger(XMLUtils.java:79)
	at org.dita.dost.module.MaprefModule.processMap(MaprefModule.java:101)
	at org.dita.dost.module.MaprefModule.execute(MaprefModule.java:76)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:182)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)

**Comment by raducoravu** [comment]
To reproduce this problem you needed to get the Saxon Enterprise Edition JAR libraries from Saxonica and replace the Saxon HE JAR inside the DITA OT with them.
Then you needed to copy a valid "saxon-licence.lic" in the DITA OT "lib" folder.
Then run the HTML5 transformation.
