### ISSUE TITLE
Treatment for UncheckedXPathException exceptions

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3395]
I'm converting a DITA topic to Word using the "com.elovirta.ooxml" plugin.
The transformation fails with:

    D:\projects\eXml\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build.xml:29: The following error occurred while executing this line:
    D:\projects\eXml\frameworks\dita\DITA-OT3.x\plugins\com.elovirta.ooxml\build.xml:72: net.sf.saxon.trans.UncheckedXPathException: Supplied element name is a zero-length string
	at net.sf.saxon.lib.DelegatingErrorListener.fatalError(DelegatingErrorListener.java:51)
	at net.sf.saxon.Controller.reportFatalError(Controller.java:466)
	at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:775)
	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
	at org.dita.dost.module.TopicMergeModule.execute(TopicMergeModule.java:99)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:182)

We need to somehow individually catch such "UncheckedXPathException " exceptions and display instead their inner "net.sf.saxon.trans.UncheckedXPathException.getXPathException()" which probably has line and column information missing in the wrapper runtime exception.

**Comment by raducoravu** [comment]
Added also an issue on the Saxonica list related to unchecked exceptions:
https://saxonica.plan.io/issues/4364

**Comment by raducoravu** [comment]
The HTML5 output works but it has its quirks, the output folder contains both an "index.html" which is the actual topic with all keyrefs and conkeyrefs expanded (but which has a broken reference to the image file). There is also an HTML equivalent of the original topic in a "topics" subfolder and in this case the image reference is properly resolved.

**Comment by raducoravu** [comment]
Also I've been having problems obtaining plain PDF output from a simple DITA Map, something like:

          dita -i D:\projects\eXml\samples\dita\flowers\flowers.ditamap -f pdf -o "d:\outputTest3" -t "d:\abcTMP3"  -d -v

no longer works on a DITA Map which has a plain topic referenced in it, I get a "topic.fo" which is invalid, contains nothing in the "xsl-region-body" flow:

          [fop] [ERROR] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10681)
      [fop] [ERROR] Anttask - Error rendering fo file: d:\abcTMP3\topic.fo <org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10681)

**Comment by raducoravu** [comment]
I consider this fixed in: https://github.com/dita-ot/dita-ot/commit/27ae24fa735ecbfa001dea027d21d6981d43d829
