### ISSUE TITLE
Cannot convert DITA to HTML using the Java API

### ISSUE THREAD

**Issue by boudhayan-dev** [dita-ot/dita-ot#3487]
## Expected Behavior
I have tried to convert a DITA doc to HTML using the CLI . It works fine.
```
dita --input=sequence.ditamap --format=html5 \
     --output=output/sequence \
     --args.input.dir=/absolute/path/to/dita-ot-dir/docsrc/samples \
     --propertyfile=properties/sequence-html5.properties
```
Now, I tried to do the same using Java API but it is throwing an error. 

## Actual Behavior
The following error is shown - 

```
Failed to read print transtypes from configuration, using defaults.
Failed to read transtypes from configuration, using empty list.
Exception in thread "main" java.lang.IllegalArgumentException: Transtype html5 not supported
	at org.dita.dost.ProcessorFactory.newProcessor(ProcessorFactory.java:58)
	at cias.dita.Main.main(Main.java:19)
```

## Steps to Reproduce

1. Created a Maven project with the following dependency -

```
        <dependency>
	  <groupId>org.dita-ot</groupId>
	  <artifactId>dost</artifactId>
	  <version>3.4.1</version>
	</dependency>
```
2. Code -

	```
public static void main(String[] args) {
		
		
		ProcessorFactory pf = ProcessorFactory.newInstance(new File("C:\\Users\\Desktop\\dita-ot-3.4.1"));
		pf.setBaseTempDir(new File("C:\\Users\\Desktop\\temp"));
		
		
		Processor ditaProcessor = pf.newProcessor("html5")
				.setInput(new File("C:\\Users\\Desktop\\dita-ot-3.4.1\\docsrc\\samples\\sequence.ditamap"))
				.setOutputDir(new File("C:\\Users\\Desktop\\dita-ot-3.4.1\\docsrc\\samples\\output"))
				.setProperty("nav-toc", "partial")
				.createDebugLog(true);

			try {
				ditaProcessor.run();
			} catch (DITAOTException e) {
				e.printStackTrace();
			}
	}
```

## Copy of the error message, log file or stack trace

```
Failed to read print transtypes from configuration, using defaults.
Failed to read transtypes from configuration, using empty list.
Exception in thread "main" java.lang.IllegalArgumentException: Transtype html5 not supported
	at org.dita.dost.ProcessorFactory.newProcessor(ProcessorFactory.java:58)
	at cias.dita.Main.main(Main.java:19)
```

## Environment

* DITA-OT version: 3.4.1
* Operating system and version: Windows 10
* How did you run DITA-OT? - Java API
* Transformation type: html5

**Comment by jelovirt** [comment]
Is your classpath correctly set up? You need everything in `lib` directory, `config` directory, and all libraries plug-ins contribute. See `config/env.sh` for a list of libraries that plug-ins have configured.

**Comment by raducoravu** [comment]
Similar to: https://github.com/dita-ot/dita-ot/issues/3647

**Comment by digiman999** [comment]
I've spend a day trying to achieve the same as @boudhayan-dev, but with his same results.  My setup is:

Intellij 2019.2.4
Gradle Wrapper 5.6   
Java 11
Dita OT 3.4.1, in /opt/dita-ot-3.4.1
Gradle Dependency org.dita-ot:dost:3.6.1

@jelovirt mentioned to add the DITA installations lib & plugins directories to the classpath.  Adding this:

`compile fileTree(dir: "/opt/dita-ot-3.4.1/lib/", include: "*.jar")`

to Gradle's build.gradle results in the Java module system error from multiple JARs having the same dependencies:

`the unnamed module reads package org.slf4j from both slf4j.api and org.slf4j`

Gradle doesn't allow excluding dependencies for fileTree dependencies, the DITA-OT lib directory doesn't seem to be available separately on MavenCentral and manually adding each dependency isn't a practical option, so it's made me question if we're doing things right at all.  Is the DOST JAR meant to be used this way, or should we be calling the /opt/dita-ot-3.4.1/bin/dita shell script using Java's ProcessBuilder/etc?  I was hoping to integrate an API like DOST into my application, and I'm not the best with Gradle, but I'm struggling here and something doesn't seem right.
