### ISSUE TITLE
NullPointerException when running DITA OT project file without specifying output.dir

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3526]
I reproduced this with a DITA OT 3.5.1 installation, this did not happen in 3.4.2.
A simple DITA OT project file is run without specifying the "-o" parameter in the command line:

    dist:
     [exec] Searching for integrator.xml ...
     [exec] java.lang.NullPointerException
     [exec] 	at org.dita.dost.invoker.Main.lambda$handleProject$3(Main.java:397)
     [exec] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
     [exec] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
     [exec] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
     [exec] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
     [exec] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
     [exec] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
     [exec] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     [exec] 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
     [exec] 	at org.dita.dost.invoker.Main.handleProject(Main.java:443)
     [exec] 	at org.dita.dost.invoker.Main.processArgs(Main.java:342)
     [exec] 	at org.dita.dost.invoker.Main.startAnt(Main.java:160)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.dita.dost.invoker.MainWithCPWildcardExpansion.startAnt(MainWithCPWildcardExpansion.java:64)
     [exec] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
     [exec] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

**Comment by raducoravu** [comment]
👍 Somebody else reported this problem on the DITA Users List: https://dita-users.groups.io/g/main/message/45518
