### ISSUE TITLE
Chunk="to-content" generates java.lang.NullPointerException error message

### ISSUE THREAD

**Issue by PieterjanVandenweghe** [dita-ot/dita-ot#3533]
See attached sample BOOKMAP
[__chunk_to_content.zip](https://github.com/dita-ot/dita-ot/files/4764407/__chunk_to_content.zip)

In attached you find a bookmap with a chapter ditamap containing a couple of topics.
All topics have unique @keys added in the topicref.
Chunk="to-content" is added in the first topic of the DITAMAP.

## Expected Behavior
Generate output with chunked="to-content" topics in webhelp.

## Actual Behavior
When I publish this BOOKMAP, I get the following error message: Generates java.lang.NullPointerException

Keys attribute seems to cause this issue.
When I remove all keys, I can publish without problems.

## Steps to Reproduce

1. Create a BOOKMAP with a DITAMAP added as chapter and add key. 
It's importat you add a DITAMAP as chapter, not a topic. There is not bug when the chapter references to a DITA file.
2. In the DITAMAP, add a topic with a couple of child topics.
3. Add a key to all topics.
4. Add the attribute @chunk="to-content" to the first topic in the DITAMAP
5. Try to generate a OxygenXML webhelp or PDF

## Environment

* DITA-OT version: 3.4.1 (OxygenXML 22.1)
* Operating system and version: Windows
* How did you run DITA-OT? OxygenXML
* Transformation type: Miramo PDF, OxygenWebhelp

**Comment by raducoravu** [comment]
@PieterjanVandenweghe  can you download a standard DITA OT 3.5.1 distribution without any Oxygen plugins installed and try to publish from the command line to html5 using the flag "-d" to add extra debug? Does it fail the same? If so, at the end of the console output there should be the stack trace of the NullPointerException, maybe you can add it to the issue.

**Comment by PieterjanVandenweghe** [comment]
Just tried it with a new version of DITA-OT 3.5.1 without Oxygen plugins but with the same result.
Please find the complete info file here: [build-info.txt](https://github.com/dita-ot/dita-ot/files/4765068/build-info.txt)

**Comment by raducoravu** [comment]
I can also reproduce the problem, attaching here the NullPointerException stack trace:

    java.lang.NullPointerException
	at org.dita.dost.writer.AbstractDitaMetaWriter.getFirstChildElement(AbstractDitaMetaWriter.java:158)
	at org.dita.dost.writer.AbstractDitaMetaWriter.findMetadataContainer(AbstractDitaMetaWriter.java:135)
	at org.dita.dost.writer.DitaMetaWriter.process(DitaMetaWriter.java:74)
	at org.dita.dost.writer.AbstractDomFilter.read(AbstractDomFilter.java:46)
	at org.dita.dost.module.MoveMetaModule.pushMetadata(MoveMetaModule.java:189)
	at org.dita.dost.module.MoveMetaModule.execute(MoveMetaModule.java:67)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:190)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by raducoravu** [comment]
Probably because of some chunking bug the method "org.dita.dost.writer.AbstractDitaMetaWriter.getMatchingTopicElement(Element)" returns null and then this leads to the NPE further on.
