### ISSUE TITLE
Unhandled java error: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hestonhoffman** [dita-ot/dita-ot#3566]
## Expected Behavior

I expect the toolkit to rescue this Java error and return a DITA-OT error telling me that the file could not be transformed. The DITA build should either continue without this file, or exit at this point.

The issue I came across is that this failed silently in our build pipeline and ended up uploading an empty folder. 

Admittedly, the file that's causing the issue is a total mess. Cleaning up the many DITA validation warnings in the file solved the issue. I've attached a map with the original file and a fixed version. Because there are so many issues with the file, it was difficult to ascertain which of the issues is causing the java error. Our previous pipeline used 3.3.3 and did not produce the error.

## Actual Behavior
Running this map with a clean version of 3.5.3 (no plugins) causes a java error:
```
Error: java.lang.IndexOutOfBoundsException: Index 3 out-of-bounds for length 3
``` 
The build exits with a 0, so if I'm running multiple builds in a script, there is no indication that it failed without consulting the DITA log.

## Steps to Reproduce

1. Unzip the attached archive
2. Run an HTML transformation on the file: `path/to/dita -i test.ditamap -o html -f html5 -d`

* DITA-OT version: 3.5.3
* Operating system and version: MacOS 10.15.6
* How did you run DITA-OT? `path/to/dita -i test.ditamap -o html -f html5 -d`

Attachement: [java_error.zip](https://github.com/dita-ot/dita-ot/files/5152581/java_error.zip)

**Comment by raducoravu** [comment]
The stack trace of the error:


      /Users/..../dita-ot-3.5.3/plugins/org.dita.base/build_preprocess.xml:194: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.dita.dost.writer.NormalizeTableFilter.processEntry(NormalizeTableFilter.java:151)
	at org.dita.dost.writer.NormalizeTableFilter.startElement(NormalizeTableFilter.java:131)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at org.dita.dost.writer.TopicFragmentFilter.startElement(TopicFragmentFilter.java:79)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:227)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1655)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)

**Comment by raducoravu** [comment]
@jelovirt  looks like a side effect of this commit about 2 months ago: https://github.com/dita-ot/dita-ot/commit/763d8e461444b415efaded3bdf00197f65b87e8a

**Comment by raducoravu** [comment]
With my local DITA OT 3.5.1 I cannot reproduce the problem.
