### ISSUE TITLE
UncheckedXPathException: An empty sequence is not allowed as the value of variable $l

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3587]
If I publish to HTML5 the referenced sample project I get an error which breaks the publishing:

     /Users/raducoravu/.../plugins/org.dita.html5/build_dita2html5.xml:212: net.sf.saxon.trans.UncheckedXPathException: An empty sequence is not allowed as the value of variable $l
	at net.sf.saxon.lib.DelegatingErrorListener.fatalError(DelegatingErrorListener.java:51)
	at net.sf.saxon.Controller.reportFatalError(Controller.java:466)
	at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:775)
	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
	at org.dita.dost.module.XsltModule.transform(XsltModule.java:187)

[chunk-lang-pb.zip](https://github.com/dita-ot/dita-ot/files/5238114/chunk-lang-pb.zip)

The cause for this seems to be a chunk="to-content" set on a topic which has no child topics:

     <topicref href="topic.dita" keys="test" chunk="to-content"/>

**Comment by raducoravu** [comment]
The error is in "plugins/org.dita.base/xsl/common/dita-utilities.xsl" at line:

    <xsl:variable name="l" select="tokenize($lang, '-')[1]" as="xs:string"/>

**Comment by raducoravu** [comment]
The DITA OT ends up creating in the temp folder a topic.dita which is an empty composite and looks like this:

    <?xml version="1.0" encoding="utf-8"?><?workdir /Users/raducoravu/Desktop/..en/temp/html5/?><?workdir-uri file:/Users/raducoravu/../html5/oxygen_dita_temp/?><?path2rootmap-uri ./?><?path2project?><?path2project-uri ./?><dita xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" ditaarch:DITAArchVersion="1.3"/>

so when the "get-render-direction" applies on it, if finds no inner topic from which to obtain the lang attribute.
