### ISSUE TITLE
Unhandled error in image metadata reader breaks entire processing

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3604]
Attaching the stack trace someone obtains when the image metadata reader attempts to read the metadata for a JPEG image:

     \plugins\org.dita.html5\build_dita2html5.xml:108: java.lang.ArrayIndexOutOfBoundsException
	at com.sun.imageio.plugins.jpeg.JPEGBuffer.loadBuf(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGBuffer.scanForFF(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(Unknown Source)
	at org.dita.dost.writer.ImageMetadataFilter.readBitmapMetadata(ImageMetadataFilter.java:209)
	at org.dita.dost.writer.ImageMetadataFilter.readMetadata(ImageMetadataFilter.java:177)
	at java.util.HashMap.computeIfAbsent(Unknown Source)
	at org.dita.dost.writer.ImageMetadataFilter.startElement(ImageMetadataFilter.java:116)

Because the ImageMetadataFilter throws outside any runtime exception, this error also breaks the publishing process.

**Comment by qualler** [comment]
@jelovirt - from your request I attached an example of an image that breaks publishing. I used a map with one topic that points to this image and the job failed. 

If there's a way to skip this error and continue processing that would be helpful as I do not have a good way to find these images. Thanks for looking at this!
![2515366](https://user-images.githubusercontent.com/11465805/96613080-25ae4500-12c4-11eb-914a-7dbdc0772bc9.jpg)
