### ISSUE TITLE
NPE at org.dita.dost.Processor.run(Processor.java:228)

### ISSUE THREAD

**Issue by zosrothko** [dita-ot/dita-ot#3667]
## Expected Behavior
No NPE throws

## Actual Behavior
NPE at org.dita.dost.Processor.run(Processor.java:228)

## Steps to Reproduce
This is the calling Processor.run() method generate(String transtype) that is called within a WalkTree processing. When the` processor.cleanOnFailure` is set to `false`, no NPE is throwed.

```
	public void generate(String transtype) throws DITAOTException {
		outDir = new File(outDir, transtype);
		ProcessorFactory processorFactory = ProcessorFactory.newInstance(ditaDir.getAbsoluteFile());
		processorFactory.setBaseTempDir(tempDir.getAbsoluteFile());
		
		// Create a processor using the factory and configure the processor
		Processor processor = processorFactory.newProcessor(transtype)
		.setInput(mapFile.getAbsoluteFile())
		.setOutputDir(outDir.getAbsoluteFile());

		processor.createDebugLog(false);
		processor.cleanOnFailure(true);
		processor.setProperty("validate", "false");
		processor.run();
	}
```

## Copy of the error message, log file or stack trace
```
Exception in thread "main" java.lang.NullPointerException
	at org.dita.dost.Processor.run(Processor.java:228)
	at com.scort.mi.dita.mojo.Dita.generate(Dita.java:38)
	at com.scort.mi.dita.mojo.DitaWalker.preVisitDirectory(DitaWalker.java:46)
	at com.scort.mi.dita.mojo.DitaWalker.preVisitDirectory(DitaWalker.java:1)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.scort.mi.dita.mojo.Main.main(Main.java:27)

```
## Environment
* DITA-OT version: 3.6
* Operating system and version: Windows 10 Pro
* How did you run DITA-OT? Java API call
* Transformation type: pdf2

**Comment by jelovirt** [comment]
Logger hasn't been set. Add fallback for it.
