### ISSUE TITLE
IndexOutOfBoundsException in NormalizeSimpleTableFilter

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3679]
One of our clients has this error break the publishing engine with DITA OT 3.5.4:

    BUILD FAILED
    C:\Program Files\Oxygen XML Editor 23\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build.xml:29: The following     error occurred while executing this line:
    C:\Program Files\Oxygen XML Editor 23\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:194: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.dita.dost.writer.NormalizeSimpleTableFilter.processEntry(NormalizeSimpleTableFilter.java:103)
	at org.dita.dost.writer.NormalizeSimpleTableFilter.startElement(NormalizeSimpleTableFilter.java:92)
	at org.dita.dost.writer.NormalizeTableFilter.startElement(NormalizeTableFilter.java:137)

the line of code there is something like: 

            for (prev = tableState.previousRow.get(tableState.currentColumn); prev != null && prev.y > 1; prev = tableState.previousRow.get(tableState.currentColumn)) {

Maybe as a failsafe, the method "org.dita.dost.writer.NormalizeSimpleTableFilter.startElement(String, String, String, Attributes)" could catch a runtimeexception and log it as an error in the build but avoid breaking the entire build because a table has invalid structure.

**Comment by jelovirt** [comment]
It should not catch `RuntimeException` because that's a sign of programmer error. Instead the code should check for the error condition and handle it so that the exception is not thrown.

Needs to be reproduced with 3.6.

**Comment by jelovirt** [comment]
@raducoravu Could we also get the source that caused this?

**Comment by raducoravu** [comment]
@jelovirt I'm working on it

**Comment by raducoravu** [comment]
[iobeTableFilter.zip](https://github.com/dita-ot/dita-ot/files/5808218/iobeTableFilter.zip)

Attached the sample project, end user seems to be using a learning and training element which derives from a DITA simple table.

**Comment by swebb2066** [comment]
Attached is a very simple example dita map showing the IndexOutOfBoundsException fault using dita-ot-3.6.1 (see dita-ot-3.6.1.log).

The same project does not produce the fault when using dita-ot-3.3.2 (see dita-ot-3.3.log).
[IndexOutOfBoundsException.zip](https://github.com/dita-ot/dita-ot/files/7207916/IndexOutOfBoundsException.zip)
