### ISSUE TITLE
Capitalization change during debug-filter pre-processing probably causes infinite loop in map-ref

### ISSUE THREAD

**Issue by ckab74** [dita-ot/dita-ot#3734]
## Expected Behavior
Capitalization change should not happen.

## Actual Behavior
During the [debug-filter] pre-processing, we found that all file path names are renamed with an error message.
Example:
[DOTJ083E][ERROR] The resource referenced as file:/d:/P1/re/276570932/b/projects/en/sample_project/trans_picts/play_mode/play_mode_midi_instance.png is capitalized differently on disk, using file:/**D**:/P1/re/276570932/b/projects/en/sample_project/trans_picts/play_mode/play_mode_midi_instance.png.

This only happens on our Windows integration server with a standard Windows installation when our custom Ant build script is run. The developer who is responsible for this server has also tested on his own Windows client and had the same issue. 
It does not happen on my client and also not on my team member's client. We both use Windows installations.

When this pre-processing step is done, in the [map-ref] pre-processing step, all maps that contain submaps show another error, which, we hope, is based on the capitalization issue.
Example:
[mapref] file:/d:/P1/re/278659705/b/projects/en/sample_project.ditamap:78:78: [DOTX053E][ERROR]: A element that references another map indirectly includes itself, which results in an infinite loop. The original map reference is to 'sample_project.ditamap'.

These error messages run in an infinite loop until the build terminates with a failure message. 

## Possible Solution
We have no idea how to fix this. This started with DITA OT 3.6. The project is running smoothly with DITA OT 3.5.4.
We don't know why a capitalization of the drive takes place. Could this be related to the #3535 issue?

## Steps to Reproduce
We cannot reproduce this as we don't know what's happening. It looks like renaming the drive letter manually with Total Commander could reproduce this issue, but not always. I don't have this error, so it wouldn't change a thing.

## Copy of the error message, log file or stack trace
The log file size is around 360 MB, and it loads forever in the browser, so I can't attach this here. Please let me know if you need anything specific from that log file apart from the error messages that I added above.

## Environment
* DITA-OT version: DITA OT 3.6 using RNG schema, our customized plug-ins, and Oxygen plug-ins.
* Operating system and version: Windows Server running Windows 10
* How did you run DITA-OT? We run DITA with ANT called by a Ruby script needed to run builds on that server.
* Transformation type: our own, based on pdf; webhelp-responsive.

I will send test files directly to you when you start looking into this.

**Comment by raducoravu** [comment]
How does the command line used to start the DITA OT look like exactly?
Maybe if it contains absolute paths to the input, temp and output folder a workaround is to capitalize the D: drive when that full path is passed to the dita command.

**Comment by ckab74** [comment]
Hi Radu,
In the build server script, the ant call is as follows:
call = "ant -f \"#{@buildpdfxml}\" -l \"#{logfile}\" -v -Dinput=\"#{ditamap}\" -Doutdir=\"#{out_put}\" -Dditadir=\"#{@dita_dir}\" #{@pdf_parameters.to_s} smtg.pdf"
temp is not generated. I don't see any absolute paths being added to the variables in that script.
I can actually simulate the server build on my machine - using the same script, but I don't get the errors.

**Comment by raducoravu** [comment]
It depends on where parameters like "#{ditamap}" are computed and passed on the build server.
Also as a side note you should consider moving to the new way of running the DITA OT using the "dita" command: https://www.dita-ot.org/dev/topics/build-using-dita-command.html

**Comment by ckab74** [comment]
I've got back to the build server developer and he told me that an absolute path is passed, but with a small letter d:
DitaMap: d:\P1\re\278661375\b\projects\en\sample_project\sample_project.ditamap
So the capitalization of that d: seems to be taking place during the pre-processing.

**Comment by raducoravu** [comment]
And if they pass the reference like this:

    D:\P1\re\278661375\b\projects\en\sample_project\sample_project.ditamap

do you still have problems?

**Comment by ckab74** [comment]
A capital D doesn't cause the issue.
But shouldn't we be able to pass the path with a small d? It still sounds more like a DITA OT bug to me.

**Comment by raducoravu** [comment]
I agree, the DITA OT tries to help with problems when references between resources in the DITA project have incorrect path capitalization, Probably the DITA OT should check the path capitalization problems after making all URI references relative to the base project folder or something..

**Comment by jelovirt** [comment]
One challenge here is that none of the core developer have a Windows machine.

**Comment by ckab74** [comment]
We would be happy to help testing.

**Comment by rcdmsw** [comment]
I've seen this issue too and would be happy to help test. Has there been any progress?

In my case:

# Expected behaviour

Upon adopting 3.6.1 (from 3.4), I do not see any capitalization changes; all references resolve correctly

# Actual behaviour

PDF and XHTML builds invoked via the Windows command prompt (cmd) suffer capitalization errors  when loading .dita resources. No individual .dita files render, but PDF builds produce a PDF file (with a front page and no content). XHTML builds produce an index.html and .html files, where the TOC entries in the index.html point to the ditamap itself.

Capitalization error from the PDF:

```
[filter] file:/c:/code/docs-prototype/dita_content/Ditamaps/Glossary.ditamap:25:106: [DOTJ083E][ERROR] The resource referenced as file:/c:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/GlossaryF.dita is capitalized differently on disk, using file:/C:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/GlossaryF.dita.
```

Error for the XHTML build  (where we have incorrect references to the .ditamap itself in the ToC). I've trimmed duplicate errors:

```
[filter] file:/c:/code/docs-prototype/dita_content/Ditamaps/Glossary.ditamap:45:106: [DOTJ083E][ERROR] The resource referenced as file:/c:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/GlossaryZ.dita is capitalized differently on disk, using file:/C:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/GlossaryZ.dita.
...
[filter] file:/c:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/GlossaryM.dita:143:73: [DOTJ083E][ERROR] The resource referenced as file:/c:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/GlossaryA.dita is capitalized differently on disk, using file:/C:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/GlossaryA.dita.
...
[move-meta] file:/c:/code/docs-prototype/dita_content/Ditamaps/Glossary.ditamap:45:106: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'Glossary.ditamap'.
...
 pipeline] file:/c:/code/docs-prototype/dita_content/Ditamaps/Glossary.ditamap:45:106: [DOTX009W][WARN]: Could not retrieve a title from 'Glossary.ditamap'. Using 'Glossary.ditamap' instead.
```

Mapref resolution also fails, preceded by capitalization errors. This causes a PDF build to fail entirely.

```
[c:\code\docs-prototype>dita -i dita_content\Ditamaps\SystemOverview.ditamap -f pdf
[map-reader] file:/c:/code/docs-prototype/dita_content/Ditamaps/SystemOverview.ditamap:58:69: [DOTJ083E][ERROR] The resource referenced as file:/c:/code/docs-prototype/dita_content/Ditamaps/SystemOverviewShared.ditamap is capitalized differently on disk, using file:/C:/code/docs-prototype/dita_content/Ditamaps/SystemOverviewShared.ditamap.
   [mapref] file:/c:/code/docs-prototype/dita_content/Ditamaps/SystemOverview.ditamap:58:69: [DOTX053E][ERROR]: A element that references another map indirectly includes itself, which results in an infinite loop. The original map reference is to '0578d81ec6ae3eb516be27f4dc54c9aa3f41d01b.ditamap'.
   [mapref] file:/c:/code/docs-prototype/dita_content/Ditamaps/SystemOverview.ditamap:58:69: [DOTX053E][ERROR]: A element that references another map indirectly includes itself, which results in an infinite loop. The original map reference is to '0578d81ec6ae3eb516be27f4dc54c9aa3f41d01b.ditamap'.
      [fop] [ERROR] Anttask - Error rendering fo file: C:\Users\rdunstan\AppData\Local\Temp\temp20210721133627898\topic.fo <org.apache.fop.apps.FOPException: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)>org.apache.fop.apps.FOPException: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:652)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:671)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:532)
      [fop]     at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:369)
      [fop]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop]     at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [fop]     at java.base/java.lang.reflect.Method.invoke(Method.java:567)
      [fop]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
      [fop]     at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop]     at org.apache.tools.ant.Target.execute(Target.java:449)
      [fop]     at org.apache.tools.ant.Target.performTasks(Target.java:470)
      [fop]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
      [fop]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
      [fop]     at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
      [fop]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
      [fop]     at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
      [fop]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop]     at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [fop]     at java.base/java.lang.reflect.Method.invoke(Method.java:567)
      [fop]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
      [fop]     at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop]     at org.apache.tools.ant.Target.execute(Target.java:449)
      [fop]     at org.apache.tools.ant.Target.performTasks(Target.java:470)
      [fop]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
      [fop]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
      [fop]     at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
      [fop]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
      [fop]     at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
      [fop]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop]     at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [fop]     at java.base/java.lang.reflect.Method.invoke(Method.java:567)
      [fop]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
      [fop]     at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop]     at org.apache.tools.ant.Target.execute(Target.java:449)
      [fop]     at org.apache.tools.ant.Target.performTasks(Target.java:470)
      [fop]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
      [fop]     at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
      [fop]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [fop]     at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
      [fop]     at org.dita.dost.invoker.Main.runBuild(Main.java:675)
      [fop]     at org.dita.dost.invoker.Main.startAnt(Main.java:204)
      [fop]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
      [fop]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
      [fop] Caused by: org.apache.fop.apps.FOPException: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)
      [fop]     at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:296)
      [fop]     at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:648)
      [fop]     ... 45 more
      [fop] Caused by: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)
      [fop]     at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(ContentHandlerProxy.java:553)
      [fop]     at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:414)
      [fop]     at net.sf.saxon.event.ProxyReceiver.endElement(ProxyReceiver.java:185)
      [fop]     at net.sf.saxon.event.SequenceNormalizer.endElement(SequenceNormalizer.java:230)
      [fop]     at net.sf.saxon.event.ReceivingContentHandler.endElement(ReceivingContentHandler.java:528)
      [fop]     at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
      [fop]     at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
      [fop]     at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(RelaxNGDefaultsComponent.java:637)
      [fop]     at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
      [fop]     at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
      [fop]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
      [fop]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
      [fop]     at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop]     at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:111)
      [fop]     at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop]     at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
      [fop]     at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
      [fop]     at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
      [fop]     at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:435)
      [fop]     at net.sf.saxon.event.Sender.send(Sender.java:141)
      [fop]     at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:368)
      [fop]     at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:293)
      [fop]     ... 47 more
      [fop] Caused by: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10831)
      [fop]     at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
      [fop]     at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
      [fop]     at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
      [fop]     at jdk.proxy2/jdk.proxy2.$Proxy5.missingChildElement(Unknown Source)
      [fop]     at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:608)
      [fop]     at org.apache.fop.fo.pagination.Flow.endOfNode(Flow.java:93)
      [fop]     at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
      [fop]     at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
      [fop]     at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:412)
      [fop]     ... 67 more
      [fop]
Error: The following error occurred while executing this line:
C:\code\dita-ot-3.6.1\plugins\org.dita.pdf2.fop\build_fop.xml:147: [PDFX013F][FATAL] The PDF file 'c:\code\docs-prototype\.\out/SystemOverview.pdf' could not be generated..
```

For XHTML, the index.html does not contain any ToC items. Individual files have rendered, but all conrefs have failed because the element IDs haven't been identified correctly. I haven't done much further checking.

```
 [conref] file:/c:/code/docs-prototype/dita_content/Ditamaps/Source/Converted/Concepts/KeyFeatures.dita:431:144: [DOTX015E][ERROR]: The attribute conref="KeyFeatures.dita" uses invalid syntax. The value should contain '#' followed by a topic or map ID, optionally followed by '/elemID' for a sub-topic element.
```

# Possible solution

Workarounds:
* Specify an absolute path and capitalize the drive, as suggested above
* Use PowerShell - files are loaded properly when using PowerShell 5.1

# Steps to reproduce

Invoke the DITA-OT from the Windows command prompt with the `dita` command, without absolute paths. The capitalization issues seem to appear on any map; the mapref issue requires a mapref. I can't share the files, but can check / repro with some freely-available dita files, if that would help.

# Copy of the error message, log file or stack trace

Some key snippets above; if you need more to progress, I'll repro with another project.

# Environment

DITA-OT version: DITA OT 3.6.1
Operating system and version: Windows 10 
How did you run DITA-OT? Invoked with the `dita` command from the Windows command prompt. Backed by the Microsoft build of the OpenJDK:
```
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Microsoft-22300 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Microsoft-22300 (build 16.0.1+9, mixed mode, sharing)
```
Transformation type: pdf, xhtml - no modifications

**Comment by raducoravu** [comment]
@ckab74 Seems indeed cauzed by #3535 
If you set "processing.mode" to "skip" does the publishing start working?
I think the problem might be the drive letter, it should be "C:" instead of "c:", so the way in which the absolute path to the DITA Map is computed might need a bit of adjusting.

**Comment by ckab74** [comment]
@raducoravu I can't test changing the processing.mode setting right now. We have some publications coming up.
I'm no sure what you mean by the second sentence. Should we adjust the absolute path to the DITA Map or should the DITA OT implementation be changed so that capitalization/non-capitalization is no longer an issue? We've made a change to the way the absolute path is computed, yes, but this is a workaround.

**Comment by raducoravu** [comment]
@ckab74 I was suggesting the workaround of computing the absolute path using "C:" instead of "c:". I agree that maybe the DITA OT should canonicalize the original DITA Map location so I think it's good you added this issue.

**Comment by mikclrk-21cs** [comment]
Managed to reproduce something very similar by issuing the command:

`dita -i ditak9/IZPCA_DB2.bookmap -o htmlk9 -f html5`

The directories in question are actually called ditaK9 and htmlK9, but all of the references are relative - the directory names don't appear anywhere in the .dita(map) files.  Lots of messages about case mismatches in references and a lot of infinite loop errors.  The messages do identify the issue as the case of the ditak9 directory (although it took me a while to see it).

If I run it as:

`dita -i ditaK9/IZPCA_DB2.bookmap -o htmlK9 -f html5`

all works fine, confirming it's not an error in the .dita files.

Might want to add an upfront check to see if the case of the input file and output directory match their case on disk and, frankly, under windows I'd expect you to use the case on disk and forgive the lazy user input.  If you're going to fail it, do it up front with a 'directory/file not found - use exact case' error - which you probably get on linux already.  What you're currently doing is reporting multiple false errors in the document because you're incorrectly resolving relative addresses using the input parameters rather than using the actual name on disk of the file that the input parameters refer to (only possible under windows).

The loop, incidentally, is there all the time -  .book chapter-rerfs comp.ditamap which topic-refs comp_XXXX.dita which x-refs table_YYYY.dita which x-refs back to comp_XXXX.dita and all works fine when rendered as html5.  So why is issueing a warning for the xrefs causing a whole lot of infinite reference loop error messages?  Smells like a different problem with the warning causing something to be skipped or set incorrectly (the reference not being flagged as a soft x-ref?)

dita is:

`D:\izpca\Unity>dita -version
DITA-OT version 4.0.1`

running under windows 10, with java 17:

```
D:\izpca\Unity>D:\JDKs\jdk-17.0.2\bin\java.exe -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

**Comment by altair-brian** [comment]
Yes, also encountered. Our CI environment passes in "c:" but DITA-OT is calculating "C:" somewhere internally and the only way to work around it that I've found is to pass:

`--processing-mode=skip`

Which we obviously don't want to do. This needs to be fixed, and for the record, it didn't happen in v2.
