### ISSUE TITLE
PDF causes error Can't connect to X11 window server

### ISSUE THREAD

**Issue by DeekshaBhagat** [dita-ot/dita-ot#3799]
## Expected Behavior
DITATopic containing SVG image should be successfully transformed into pdf using DITA-OT java api.

## Actual Behavior
DITATopic containing SVG image gives error while transforming into pdf using DITA-OT java api..
It works fine for PNG image file.

## Possible Solution
Don't know how to fix this.

## Steps to Reproduce

1.
2.
3.

## Copy of the error message, log file or stack trace

```
Caused by: org.apache.tools.ant.BuildException: The following error occurred while executing this line:
/ExecutionFramework/linux_a64/docs/javaserver/dita-ot/plugins/org.dita.pdf2.fop/build_fop.xml:145: java.awt.AWTError: Can't connect to X11 window server using '<server-name>:0' as the value of the DISPLAY variable.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:571)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.dita.dost.Processor.run(Processor.java:216)
	... 14 common frames omitted
Caused by: org.apache.tools.ant.BuildException: java.awt.AWTError: Can't connect to X11 window server using '<server-name>:0' as the value of the DISPLAY variable.
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:109)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	... 28 common frames omitted
Caused by: java.awt.AWTError: Can't connect to X11 window server using '<server-name>:0' as the value of the DISPLAY variable.
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
	at org.apache.batik.bridge.DefaultFontFamilyResolver.<clinit>(DefaultFontFamilyResolver.java:85)
	at org.apache.fop.image.loader.batik.PreloaderSVG$Loader.createImageInfo(PreloaderSVG.java:165)
	at org.apache.fop.image.loader.batik.PreloaderSVG$Loader.getImage(PreloaderSVG.java:131)
	at org.apache.fop.image.loader.batik.PreloaderSVG$Loader.access$200(PreloaderSVG.java:108)
	at org.apache.fop.image.loader.batik.PreloaderSVG.preloadImage(PreloaderSVG.java:76)
	at org.apache.xmlgraphics.image.loader.ImageManager.preloadImage(ImageManager.java:176)
	at org.apache.xmlgraphics.image.loader.cache.ImageCache.needImageInfo(ImageCache.java:127)
	at org.apache.xmlgraphics.image.loader.ImageManager.getImageInfo(ImageManager.java:123)
	at org.apache.fop.fo.flow.ExternalGraphic.bind(ExternalGraphic.java:81)
	at org.apache.fop.fo.FObj.processNode(FObj.java:129)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:293)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at net.sf.saxon.event.ContentHandlerProxy.startContent(ContentHandlerProxy.java:385)
	at net.sf.saxon.event.ProxyReceiver.startContent(ProxyReceiver.java:177)
	at net.sf.saxon.event.SequenceNormalizer.startContent(SequenceNormalizer.java:163)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:446)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(RelaxNGDefaultsComponent.java:637)
	at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:111)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:435)
	at net.sf.saxon.event.Sender.send(Sender.java:141)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:368)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:293)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:648)
	at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:671)
	at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:532)
	at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:369)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	... 35 common frames omitted
```

## Environment
Cloud

* DITA-OT version:3.4
* Operating system and version: Linux and Windows
* How did you run DITA-OT: using Java API
* Transformation type:   PDF

**Comment by raducoravu** [comment]
How do you start the DITA OT process? Are you using the "dita-ot\bin\dita" executable?

**Comment by DeekshaBhagat** [comment]
Yes dita-ot\bin\dita" is executable.
We ae using java 8.
 DITA-OT process is like, we keep ditataopic and image in a temp folder in local server and use those paths for transformation.

ProcessorFactory pf = ProcessorFactory.newInstance(ditaOTDir);
			// and set the temporary directory
			pf.setBaseTempDir(ditaTempDir);

			// Create a processor using the factory and configure the processor
			Processor p = pf.newProcessor(renderFormat).setInput(mapFile).setOutputDir(outDir).createDebugLog(false)
					.setProperties(ditaProperties);

			if (renderLogger != null) {
				p.setLogger(renderLogger);
			}

			// Run conversion
			p.run();

**Comment by raducoravu** [comment]
You are not using the "dita" executable, you are creating your own Java code which uses directly the DITA OT Java API to start a process.
Maybe when you start your Java process you can pass the "-Djava.awt.headless=true" parameter to the Java executable, see if it works or not.

**Comment by DeekshaBhagat** [comment]
Do I need to pass "-Djava.awt.headless=true" parameter in ditaProperties in below code-

	Processor p = pf.newProcessor(renderFormat).setInput(mapFile).setOutputDir(outDir).createDebugLog(false)
					_.setProperties(ditaProperties);_

**Comment by DeekshaBhagat** [comment]
@raducoravu Thank you for help.
I added below line in my code and it works for me.
		System.setProperty("java.awt.headless", "true");

**Comment by raducoravu** [comment]
@DeekshaBhagat right, you could have also added it to the command line which starts the Java application you are building.

**Comment by raducoravu** [comment]
@DeekshaBhagat maybe you can close this issue if the workaround works for you.
