### ISSUE TITLE
DITAOTException when resolving subject schema map references

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#3808]
## Expected Behavior
Subject scheme map references should resolve properly.

## Actual Behavior
Build fails in `debug-filter`.

## Possible Solution
No idea

## Steps to Reproduce

1. Download and extract [subject-scheme-issue.zip](https://github.com/dita-ot/dita-ot/files/7279389/subject-scheme-issue.zip).
2. Open the `subject-scheme-issue` > `pubmap` > `publication-map.ditamap`.
3. Start a `pdf2` publication.

## Copy of the error message, log file or stack trace
```bash
debug-filter:
   [filter] Using Xerces grammar pool for DTD and schema caching.
   [filter] Failed to read document: C:\Users\eike\Downloads\subject-scheme-issue\pubmap\audiences.ditamap (The system cannot find the file specified)
   [filter] org.dita.dost.exception.DITAOTException
   [filter] 	at org.dita.dost.module.DebugAndFilterModule.outputSubjectScheme(DebugAndFilterModule.java:357)
   [filter] 	at org.dita.dost.module.DebugAndFilterModule.init(DebugAndFilterModule.java:192)
   [filter] 	at org.dita.dost.module.DebugAndFilterModule.execute(DebugAndFilterModule.java:99)
   [filter] 	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:189)
   [filter] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [filter] 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
   [filter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [filter] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   [filter] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [filter] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [filter] 	at org.apache.tools.ant.Target.execute(Target.java:449)
   [filter] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
   [filter] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
   [filter] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
   [filter] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
   [filter] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
   [filter] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
   [filter] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [filter] 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
   [filter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [filter] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   [filter] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [filter] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [filter] 	at org.apache.tools.ant.Target.execute(Target.java:449)
   [filter] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
   [filter] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
   [filter] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
   [filter] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
   [filter] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
   [filter] 	at org.apache.tools.ant.Main.runBuild(Main.java:827)
   [filter] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
   [filter] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
   [filter] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
   [filter] Caused by: java.io.IOException: Failed to read document: C:\Users\eike\Downloads\subject-scheme-issue\pubmap\audiences.ditamap (The system cannot find the file specified)
   [filter] 	at org.dita.dost.store.StreamStore.getDocument(StreamStore.java:71)
   [filter] 	at org.dita.dost.store.StreamStore.getImmutableDocument(StreamStore.java:53)
   [filter] 	at org.dita.dost.module.DebugAndFilterModule.outputSubjectScheme(DebugAndFilterModule.java:344)
   [filter] 	... 32 more
   [filter] Caused by: java.io.FileNotFoundException: C:\Users\eike\Downloads\subject-scheme-issue\pubmap\audiences.ditamap (The system cannot find the file specified)
   [filter] 	at java.base/java.io.FileInputStream.open0(Native Method)
   [filter] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
   [filter] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
   [filter] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
   [filter] 	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
   [filter] 	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
   [filter] 	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:1040)
   [filter] 	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
   [filter] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
   [filter] 	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:112)
   [filter] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
   [filter] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
   [filter] 	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
   [filter] 	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:306)
   [filter] 	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:178)
   [filter] 	at org.dita.dost.store.StreamStore.getDocument(StreamStore.java:69)
   [filter] 	... 34 more`
```

## Environment

* DITA-OT version: 3.6.0
* Operating system and version: Windows 10
* How did you run DITA-OT? oxygen
* Transformation type: PDF2

**Comment by xephon2** [comment]
@raducoravu, thanks a lot for your support. I confirm setting the `fix.external.refs.com.oxygenxml` transformation scenario solves this issue. Anyhow, using a single subject scheme map which is outside of the DITA Map folder works, the problem only occurs, if the subject scheme map has submaps.

So, IMHO this is still a bug. Further on, according to [your docs](https://www.oxygenxml.com/doc/versions/23.1/ug-editor/topics/dita-ot-external-refs.html), this parameter only works when the publication is triggered from oXygen directly, so it's not a good solution for a server based publishing environment. It's not an official DITA-OT parameter.

**Comment by chrispy-snps** [comment]
This problem can also be reproduced by attempting to publish the DITA-OT user guide TOC:

`dita -i ./dita-ot/docsrc/resources/common-toc.ditamap -f html5`

The error initiating the exception is (note the double "resources/"):

`[filter] Failed to read document: /mnt/c/Users/chrispy/DITA/4218/docsrc/resources/resources/subjectscheme-outputclass.ditamap (No such file or directory)`
