### ISSUE TITLE
Guard against possible NPE in XMLUtils.toErrorReporter(DITAOTLogger)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3959]
Using an invalid plugin I got this NPE in the XMLUtils.toErrorReporter method:

      .... java.lang.NullPointerException: Cannot invoke "net.sf.saxon.s9api.Location.getSystemId()" because the return value of "net.sf.saxon.s9api.XmlProcessingError.getLocation()" is null
	at org.dita.dost.util.XMLUtils.lambda$0(XMLUtils.java:202)
	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:117)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:838)
	at org.dita.dost.module.XsltModule.execute(XsltModule.java:112)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:189)
	
the NPE is caused by a FileNotFoundException thrown somewhere because an XSLT stylesheet is missing in my plugin:

       .../plugins/com.oxygenxml.webhelp.responsive/xsl/indexterms/extractIndexterms.xsl (No such file or directory)
         [pipeline] 	at java.base/java.io.FileInputStream.open0(Native Method)
         [pipeline] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
         [pipeline] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
         [pipeline] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
         [pipeline] 	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
         [pipeline] 	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
         [pipeline] 	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:1114)
         [pipeline] 	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
         [pipeline] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
         [pipeline] 	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:119)
         [pipeline] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
         [pipeline] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
         [pipeline] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
         [pipeline] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
         [pipeline] 	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
         [pipeline] 	at net.sf.saxon.event.Sender.send(Sender.java:168)
         [pipeline] 	at net.sf.saxon.style.StylesheetModule.sendStylesheetSource(StylesheetModule.java:157)
         [pipeline] 	at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:229)
         [pipeline] 	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:113)
         [pipeline] 	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:838)
         [pipeline] 	at org.dita.dost.module.XsltModule.execute(XsltModule.java:112)
         [pipeline] 	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:1

**Comment by raducoravu** [comment]
I also added an issue on the Saxonica issues list to clarify their Javadoc for the net.sf.saxon.s9api.XmlProcessingError.getLocation() method:
https://saxonica.plan.io/issues/5588
