### ISSUE TITLE
Chunk to content on DITA Map fails when the DITA Map has spaces in file name

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4064]
I have a DITA Map with spaces in its file name "flowers by season_map.ditamap" which has chunk=to-content set on the root element.

Publishing it to HTML5 fails with:

        /.../plugins/org.dita.base/build_preprocess.xml:260: java.lang.IllegalArgumentException: Illegal character in path at index 7: flowers by season_map.dita
	at java.base/java.net.URI.create(URI.java:906)
	at java.base/java.net.URI.resolve(URI.java:1089)
	at org.dita.dost.reader.ChunkMapReader.chunkMap(ChunkMapReader.java:209)
	at org.dita.dost.reader.ChunkMapReader.process(ChunkMapReader.java:136)
	at org.dita.dost.writer.AbstractDomFilter.read(AbstractDomFilter.java:41)

[flowers22.zip](https://github.com/dita-ot/dita-ot/files/10089903/flowers22.zip)

**Comment by lief-erickson** [comment]
@raducoravu, very interesting. Thank you for reporting this. I recently used `flowers.ditamap` as a test case for something and it failed. I hadn't investigated yet, but this might be the explanation.

**Comment by raducoravu** [comment]
@lief-erickson our original flowers.ditamap does not have submaps, I just created a submap with spaces inside its file name to reflect this problem and attach a sample project to the issue. So it's possible your test case failed because of something else.
