### ISSUE TITLE
InvocationTargetException is triggered when using custom PDF plugin with XSLT <pipeline> on Github Actions

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#4145]
## Expected Behavior
The build should pass on Github Actions, as it does locally on my Windows machine.

## Actual Behavior

The build fails on Github Actions with an `InvocationTargetException` when using a custom `pdf2` based transformation. This transformation works fine on my local Windows machine. I can publish on Github Actions when using a pure `pdf2` transformation (no custom transformation type).

My first guess is, that this is in some way related to a relative/absolute OS-specific path issue.

```
org.dita.index.init:

org.dita.index:
     [echo] Processing /opt/app/temp/temp20230306074216588/HelloWorld_MERGED.xml to /opt/app/temp/temp20230306074216588/stage1.xml

transform.topic2fo.main:
 [pipeline] Loading stylesheet /opt/app/plugins/com.dometic.dita-ot.pdf/xsl/fo/topic2fo_shell_dometic_fop.xsl
Error: The following error occurred while executing this line:
/opt/app/plugins/org.dita.pdf2/build.xml:280: java.lang.reflect.InvocationTargetException
```

The log is not very useful, even with `-v` and `-d` verbose/debugging parameters. The problem is somewhere in this **`<pipeline>`** element.

```xml
<target name="transform.topic2fo.main">
    <local name="_stage1.exists"/>
    <available property="_stage1.exists" file="${dita.temp.dir}/stage1.xml"/>
    <copy file="${inputFile}" tofile="${dita.temp.dir}/stage1.xml" unless:set="_stage1.exists"/>

    <!--makeurl seems to output file:/C: style instead of file:///C:, but xep, fop, and ah all accept it.-->
    <makeurl property="artworkPrefixUrl" file="${artworkPrefix}" validate="no"/>
    <makeurl property="dita.map.output.dir.url" file="${pdf2.temp.dir}" validate="no"/>
    <makeurl property="work.dir.url" file="${dita.temp.dir}" validate="no"/>
    <makeurl property="customization.dir.url" file="${customization.dir}" validate="no"/>
    <makeurl property="user.input.dir.url" file="${user.input.dir}" validate="no"/>
    <makeurl property="variable.file.url" file="${variable.file}" validate="no"/>

    <pipeline> <!-- This is line 280 (org.dita.pdf2/build.xml:280) -->
      <xslt style="${temp.transformation.file}" in="${dita.temp.dir}/stage1.xml" out="${dita.temp.dir}/stage2.fo">
        <param name="locale" expression="${document.locale}"/>
        <param name="customizationDir.url" expression="${customization.dir.url}" if:set="customization.dir"/>
        <param name="input.dir.url" expression="${user.input.dir.url}"/>
        <param name="DRAFT" expression="${args.draft}"/>
        <param name="output.dir.url" expression="${dita.map.output.dir.url}"/>
        <param name="work.dir.url" expression="${work.dir.url}"/>
        <param name="artworkPrefix" expression="${artworkPrefixUrl}"/>
        <param name="publishRequiredCleanup" expression="${publish.required.cleanup}"/>
        <param name="artLabel" expression="${args.artlbl}" if:set="args.artlbl"/>
        <param name="antArgsBookmarkStyle" expression="${args.bookmark.style}"/>
        <param name="antArgsChapterLayout" expression="${args.chapter.layout}"/>
        <param name="include.rellinks" expression="${include.rellinks}"/>
        <param name="antArgsGenerateTaskLabels" expression="${args.gen.task.lbl}"/>
        <param name="pdfFormatter" expression="${pdf.formatter}"/>
        <param name="bookmap-order" expression="${args.bookmap-order}"/>
        <param name="figurelink.style" expression="${args.figurelink.style}"/>
        <param name="tablelink.style" expression="${args.tablelink.style}"/>
        <param name="variableFiles.url" expression="${variable.file.url}" if:set="variable.file.exists"/>
        <param name="defaultLanguage" expression="${default.language}"/>

        <param xmlns:if="ant:if" name="bookrights" expression="${bookrights}"/>
        <param xmlns:if="ant:if" name="brand" expression="${brand}"/>
        <param xmlns:if="ant:if" name="compliance-image" expression="${compliance-image}"/>
        <param xmlns:if="ant:if" name="debugging.mode" expression="${debugging.mode}"/>
        <param xmlns:if="ant:if" name="ditaTempDir" expression="${dita.temp.dir}"/>
        <param xmlns:if="ant:if" name="document-id" expression="${document-id}"/>
        <param xmlns:if="ant:if" name="document-type" expression="${document-type}"/>
        <param xmlns:if="ant:if" name="dometic-company" expression="${dometic-company}"/>
        <param xmlns:if="ant:if" name="factory-supplier" expression="${factory-supplier}"/>
        <param xmlns:if="ant:if" name="force.decimal.places" expression="${force.decimal.places}"/>
        <param xmlns:if="ant:if" name="frontpage-layout" expression="${frontpage-layout}"/>
        <param xmlns:if="ant:if" name="generate.backcover" expression="${generate.backcover}"/>
        <param xmlns:if="ant:if" name="git.commit" expression="${git.commit}"/>
        <param xmlns:if="ant:if" name="mini.toc.levels" expression="${mini.toc.levels}"/>
        <param xmlns:if="ant:if" name="model-family" expression="${model-family}"/>
        <param xmlns:if="ant:if" name="model-family-length" expression="${model-family-length}"/>
        <param xmlns:if="ant:if" name="move.figures.before.text" expression="${move.figures.before.text}"/>
        <param xmlns:if="ant:if" name="number-of-parts" expression="${number-of-parts}"/>
        <param xmlns:if="ant:if" name="number.of.columns" expression="${number.of.columns}"/>
        <param xmlns:if="ant:if" name="page.format" expression="${page.format}"/>
        <param xmlns:if="ant:if" name="pdf.watermark" expression="${pdf.watermark}"/>
        <param xmlns:if="ant:if" name="process.map.metadata" expression="${process.map.metadata}"/>
        <param xmlns:if="ant:if" name="product-area" expression="${product-area}"/>
        <param xmlns:if="ant:if" name="product-area-length" expression="${product-area-length}"/>
        <param xmlns:if="ant:if" name="product-name-length" expression="${product-name-length}"/>
        <param xmlns:if="ant:if" name="skus" expression="${skus}"/>
        <param xmlns:if="ant:if" name="special-document-id" expression="${special-document-id}"/>
        <param xmlns:if="ant:if" name="technical.units" expression="${technical.units}"/>
        <param xmlns:if="ant:if" name="technical.values.decimal.places.imperial" expression="${technical.values.decimal.places.imperial}"/>
        <param xmlns:if="ant:if" name="technical.values.decimal.places.si" expression="${technical.values.decimal.places.si}"/>
        <param xmlns:if="ant:if" name="wrike.pdf.permalink" expression="${wrike.pdf.permalink}"/>
        <param xmlns:if="ant:if" name="wrike.upload" expression="${wrike.upload}"/>


        <param xmlns:if="ant:if" name="editlink.remote.ditamap.url" expression="${editlink.remote.ditamap.url}" if:set="editlink.remote.ditamap.url"/>


        <param xmlns:if="ant:if" name="editlink.web.author.url" expression="${editlink.web.author.url}" if:set="editlink.web.author.url"/>
        <param xmlns:if="ant:if" name="editlink.present.only.path.to.topic" expression="${editlink.present.only.path.to.topic}" if:set="editlink.present.only.path.to.topic"/>

        <param name="editlink.local.ditamap.path" expression="${args.input}"/>
        <param xmlns:if="ant:if" name="editlink.local.ditaval.path" expression="${args.filter}" if:set="args.filter"/>

        <param xmlns:if="ant:if" name="editlink.ditamap.edit.url" expression="${editlink.ditamap.edit.url}" if:set="editlink.ditamap.edit.url"/>
        <param xmlns:if="ant:if" name="editlink.additional.query.parameters" expression="${editlink.additional.query.parameters}" if:set="editlink.additional.query.parameters"/>

        <param xmlns:if="ant:if" name="com.oxygenxml.xhtml.linkToMediaResources" expression="${com.oxygenxml.xhtml.linkToMediaResources}" if:set="com.oxygenxml.xhtml.linkToMediaResources"/>
        <param name="ditaTempDir" expression="${dita.temp.dir}"/>

        <param xmlns:if="ant:if" name="com.oxygenxml.use.custom.note.images" expression="${com.oxygenxml.use.custom.note.images}" if:set="com.oxygenxml.use.custom.note.images"/>

        <param name="use.alpha.for.highlights" expression="'no'"/>
        <param xmlns:if="ant:if" name="show.changes.and.comments" expression="${show.changes.and.comments}" if:set="show.changes.and.comments"/>
        <param xmlns:if="ant:if" name="show.changebars" expression="${show.changebars}" if:set="show.changebars"/>

        <param name="tempdirLocalComm" expression="${dita.temp.dir}"/>
        <param name="mappath" expression="${args.input}"/>

        <param xmlns:if="ant:if" name="lc-number-questions" expression="${arg.lc.html.numberQuestions}" if:set="arg.lc.html.numberQuestions"/>
        <param xmlns:if="ant:if" name="lc-show-feedback" expression="${arg.lc.html.showFeedback}" if:set="arg.lc.html.showFeedback"/>
        <param xmlns:if="ant:if" name="lc-style-correct-responses" expression="${arg.lc.html.styleCorrectResponses}" if:set="arg.lc.html.styleCorrectResponses"/>
        <param xmlns:if="ant:if" name="lc-question-number-format" expression="${arg.lc.html.questionNumberFormat}" if:set="arg.lc.html.questionNumberFormat"/>
        <param xmlns:if="ant:if" name="lc-question-number-prefix" expression="${arg.lc.html.questionNumberPrefix}" if:set="arg.lc.html.questionNumberPrefix"/>
        <param xmlns:if="ant:if" name="lc-question-number-suffix" expression="${arg.lc.html.questionNumberSuffix}" if:set="arg.lc.html.questionNumberSuffix"/>
        <param xmlns:if="ant:if" name="lc-answer-option-number-format" expression="${arg.lc.html.answerOptionNumberFormat}" if:set="arg.lc.html.answerOptionNumberFormat"/>
        <param xmlns:if="ant:if" name="lc-show-only-correct-answer" expression="${arg.lc.html.showOnlyCorrectAnswer}" if:set="arg.lc.html.showOnlyCorrectAnswer"/>
        <param xmlns:if="ant:if" name="lc-show-only-feedback" expression="${arg.lc.html.showOnlyFeedback}" if:set="arg.lc.html.showOnlyFeedback"/>
        <param xmlns:if="ant:if" name="lc-hide-question-labels" expression="${arg.lc.html.hideQuestionLabels}" if:set="arg.lc.html.hideQuestionLabels"/>

        <param name="tempdir" expression="${dita.temp.dir}"/>
        <param name="mappath" expression="${args.input}"/>

        <xmlcatalog refid="xml.catalog"/>
      </xslt>
    </pipeline>
  </target>
```

## Possible Solution
I have no idea.

## Steps to Reproduce
Maybe by creating a very simple pdf2 overriding plugin and running it on Github Actions. But so far I have not yet had the time to do that.

## Copy of the error message, log file or stack trace
see above

## Environment

**Github Actions**

* DITA-OT version: 3.6.1, 4.0.2
* Operating system and version: Ubuntu
* How did you run DITA-OT? `dita` command with DITA-OT project file
* Transformation type: dometic-pdf (based on pdf2/FOP)

**Local**

* DITA-OT version: 3.6.1
* Operating system and version: Windows
* How did you run DITA-OT? Oxygen with DITA-OT project file
* Transformation type: dometic-pdf (based on pdf2/FOP)

**Comment by raducoravu** [comment]
The stack trace of the error would have helped. It's not there probably because of #3731
How about if you use the stock DITA OT with plain PDF output without your dometic-pdf plugin?

**Comment by xephon2** [comment]
@raducoravu, as I wrote in the description: `-d` and `-v` are set and _This transformation works fine on my local Windows machine. I can publish on Github Actions when using a pure pdf2 transformation (no custom transformation type)._

It runs fine with a stock 3.6.1 and pdf2 on Github Actions. But I need the custom stuff. 🤷🏻‍♂️

**Comment by xephon2** [comment]
I get the same error when using 4.0.2 on Github Actions.

**Comment by raducoravu** [comment]
@xephon2 you mentioned the same DITA OT works on Windows (I assume using the command line). Can you test the same DITA OT on a local Linux or Mac OS machine?
Can you check if the problem is somehow caused by the published content? Maybe try to publish a very small DITA Map with 1-2 topics?
Other than that if you pack the entire DITA OT (including your custom plugins) with a small DITA project to reproduce the problem I could try to run it on my Mac and see if I can reproduce the problem and if I can get the entire stack trace of the error printed.

**Comment by xephon2** [comment]
Hi @raducoravu, I cannot test with a fresh DITA-OT flavored with the needed plugins locally, because the policy stops me. There is probably one Java library different between the 3.6.1 Oxygen publishing engine and the 3.6.1 stock OT. This makes debugging so difficult. 😞 

```bash
dist:
     [exec] This program is blocked by group policy. For more information, contact your system administrator.
```

It would be very kind of you, if you'd take the time to test this on your computer. Thank you so much in advance. 🙇🏻 I'll send you an e-mail.

**Comment by raducoravu** [comment]
Here's the entire stack trace of the error:

    Caused by: javax.xml.transform.TransformerException: Malformed URL plugin:com.oxygenxml.highlight:pdfHighlight.xsl(base file:/Users/raducoravu/Downloads/stefan-dita-ot/plugins/com.dometic.dita-ot-pdf/xsl/fo/topic2fo_shell_dometic_fop.xsl)
	at org.apache.xml.resolver.tools.CatalogResolver.resolve(CatalogResolver.java:266)
	... 76 more
Caused by: java.net.MalformedURLException: unknown protocol: plugin
	at java.base/java.net.URL.<init>(URL.java:681)

Your topic2fo_shell_dometic_fop.xsl seems to refer to an Oxygen specific commercial plugin which is not installed.

**Comment by xephon2** [comment]
Thank you so much, @raducoravu. This was indeed the problem. 👍🏻 

I totally forgot the shell file.
