### ISSUE TITLE
Branch filtering issues - NullPointerException

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#4190]
## Expected Behavior
The attached source files help to reproduce two issues: A Java error in the `branch-filter` step and a logical issue in the output.

## Actual Behavior

The publishing throws this `NullPointerException`, which causes the build to fail.

## Possible Solution
No idea

## Steps to Reproduce
Download the test files [branch-filtering-override.zip](https://github.com/dita-ot/dita-ot/files/11441160/branch-filtering-override.zip) and build the deliverable from the DITA-OT project file .

## Copy of the error message, log file or stack trace

```bash
branch-filter:
[branch-filter] Processing file:/C:/Users/eike/workspace/branch-filtering-override/temp/branch-filtering-override.ditamap
[branch-filter] Reading file:/C:/Users/eike/workspace/branch-filtering-override/expert.ditaval
Error: java.lang.NullPointerException: Cannot read field "src" because "fi" is null
```

## Environment

* DITA-OT version: 3.6.0
* Operating system and version: Windows 10
* How did you run DITA-OT? oXygen
* Transformation type: pdf2

**Comment by raducoravu** [comment]
The stack trace of the error is something like this:

    java.lang.NullPointerException: Cannot read field "src" because "fi" is null
	at org.dita.dost.module.BranchFilterModule.getFilterUtils(BranchFilterModule.java:481)
	at org.dita.dost.module.BranchFilterModule.combineFilterUtils(BranchFilterModule.java:357)
	at org.dita.dost.module.BranchFilterModule.filterTopics(BranchFilterModule.java:433)
	at org.dita.dost.module.BranchFilterModule.filterTopics(BranchFilterModule.java:467)
	at org.dita.dost.module.BranchFilterModule.processMap(BranchFilterModule.java:144)
	at org.dita.dost.module.BranchFilterModule.execute(BranchFilterModule.java:103)

Somehow seems to be related to the fact that the same ditaval file is referenced multiple times in the DITA Map, if I were to replace:

    <topicref href="topic3.dita" audience="expert">
        <ditavalref href="expert.ditaval"/>
    </topicref>
    <topicref href="linux.dita" platform="linux">
        <ditavalref href="expert.ditaval"/>
    </topicref>

with:

    <topicgroup>
        <ditavalref href="expert.ditaval"/>
        <topicref href="topic3.dita" audience="expert"/>
        <topicref href="linux.dita" platform="linux"/>
    </topicgroup>

the error would no longer occur.

**Comment by xephon2** [comment]
@raducoravu You are right, but still I consider this to be a bug. We have a couple of branches (maps) which have to be filtered with the same settings and a few with different settings. For us this means, I need to create tons of DITAVAL files. Let's say I have 25 branches (maps) and 23 of these are filtered the same way, I need to create and maintain 23 different DITAVALs instead of just one and make sure they have the same content, which is very error prone and time consuming.

**Comment by raducoravu** [comment]
@xephon2 I did not say this is not a bug, it was just a remark based on me working a bit with the samples.

**Comment by raducoravu** [comment]
+1 using DITA OT 4.1 this reported issue seems to produce the same null pointer exception:
https://stackoverflow.com/questions/76593411/using-same-ditaval-references-under-parent-map-and-sub-map-causes-null-pointer-e
Adding a sample for it as well:
[npeBranchFilter.zip](https://github.com/dita-ot/dita-ot/files/11932953/npeBranchFilter.zip)


     Users/...dita-ot-4.1/plugins/org.dita.base/build_preprocess.xml:163: java.lang.NullPointerException: Cannot read field "src" because "fi" is null
	at org.dita.dost.module.BranchFilterModule.getFilterUtils(BranchFilterModule.java:467)
	at org.dita.dost.module.BranchFilterModule.combineFilterUtils(BranchFilterModule.java:342)
	at org.dita.dost.module.BranchFilterModule.filterTopics(BranchFilterModule.java:416)
