### ISSUE TITLE
XSL Messages with termination are presented as unhandled internal errors

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4293]
If inside an XSLT stylesheet I add something like this:

     <xsl:message terminate="yes">THIS IS IT...</xsl:message>

I publish with the DITA OT and the console output contains an error like this:

            [pipeline] net.sf.saxon.s9api.SaxonApiUncheckedException: THIS IS IT...
            [pipeline] 	at org.dita.dost.util.XMLUtils.lambda$toMessageListener$0(XMLUtils.java:209)
            [pipeline] 	at net.sf.saxon.s9api.AbstractXsltTransformer.lambda$setMessageListener$0(AbstractXsltTransformer.java:302)
            [pipeline] 	at net.sf.saxon.expr.instruct.MessageInstr$MessageInstrElaborator.lambda$elaborateForPush$0(MessageInstr.java:351)
            [pipeline] 	at net.sf.saxon.expr.instruct.Block$BlockElaborator.lambda$elaborateForPush$1(Block.java:851)
            [pipeline] 	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:393)
            [pipeline] 	at net.sf.saxon.trans.Mode.handleRuleNotNull(Mode.java:587)
            [pipeline] 	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:521)
            [pipeline] 	at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:684)
            [pipeline] 	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:427)
            [pipeline] 	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:356)
            [pipeline] 	at org.dita.dost.store.StreamStore.transformUri(StreamStore.java:235)
            [pipeline] 	at org.dita.dost.store.StreamStore.transform(StreamStore.java:212)
            [pipeline] 	at org.dita.dost.module.XsltModule.transform(XsltModule.java:307)
            [pipeline] 	at org.dita.dost.module.XsltModule.transform(XsltModule.java:280)
            [pipeline] 	at org.dita.dost.module.XsltModule.execute(XsltModule.java:170)
            [pipeline] 	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:210)
            ...
            [pipeline] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
            [pipeline] Caused by: net.sf.saxon.expr.instruct.TerminationException: THIS IS IT...
            [pipeline] 	at org.dita.dost.util.XMLUtils.lambda$toMessageListener$0(XMLUtils.java:207)
            [pipeline] 	... 57 more
            [31mError: java.lang.RuntimeException: Internal error evaluating template rule  at line 125 in module file:/.../com.oxygenxml.webhelp.responsive/xsl/dita2webhelp/dita2webhelpImpl.xsl[0m

Looking at this console log as a developer it looks more ike a bug in the Saxon processor, not like an xsl:message which terminated the processing.
Maybe in the "XMLUtils MessageListener2.message(XdmNode, QName, boolean, SourceLocator)" when the terminate flag comes enabled we could just issue a message and let Saxon terminate the process instead of us.

Maybe we could also create a custom exception class which extends net.sf.saxon.s9api.SaxonApiUncheckedException, named something like "org.dita.dost.TerminateMessage" and throw that when we want to forcefully terminate a "FATAL" error which does not have terminate = yes.

**Comment by raducoravu** [comment]
Also the custom message presenter in XMLUtils receives a custom "code" which can be set from the xsl:message:

    <xsl:message terminate="yes" error-code="codeHere">ABC</xsl:message>

and we do not yet do anything with it right now, I think we could at least present it next to the message.

**Comment by chrispy-snps** [comment]
This would be a nice improvement.
