### ISSUE TITLE
Apache FOP cannot access the .fop/fop-fonts.cache anymore

### ISSUE THREAD

**Issue by stefan-jung** [dita-ot/dita-ot#4319]
## Expected Behavior
Since a few days, I cannot publish no PDFs anymore with Apache FOP. It started crashing and I don't know why. Not sure, if this is related to the DITA-OT, but I don't know where else to search for a solution.

## Actual Behavior
The build crashes because the FOP fonts cache cannot be accessed anymore `.fop\fop-fonts.cache (Access is denied)`. I can delete the entire directory. It is re-created when I publish something, so this is quite strange. Also the cache is filled with data during the transformation, so I absolutely do not understand why FOP is failing a few seconds later. And I cannot disable font caching, because then the publishing fails with a stack-overflow.

![image](https://github.com/dita-ot/dita-ot/assets/3266567/5450f6dd-df1f-40d1-9c8e-a51b02c058ac)

## Possible Solution
I have no idea.

## Steps to Reproduce
Can only repruce this on my computer, unfortunately.

## Copy of the error message, log file or stack trace

```
[fop] [ERROR] Anttask - Error rendering fo file: C:\Users\eike\workspace\dometic-docs\Power & Control\Interact Gateway\DMG210\temp\topic.fo <org.apache.fop.apps.FOPException: java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
[fop] java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)>org.apache.fop.apps.FOPException: java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
[fop] java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
[fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:657)
[fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:676)
[fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:537)
[fop] 	at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:369)
[fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
[fop] 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[fop] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[fop] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
[fop] 	at org.apache.tools.ant.Task.perform(Task.java:350)
[fop] 	at org.apache.tools.ant.Target.execute(Target.java:449)
[fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
[fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
[fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
[fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
[fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
[fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
[fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
[fop] 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[fop] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[fop] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
[fop] 	at org.apache.tools.ant.Task.perform(Task.java:350)
[fop] 	at org.apache.tools.ant.Target.execute(Target.java:449)
[fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
[fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
[fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
[fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
[fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
[fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
[fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
[fop] 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[fop] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[fop] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
[fop] 	at org.apache.tools.ant.Task.perform(Task.java:350)
[fop] 	at org.apache.tools.ant.Target.execute(Target.java:449)
[fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
[fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
[fop] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
[fop] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
[fop] 	at org.dita.dost.invoker.Main.runBuild(Main.java:718)
[fop] 	at org.dita.dost.invoker.Main.startAnt(Main.java:222)
[fop] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[fop] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[fop] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[fop] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[fop] 	at org.dita.dost.invoker.MainWithCPWildcardExpansion.startAnt(MainWithCPWildcardExpansion.java:65)
[fop] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
[fop] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
[fop] Caused by: org.apache.fop.apps.FOPException: java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
[fop] java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
[fop] 	at org.apache.fop.util.LogUtil.handleException(LogUtil.java:57)
[fop] 	at org.apache.fop.fonts.FontCache.saveTo(FontCache.java:222)
[fop] 	at org.apache.fop.fonts.FontCacheManagerFactory$FontCacheManagerImpl.save(FontCacheManagerFactory.java:71)
[fop] 	at org.apache.fop.fonts.FontManager.saveCache(FontManager.java:142)
[fop] 	at org.apache.fop.fonts.DefaultFontConfigurator.configure(DefaultFontConfigurator.java:103)
[fop] 	at org.apache.fop.render.PrintRendererConfigurator.getCustomFontCollection(PrintRendererConfigurator.java:147)
[fop] 	at org.apache.fop.render.PrintRendererConfigurator.setupFontInfo(PrintRendererConfigurator.java:127)
[fop] 	at org.apache.fop.render.intermediate.IFUtil.setupFonts(IFUtil.java:170)
[fop] 	at org.apache.fop.render.intermediate.IFRenderer.setupFontInfo(IFRenderer.java:187)
[fop] 	at org.apache.fop.area.RenderPagesModel.<init>(RenderPagesModel.java:75)
[fop] 	at org.apache.fop.area.AreaTreeHandler.setupModel(AreaTreeHandler.java:135)
[fop] 	at org.apache.fop.area.AreaTreeHandler.<init>(AreaTreeHandler.java:105)
[fop] 	at org.apache.fop.render.RendererFactory.createFOEventHandler(RendererFactory.java:363)
[fop] 	at org.apache.fop.fo.FOTreeBuilder.<init>(FOTreeBuilder.java:109)
[fop] 	at org.apache.fop.apps.Fop.createDefaultHandler(Fop.java:104)
[fop] 	at org.apache.fop.apps.Fop.<init>(Fop.java:78)
[fop] 	at org.apache.fop.apps.FOUserAgent.newFop(FOUserAgent.java:184)
[fop] 	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:108)
[fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:653)
[fop] 	... 50 more
[fop] Caused by: java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
[fop] 	at java.base/java.io.FileOutputStream.open0(Native Method)
[fop] 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[fop] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[fop] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[fop] 	at org.apache.fop.fonts.FontCache.saveTo(FontCache.java:213)
[fop] 	... 67 more
[fop] 
Error: The following error occurred while executing this line:
C:\Users\eike\AppData\Roaming\Dometic\DITA\dita-ot\plugins\org.dita.pdf2.fop\build_fop.xml:145: org.apache.fop.apps.FOPException: org.apache.fop.apps.FOPException: java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
org.apache.fop.apps.FOPException: java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
java.io.FileNotFoundException: C:\Users\eike\.fop\fop-fonts.cache (Access is denied)
```

```
eike@DOM-PF0ZVE6U MINGW64 ~/.fop
$ ls -l
total 1756
-rw-r--r-- 1 eike 1049089 1798019 Oct 16 12:00 fop-fonts.cache
```

## Environment

* DITA-OT version: 3.7.4
* Operating system and version: Windows
* How did you run DITA-OT? oXygen
* Transformation type: custom pdf2

**Comment by raducoravu** [comment]
This does not look like a bug in the DITA OT, it looks like a problem of permissions.
If you attempt to publish from the command line do you get the same problem?
When Oxygen starts, it starts usually as an application running under the current logger user's permissions. Then Oxygen starts the DITA OT process which runs again with the permissions inherited from Oxygen. And it seems the current logger user's permissions are considered not enough by Windows to open a stream to this file "C:\Users\eike\.fop\fop-fonts.cache".
So if you delete this "fop-fonts.cache" does the next publishing started from Oxygen break but also re-create it on disk?
If the file gets re-created could you maybe right click it in the Windows Explorer and look at its user based permissions?

**Comment by stefan-jung** [comment]
The problem suddenly disappeared again. Maybe this was related to a group IT policy change? I do not understand it.
