### ISSUE TITLE
NullPointerException in NormalizeTableFilter when reusing table cell

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4322]
## Expected Behavior
I'm attaching a sample project.
It contains an on the fly Oxygen topic specialization which defines a table cell which is reused from another topic.
The published output should contain the reused cell.

## Actual Behavior
When publishing to HTML the DITA OT breaks with a NullPointerException.

## Steps to Reproduce

1. Download the attached project.
2. Publish it to HTML5 for example.

[npe-conref-cell.zip](https://github.com/dita-ot/dita-ot/files/13276355/npe-conref-cell.zip)
## Copy of the error message, log file or stack trace

	at org.dita.dost.writer.NormalizeTableFilter.grow(NormalizeTableFilter.java:244)
	at org.dita.dost.writer.NormalizeTableFilter.processEntry(NormalizeTableFilter.java:171)
	at org.dita.dost.writer.NormalizeTableFilter.startElement(NormalizeTableFilter.java:136)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:539)
	at org.dita.dost.writer.TopicFragmentFilter.startElement(TopicFragmentFilter.java:75)

* DITA-OT version: 4.1
* Operating system and version:
  _(macOS)_
* How did you run DITA-OT?
  _(oXygen)_
* Transformation type:
  _(HTML5, PDF, custom, etc.)_

**Comment by jelovirt** [comment]
The only way to fix this is run the table normalization *after* conref. I don't remember whether we use table coordinates in any build step before conref.

**Comment by raducoravu** [comment]
The NormalizeTableFilter should not fail with a null pointer exception no matter what content it is given to parse.
Also it might fail when attempting to parse the "npe-conref-cell/Shared/aa_component_two.dita" which contains just the reusable cell element.

**Comment by raducoravu** [comment]
A similar problem was reported here:

https://www.oxygenxml.com/forum/post73228.html#p73228

    BUILD FAILED
    /Applications/Oxygen XML Editor/frameworks/dita/DITA-OT/plugins/org.dita.base/build.xml:28: The following error occurred while executing this line:
    /Applications/Oxygen XML Editor/frameworks/dita/DITA-OT/plugins/org.dita.base/build_preprocess.xml:210:     java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "array" is null
	at org.dita.dost.writer.NormalizeTableFilter.grow(NormalizeTableFilter.java:244)
	at org.dita.dost.writer.NormalizeTableFilter.processEntry(NormalizeTableFilter.java:171)
	at org.dita.dost.writer.NormalizeTableFilter.startElement(NormalizeTableFilter.java:136)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:539)
