### ISSUE TITLE
InvalidPathException when using URL inputs on windows

### ISSUE THREAD

**Issue by TiboGr** [dita-ot/dita-ot#4419]
## Steps to Reproduce

Use an url as input of a dita command line:
1. ```dita --args.input=http://myrepository/content/my_guide.bookmap -o output\\test_remote -f dita --generate.copy.outer=3```
2. process raises an error `InvalidPathException` when parsing arguments

## Copy of the error message, log file or stack trace
 ```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://myrepository/content/my_guide.bookmap
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.dita.dost.invoker.Arguments$FileArgument.getValue(Arguments.java:258)
        at org.dita.dost.invoker.ConversionArguments.handleParameterArg(ConversionArguments.java:266)
        at org.dita.dost.invoker.ConversionArguments.parse(ConversionArguments.java:153)
        at org.dita.dost.invoker.ArgumentParser.processArgs(ArgumentParser.java:122)
        at org.dita.dost.invoker.Main.processArgs(Main.java:300)
        at org.dita.dost.invoker.Main.startAnt(Main.java:183)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```
## Workaround

In the configuration file `config/plugins.xml`, changing the type of `args.input` from `file` to `string` allow to run the process.
It may induce side effets i did not notice.

```
    <!-- OLD VALUE -->
    <!-- <param desc="Specifies the main file for your documentation project." name="args.input" required="true" type="file"/> -->
    <param desc="Specifies the main file for your documentation project." name="args.input" required="true" type="string"/>
```

## Environment

* DITA-OT version: 4.1.2
* Operating system and version: Windows 11
* How did you run DITA-OT? `dita` command

**Comment by jelovirt** [comment]
@TiboGr could you try this on DITA-OT 4.2.1 on Windows and report what you get?

**Comment by jelovirt** [comment]
The problem with the initial report is that the parameter is given as `--args.input=http://myrepository/content/my_guide.bookmap`. That should be `--input`, not `--args.input`

**Comment by TiboGr** [comment]
I tried with DITA-OT 4.2.1 with `--input`. I have the same error.
