### ISSUE TITLE
docker: permission issue on pdf compilation when specifying user-id/group

### ISSUE THREAD

**Issue by raven42** [dita-ot/dita-ot#4473]
I'm seeing an issue with uid:group permissions when attempting to compile a PDF using the default docker image when specifying the `-u $(id -u):$(id -g` option. My company has tight restrictions on directory ownership and permissions, so I need to be able to specify the uid:group for the docker command.

## Expected Behavior
When using the default docker image with the `-u $(id -u):$(id -g` the PDF compilation should succeed work without issue.

## Actual Behavior
I'm seeing a permission issue when attempting to compile the PDF output. Compiling with `-f dita` or `-f html5` works find, but specifying the `-f pdf` fails.

## Possible Solution
The permissions for the anttask step during the Format PDF
```
==> Format PDF
[ERROR] Anttask - Error rendering fo file: /tmp/temp20240514160016393/topic.fo <org.apache.fop.apps.FOPException: java.io.FileNotFoundException: .fop (Permission denied)
java.io.FileNotFoundException: .fop (Permission denied)>org.apache.fop.apps.FOPException: java.io.FileNotFoundException: .fop (Permission denied)
java.io.FileNotFoundException: .fop (Permission denied)
        at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:652)
...
```

## Steps to Reproduce
Here is the sample files and command I'm using.
```
dita-ot-test$ ls -l
total 48
-rw-rw-r-- 1 username username  35 May 14 10:57 chapter-01.md
-rw-rw-r-- 1 username username 185 May 14 10:58 test.ditamap
dita-ot-test$ cat test.ditamap 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map title="Document">
    <topicref href="chapter-01.md" format="markdown"/>
</map>
dita-ot-test$ cat chapter-01.md 
# Chapter 1

Content for chapter 1
dita-ot-test$ 
```

## Copy of the error message, log file or stack trace
```
dita-ot-test$ docker run --user $(id -u):$(id -g) -v $(pwd):/src ghcr.io/dita-ot/dita-ot:4.2.3 -i /src/test.ditamap -o /src/out -f pdf -v
Initializing project

==> Validate and init input arguments
Created dir: /src/out
Created dir: /tmp/temp20240514160016393
transtype = pdf
tempdir = /tmp/temp20240514160016393
outputdir = /src/out
DITA-OT version = 4.2.3

==> Initialize map-first preprocessing
input = /src/test.ditamap

==> Merge DITAVAL files into temporary file

==> Read input map files to temporary store
Processing file:/src/test.ditamap to file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Resolve mapref in ditamap
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Profile input map files
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Resolve input map files branch filtering
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Resolve input map files keyref
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Resolve input map files conref push

==> Resolve conref in input map files

==> Profile input map files

==> Read topic files to temporary store
Reading file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap
Processing file:/src/chapter-01.md to file:/tmp/temp20240514160016393/039fbe363f975fc6dad0a5db7ccad9092bc6aa0b.md

==> Topic branch filtering
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Resolve conref in input map files

==> Resolve keyref

==> Resolve conref push

==> Resolve conref in input files

==> Profile input files

==> Normalize same topic fragment identifiers and table column names, and resolve coderef
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap
Processing file:/tmp/temp20240514160016393/039fbe363f975fc6dad0a5db7ccad9092bc6aa0b.md

==> Move metadata entries
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap
Loading stylesheet /opt/app/plugins/org.dita.base/xsl/preprocess/mappull.xsl
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Find and generate related link information

==> Pull metadata for link and xref element
Loading stylesheet file:/opt/app/plugins/org.dita.base/xsl/preprocess/topicpull.xsl
Loading stylesheet file:/opt/app/plugins/org.dita.base/xsl/preprocess/topicpull.xsl
Processing file:/tmp/temp20240514160016393/039fbe363f975fc6dad0a5db7ccad9092bc6aa0b.md

==> Map-first preprocessing topic steps

==> Clean ditamap
Loading stylesheet file:/opt/app/plugins/org.dita.base/xsl/preprocess/clean-map.xsl
Loading stylesheet file:/opt/app/plugins/org.dita.base/xsl/preprocess/clean-map.xsl
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap

==> Clean preprocess

==> Copy html files

==> Copy files to the output directory

==> Preprocess post

==> Merge topics
Processing file:/tmp/temp20240514160016393/dcf9bb8a920c382ea7ba32e8967195e2ec90832c.ditamap
Processing file:/tmp/temp20240514160016393/039fbe363f975fc6dad0a5db7ccad9092bc6aa0b.md

==> Build FO
Copying 4 files to /tmp/temp20240514160016393/Configuration/OpenTopic
Using document.locale=en
Processing /tmp/temp20240514160016393/test_MERGED.xml to /tmp/temp20240514160016393/stage1.xml
Loading stylesheet file:/opt/app/plugins/org.dita.pdf2.fop/xsl/fo/topic2fo_shell_fop.xsl
Loading stylesheet file:/opt/app/plugins/org.dita.pdf2.fop/xsl/fo/topic2fo_shell_fop.xsl
Processing file:/tmp/temp20240514160016393/stage1.xml to file:/tmp/temp20240514160016393/stage2.fo
Processing file:/tmp/temp20240514160016393/stage2.fo to file:/tmp/temp20240514160016393/topic.fo
Loading stylesheet file:/opt/app/plugins/org.dita.pdf2/xsl/fo/i18n-postprocess.xsl

==> Format PDF
[ERROR] Anttask - Error rendering fo file: /tmp/temp20240514160016393/topic.fo <org.apache.fop.apps.FOPException: java.io.FileNotFoundException: .fop (Permission denied)
java.io.FileNotFoundException: .fop (Permission denied)>org.apache.fop.apps.FOPException: java.io.FileNotFoundException: .fop (Permission denied)
java.io.FileNotFoundException: .fop (Permission denied)
        at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:652)
        at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:671)
        at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:532)
        at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:369)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.dita.dost.invoker.Main.runBuild(Main.java:853)
        at org.dita.dost.invoker.Main.startAnt(Main.java:240)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: org.apache.fop.apps.FOPException: java.io.FileNotFoundException: .fop (Permission denied)
java.io.FileNotFoundException: .fop (Permission denied)
        at org.apache.fop.util.LogUtil.handleException(LogUtil.java:57)
        at org.apache.fop.fonts.FontCache.saveTo(FontCache.java:222)
        at org.apache.fop.fonts.FontCacheManagerFactory$FontCacheManagerImpl.save(FontCacheManagerFactory.java:71)
        at org.apache.fop.fonts.FontManager.saveCache(FontManager.java:142)
        at org.apache.fop.fonts.DefaultFontConfigurator.configure(DefaultFontConfigurator.java:103)
        at org.apache.fop.render.PrintRendererConfigurator.getCustomFontCollection(PrintRendererConfigurator.java:147)
        at org.apache.fop.render.PrintRendererConfigurator.setupFontInfo(PrintRendererConfigurator.java:127)
        at org.apache.fop.render.intermediate.IFUtil.setupFonts(IFUtil.java:170)
        at org.apache.fop.render.intermediate.IFRenderer.setupFontInfo(IFRenderer.java:187)
        at org.apache.fop.area.RenderPagesModel.<init>(RenderPagesModel.java:75)
        at org.apache.fop.area.AreaTreeHandler.setupModel(AreaTreeHandler.java:135)
        at org.apache.fop.area.AreaTreeHandler.<init>(AreaTreeHandler.java:105)
        at org.apache.fop.render.RendererFactory.createFOEventHandler(RendererFactory.java:363)
        at org.apache.fop.fo.FOTreeBuilder.<init>(FOTreeBuilder.java:109)
        at org.apache.fop.apps.Fop.createDefaultHandler(Fop.java:104)
        at org.apache.fop.apps.Fop.<init>(Fop.java:78)
        at org.apache.fop.apps.FOUserAgent.newFop(FOUserAgent.java:184)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:108)
        at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:648)
        ... 45 more
Caused by: java.io.FileNotFoundException: .fop (Permission denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at org.apache.fop.fonts.FontCache.saveTo(FontCache.java:213)
        ... 62 more

/tmp/temp20240514160016393/topic.fo -> /src/out/test.pdf
Error: Build failed with an exception: org.dita.dost.exception.DITAOTException: [PDFX013F] The PDF file '/src/out/test.pdf' cannot be generated.
        at org.dita.dost.ant.DITAOTFailTask.execute(DITAOTFailTask.java:100)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.dita.dost.invoker.Main.runBuild(Main.java:853)
        at org.dita.dost.invoker.Main.startAnt(Main.java:240)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: No message
        at org.apache.tools.ant.taskdefs.Exit.execute(Exit.java:162)
        at org.dita.dost.ant.DITAOTFailTask.execute(DITAOTFailTask.java:98)
        ... 42 more

BUILD FAILED in 4 seconds
dita-ot-test$
```

## Environment
I'm using ubuntu 20.04.1 LTS with docker 20.10.12

**Comment by jelovirt** [comment]
FOP fails when reading the FOP font cache. Need to investigate where it is on the container.

**Comment by jelovirt** [comment]
When you run Docker with `--user $(id -u):$(id -g)`, you're basically trying to run the container with your current user ID and group ID. However, those do not exist in the container. Could you elaborate on why you do this, other than your company mandates this?

You can always create your own Docker image that builds on top of the DITA-OT image, and there create a user that has matching user ID and group.

**Comment by raven42** [comment]
We are looking to use a standard docker container that will work for any user to run on their local repository where the documentation files will all be. So each user will have their own uid:group values set on the files in their local repository. And our company does not allow service accounts, so we're kind of stuck where we need to be able to pass the uid:group into the docker run command like this so the output directory can be written to with the correct permissions. This will essentially become part of the build process with a common docker image. We'd prefer to use a standard one instead of maintaining our own, but we can do that if need be. The main issue is we don't want to create a new docker image every time a user is added or removed from the list of usernames.

Maybe an alternative would be to allow some environment variables to be used that can be passed into the docker image to set the uid:group for the output directory? Or maybe additional command line args that can provide a uid:group that the docker image can create on the fly?

**Comment by jelovirt** [comment]
@raven42 Off the top of my head, you could create a Docker image from DITA-OT base image that will override the `ENTRYPOINT` script with you custom `dita` script. That could first check that the user has a home directory and create it if it's missing. Then it would pass all the arguments to the built-in `dita` script.
