### ISSUE TITLE
DITA-OT does not properly transtypes anymore since 4.2

### ISSUE THREAD

**Issue by stefan-jung** [dita-ot/dita-ot#4502]
## Expected Behavior
The DITA-OT should properly recognize and support custom transtypes.

## Actual Behavior
Since DITA-OT 4.1 something has changed with the transtypes what makes my regression tests fail.

## Possible Solution
No idea

## Steps to Reproduce
You can see the effect in [this GitHub Action run](https://github.com/stefan-jung/org.jung.terminology/actions/runs/10317035726/job/28560462640). Builds with 4.1 and 4.2 are failing. But the [build script](https://github.com/stefan-jung/org.jung.terminology/blob/main/.github/workflows/main.yml) is the same for all DITA-OT versions.

## Copy of the error message, log file or stack trace
```
Run dita-ot-4.2.3/bin/dita --project=samples/terminology.xml --deliverable=termchecker-dita --output=4.2.3 --processing-mode=strict --verbose
Error: Build failed with an exception: org.dita.dost.exception.DITAOTException: [DOTA001F] 'termchecker-dita' is not a recognized transformation type. Supported transformation types are dita, eclipsehelp, html5, htmlhelp, markdown, markdown_gitbook, markdown_github, pdf, pdf2, xhtml.
	at org.dita.dost.ant.DITAOTFailTask.execute(DITAOTFailTask.java:100)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.dita.dost.invoker.Main.runBuild(Main.java:853)
	at org.dita.dost.invoker.Main.startAnt(Main.java:240)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: No message
	at org.apache.tools.ant.taskdefs.Exit.execute(Exit.java:[16](https://github.com/stefan-jung/org.jung.terminology/actions/runs/10317035726/job/28560462640#step:5:17)2)
	at org.dita.dost.ant.DITAOTFailTask.execute(DITAOTFailTask.java:98)
	... 16 more
```

**Comment by raducoravu** [comment]
From the error it looks like you did not install the plugin or that the dita --install encountered a problem installing it.

**Comment by stefan-jung** [comment]
@raducoravu, here is the detailed [raw log](https://productionresultssa12.blob.core.windows.net/actions-results/6698e9b0-7397-49d3-b8c3-53155f81be50/workflow-job-run-17cd5dfc-0c9c-55ae-93ef-334c198924f0/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-09T11%3A03%3A16Z&sig=9fW5cx9b%2BDaw%2BLG5gxzFG9jW8lCNY1D1I8sY5WIzKbA%3D&ske=2024-08-09T19%3A38%3A23Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-09T07%3A38%3A23Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-09T10%3A53%3A11Z&sv=2024-05-04). I cannot see any difference to the other DITA-OT versions and the previous commands do not throw any exceptions.

**Comment by raducoravu** [comment]
@stefan-jung I am not authorized to access your log file, if you run "dita --install" with "-v" or "-d" does it report maybe some extra problems?

**Comment by stefan-jung** [comment]
@raducoravu here is the detailed raw log for 4.0.2: [4.0.2.txt](https://github.com/user-attachments/files/16566363/4.0.2.txt). Script:

```
        run: |
          curl --location --remote-name https://github.com/dita-ot/dita-ot/releases/download/4.0.2/dita-ot-4.0.2.zip
          unzip -q dita-ot-4.0.2
          chmod +x dita-ot-4.0.2/bin/dita
          chmod +x dita-ot-4.0.2/bin/ant
          zip -qq -r org.jung.terminology.zip . -x ./.git/**\*
          zip -qq -r org.jung.terminology-webhelp-dummy-plugin.zip webhelp-dummy-plugin -x ./.git/**\*
          dita-ot-4.0.2/bin/dita install org.jung.terminology.zip --force
          dita-ot-4.0.2/bin/dita install org.jung.terminology-webhelp-dummy-plugin.zip --force
          dita-ot-4.0.2/bin/dita transtypes
```

And here is the detailed raw log for 4.2.3: [4.2.3.txt](https://github.com/user-attachments/files/16566379/4.2.3.txt). Script:

```
        run: |
          curl --location --remote-name https://github.com/dita-ot/dita-ot/releases/download/4.2.3/dita-ot-4.2.3.zip
          unzip -q dita-ot-4.2.3
          chmod +x dita-ot-4.2.3/bin/dita
          chmod +x dita-ot-4.2.3/bin/ant
          zip -qq -r org.jung.terminology.zip . -x ./.git/**\*
          zip -qq -r org.jung.terminology-webhelp-dummy-plugin.zip webhelp-dummy-plugin -x ./.git/**\*
          dita-ot-4.2.3/bin/dita install org.jung.terminology.zip --force
          dita-ot-4.2.3/bin/dita install org.jung.terminology-webhelp-dummy-plugin.zip --force
          dita-ot-4.2.3/bin/dita transtypes 
```

Maybe I am blind, but this looks exactly the same to me.

**Comment by raducoravu** [comment]
How about if you copy both plugins to the DITA OT "plugins" folder and then just run plain "dita --install"?
Because right now I'm not sure why you are zipping them in order for the DITA OT to unzip them when it installs them...

**Comment by stefan-jung** [comment]
@raducoravu copying instead of zipping has helped, but as I still think this is a bug, I'll leave this issue open.
