### ISSUE TITLE
NullPointerException with --root-chunk-override=combine and xref in Dita 2.0 content

### ISSUE THREAD

**Issue by TiboGr** [dita-ot/dita-ot#4511]
## Steps to Reproduce

1. Download following test case (source is Dita 2.0, one of the topics contains a `<xref/>` element ): 
[test_case.zip](https://github.com/user-attachments/files/17061120/test_case.zip)

2. Launch following command `dita -i map.ditamap -o out -f dita --root-chunk-override=combine`
3. Process ends with an error, no output is produced

## Copy of the error message, log file or stack trace

```
Error: Build failed with an exception: C:\DITA_OT\plugins\org.dita.base\build.xml:28: The following error occurred while executing this line:
C:\DITA_OT\plugins\org.dita.base\build_preprocess2.xml:314: java.lang.NullPointerException: Cannot invoke "java.net.URI.resolve(java.net.URI)" because "src" is null
        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:582)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.dita.dost.invoker.Main.runBuild(Main.java:853)
        at org.dita.dost.invoker.Main.startAnt(Main.java:240)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: C:\DITA_OT\plugins\org.dita.base\build_preprocess2.xml:314: java.lang.NullPointerException: Cannot invoke "java.net.URI.resolve(java.net.URI)" because "src" is null
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:109)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
        ... 17 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URI.resolve(java.net.URI)" because "src" is null
        at org.dita.dost.chunk.ChunkModule.rewriteLinks(ChunkModule.java:480)
        at org.dita.dost.chunk.ChunkModule.lambda$generateChunks$11(ChunkModule.java:445)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at org.dita.dost.chunk.ChunkModule.generateChunks(ChunkModule.java:440)
        at org.dita.dost.chunk.ChunkModule.processCombine(ChunkModule.java:152)
        at org.dita.dost.chunk.ChunkModule.execute(ChunkModule.java:67)
        at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:210)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        ... 24 more
```

## Environment

* DITA-OT version: 4.2.3
* Operating system and version: Windows
* How did you run DITA-OT? `dita` command
* Transformation type: HTML5, dita, ...

**Comment by raducoravu** [comment]
A bit similar with #4036 but not sure if the same thing
